let cy = { 
       
    "Categories",
    "Share this event",
    "Language",
    "Show Time Zone",
    "Custom Local Settings",
    "Add and showcase events on your site using a beautiful calendar.",
    "Week Days",
    "Manage Events",
    "General",
    "Layout Picker",
    "Month",
    "Monthly",
    "Week",
    "Weekly",
    "Day",
    "Daily",
    "Agenda",
    "Navigation Buttons",
    "Week numbers",
    "Include Weekends",
    "All-day",
    "All Day",
    "Label",
    "Fit to Height",
    "To set App proportions manully disable this option and resize Calendar in Editor.",
    "Default Layout",
    "Monthly view",
    "Weekly and Daily view",
    "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.",
    "Fixed Weekly Layout",
    "back",
    "Row",
    "Hours in Weekly View",
    "Hours in Daily View",
    "Start",
    "End",
    "At This Hour",
    "Button",
    "Buttons",
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Default Date",
    "year",
    "month",
    "mo",
    "days",
    "ago",
    "ahead",
    "Yesterday",
    "Today",
    "Tomorrow",
    "Custom",
    "Set Daily Rows Limit",
    "Set Proportions",
    "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.",
    "Container",
    "Background",
    "Container Background",
    "Container Borders",
    "Calendar",
    "Event Info Tooltip",
    "When people hover over an event they’ll see all the info about it in a tooltip.",
    "Event Info Window",
    "This is the full information window that opens when someone clicks on the event.",
    "Use Gradient",
    "Vertical",
    "Horizontal",
    "First",
    "Second",
    "diagonal",
    "Radial",
    "Select option",
    "Solid",
    "Dotted",
    "Dashed",
    "Double",
    "Border Radius",
    "Padding",
    "Date Header",
    "Event Default Color",
    "Days of Week",
    "Days of Week Background",
    "Date",
    "Event Title",
    "Highlight today",
    "Highlight Color",
    "Hide",
    "Calendar Border Color",
    "Calendar Border Width",
    "Calendar Border Style",
    "Font Color",
    "Event Background",
    "Card Date Color",
    "Title Font",
    "Date Font",
    "Description Font",
    "Button Background",
    "Button Text",
    "Border Color",
    "Border Width",
    "Border Type",
    "Title",
    "Description",
    "Background Color",
    "Divider",
    "Event Details Font",
    "Website Link Color",
    "Developer Info",
    "User Guide",
    "Support e-mail",
    "Our Website",
    "App Review",
    "Enjoying App? Leave us a review in the App Market.",
    "Review Us",
    "Connect With Us",
    "What's your email?",
    "Invalid email address!",
    "Comments",
    "We'd love to hear from you. Send us a message.",
    "Message must be at least 5 characters long",
    "Send",
    "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.",
    "Main",
    "Localize",
    "Settings",
    "Layouts",
    "Advanced",
    "Design",
    "Support",
    "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.",
    "Date Format",
    "Time Format",
    "Text Direction",
    "Left to Right",
    "Right to Left",
    "Week Starts On",
    "Agenda Style",
    "Classic",
    "Modern",
    "Agenda Header",
    "Upcoming Events",
    "Agenda Event Limit",
    "Upgrade now and get a lot more features and enjoy your APP in full!",
    "Upgrade Now",
    "Hosting events that last all day? This lets you show them on your calendar.",
    "24 hours",
    "Sat",
    "Sun",
    "Mon",
    "Default",
    "Select custom design style for your calendar.",
    "Style",
    "Styles and Colors",
    "Calendar Name",
    "Write your Calendar name here",
    "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.",
    "General Info",
    "Venue",
    "Organizer",
    "Search",
    "Add to",
    "calendar",
    "Copy event URL",
    "Copied!",
    "Add & Share",
    "Map",
    "Calendar view",
    "Add Event",
    "Uncategorised",
    "More",
    "Less",
    "Register",
    "Card",
    "Guests",
    "unlimited",
    "Show more",
    "Enable Search",
    "+ Add Event",
    "Manage and Sync",
    "Show event details as...",
    "Tooltip",
    "Popup",
    "None",
    "Show Category",
    "Header Align",
    "Show Time",
    "Hours in Weekly/Daily View",
    "Share Events",
    "Shadow",
    "Inner Padding",
    "Text",
    "Active Button Border",
    "Light Mode",
    "Event Text Color",
    "Dates",
    "Skeleton",
    "Skeleton Color",
    "Width",
    "Skeleton Style",
    "Color",
    "Section Titles",
    "Section Content",
    "Header",
    "Standard",
    "Retro",
    "Silver",
    "Night",
    "Dark",
    "Aubergine",
    "Map Header",
    "Show Title in mobile",
    "Card View",
    "Card background color",
    "Title font",
    "Desciption font",
    "Section font",
    "Section divider color",
    "Add event",
    "All Day Event",
    "Location",
    "Choose a category",
    "Venue name",
    "Venue phone",
    "Venue email",
    "Venue website",
    "Organizer name",
    "Organizer phone",
    "Organizer email",
    "Organizer website",
    "Personal info",
    "First name",
    "Last name",
    "Email Address",
    "Additional Notes",
    "Back",
    "Save",
    "Next",
    "Your event has been submitted",
    "Event submittion has been failed",
    "e.g. Birthday Party",
    "First Name",
    "Last Name",
    "Phone Number",
    "Address",
    "Your comments",
    "How many guests?",
    "Anything else we need to know?",
    "Guests:",
    "Submit",
    "Go to Calendar",
    "Registration completed successfully!",
    "Please check your registered email address",
    "Add to Calendar",
    "Share this Event",
    "Sorry something went wrong",
    "Back to registration",
    "Date & Location",
    "Date & Time",
    "home",
    "Header align",
    "Footer",
    "Categories Filter",
    "Show only upcoming",
    "Card(s) in a row",
    "Space between cards",
    "Shown events limit",
    "Style 1",
    "Style 2",
    "Style 3",
    "Style 4",
    "Buttons & Links",
    "Button corner radius",
    "Buttons font",
    "Buttons background",
    "Get notified by Email",
    "Review events",
    "Click on date",
    "Add Event button",
    "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
    "connect",
    "Synchronized Calendars",
    "Import events",
    "Disconnect",
    "Choose calendar",
    "Monitor your Wix events through the sync feature",
    "Connect all your Boom calendars available on your website",
    "Schedule, join, and manage Zoom meetings right through our Boom Calendar.",
    "Monitor your Event Brite events through the Event Brite sync feature",
    "Email",
    "Add-ons",
    "Receive notification emails as soon as users add events to your calendar.",
    "Enable + button on the calendar header",
    "Accept or decline events added by customers before making them public.",
    "Switch Add Event",
    "Enable your browser cookies to connect to your account.",
    "Learn more",
    "Print Button",
    "Permit your users to print your Boom Event Calendar in any date range.",
    "Show Title on mobile",
    "Show Skeleton on mobile",
    "Start 7-day Business trial",
    "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.",
    "Please note: At the end of the trial period, you will be returned to your existing subscription plan.",
    "Not Now",
    "Start free trial",
    "Congrats!",
    "Your 7-day Business trial has been successfully activated.",
    "Done",
    "Title font color",
    "Desciption font color",
    "Section font color",
    "Card Header",
    "Category",
    "Display at the",
    "top",
    "bottom",
    "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only",
    "Processing your events",
    "Search for events",
    "There are no events added",
    "Location: To be determined",
    "No events for selected date",
    "Uncategorized",
    "Edit event",
    "Edit original event",
    "Copy event",
    "Copy as new event",
    "Delete event",
    "Stop repeating on this date",
    "Exclude this date",
    "Location is going to be announced",
    "Fill your personal information",
    "Check Box",
    "Single Choice",
    "Option",
    "Share Event",
    "Oops! Something went wrong",
    "We are sorry this event has already taken place",
    "Back to calendar",
    "This field is required",
    "Phone",
    "Number field",
    "Please provide a valid email",
    "Select at least one option",
    "Choose tickets to see total value",
    "tickets",
    "Choose Tickets",
    "Choose payment method",
    "Pay",
    "Total",
    "Free",
    "Buy tickets",
    "Sold Out",
    "Tickets are available",
    "Sales End",
    "Availible from",
    "Go to Orders",
    "Go to Details",
    "Group ticket",
    "Name",
    "Price",
    "Order by",
    "Order ID",
    "Applied",
    "Fees",
    "Enter promo code",
    "Apply",
    "Promo Code",
    "Cash",
    "You can find your e-tickets attached to your email or download them",
    "here",
    "Time",
    "Invalid promo code",
    "Credit card",
    "You will soon receive a confirmation message of successful registration to your email address.",
    "You can also check your order details below.",
    "at",
    "Buy",
    "Donation",
    "Enter price",
    "Choose",
    "Chosen",
    "Choose your plan",
    "week",
    "wk",
    "Choose plan cycle",
    "months",
    "years",
    "weeks",
    "Copy Event Url",
    "You can find your e-tickets attached to your email or print them",
    "Guest Info",
    "Ticket Info",
    "Ticket name",
    "Ticket price",
    "Ticket ID",
    "If you have any questions contact to organizer",
    "As soon as event ends",
    "1 day after event ends",
    "7 days after event ends",
    "14 days after event ends",
    "30 days after event ends",
    "Menu",
    "No event for selected date",
    "view",
    "List",
    "Year",
    "Yearly",
    "Year view header",
    "Yearly Style",
    "There are no events",
    "Autotranslation",
    "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.",
    "Note on mobile",
    "Turn off or change the text of the “No events” bar on mobile version of calendar",
    "Autodeletion",
    "Enabling the option, will automatically remove your past events from the calendar.",
    "This does not apply to repeating events!",
    "Notify event creators about the guest",
    "Send event creators notification emails as soon as guests register for their events",
    "List View Type",
    "Description font",
    "Connect",
    "You have no events",
    "Synchronize",
    "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
    "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.",
    "Your message has been sent successfully!",
    "There are no synchronized calendars",
    "to view more than 7 events",
    "Mobile app",
    "Admin Account",
    "Password",
    "Second User",
    "Edit",
    "Guest limit",
    "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.",
    "available",
    "next",
    "Tickets",
    "Quantity",
    "Promo code",
    "Select a payment method",
    "Fee",
    "Book",
    "All the tickets have been sold out",
    "Choose at least one ticket",
    "First choose ticket",
    "Please fill out your personal information.",
    "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.",
    "Credit/Debit card",
    "print here.",
    "QR code for all tickets",
    "Duration",
    "Full Name",
    "Ticket id",
    "Group id",
    "Choose your ticket.",
    "Fill out your personal information.",
    "Add the payment details.",
    "To be determined",
    "You can find your e-tickets attached to the email or",
    "print here",
    "Full name",
    "Group ID",
    "to Book",
    "Unfortunately, your card has been declined",
    "Thank you for your purchase!",
    "Find your printable e-tickets attached to the confirmation email",
    "Confirm",
}
export default cy