let fi = {
  "Custom Link": "Mukautettu linkki",
  "Link to event page": "Linkki tapahtumasivulle",
  "No link": "Ei linkkiä",
  "Attach File": "Liitä tiedosto",
  "To be announced": "Ilmoitetaan",
  "Online": "verkossa",
  "Physical": "Fyysinen",
  "Select Categories to display events related to them, or manually choose specific events under Events": "Valitse Luokat näyttääksesi niihin liittyvät tapahtumat tai valitse tietyt tapahtumat manuaalisesti Tapahtumat-kohdasta",
  "Automatically approve events from these addresses": "Hyväksy tapahtumat automaattisesti näistä osoitteista",
  "Approve events": "Hyväksy tapahtumat",
  "Payable with a plan": "Maksetaan suunnitelmalla",
  "Service Details": "Palvelun tiedot",
  "participants": "osallistujia",
  "To": "Vastaanottaja",
  "From": "From",
  "Ahead": "Eteenpäin",
  "Ago": "Sitten",
  "Change the category": "Vaihda luokkaa",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Ticket Tailor -synkronoinnin avulla voit integroida tapahtumat ja istunnot Boom-kalenteriin.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Näytä tapahtuman aika otsikon vieressä. Tämä asetus koskee vain kuukausi-, päivä- ja viikkonäkymiä.",
  "Show Staff Member": "Näytä henkilöstön jäsen",
  "Show Price": "Näytä hinta",
  "To Event Page": "Tapahtumasivulle",
  "Layout": "Layout",
  "Acending": "Nouseva",
  "Yearly": "Vuosittain",
  "Layout device": "Asettelulaite",
  "Date container font": "Päivämääräsäilön fontti",
  "Hide Fully Booked Slots": "Piilota täysin varatut paikat",
  "Enable": "ota käyttöön",
  "Limit": "Raja",
  "Export": "Viedä",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Olet muuttamassa tapahtumasi tietoja. Kun muutat, vieraslistasi menetetään.",
  "Change Date": "Muuta päivämäärää",
  "Ends": "Päättyy",
  "On": "Päällä",
  "After": "Jälkeen",
  "Accept": "Hyväksyä",
  "Show less": "Näytä vähemmän",
  "Venue detail": "Tapahtumapaikan yksityiskohdat",
  "Reject": "Hylätä",
  "See guest list": "Katso vieraslista",
  "Submit Date": "Lähetyspäivämäärä",
  "Total guests": "Vieraita yhteensä",
  "Do you really want to delete selected user? Once removed, cannot be undone.": "Haluatko todella poistaa valitun käyttäjän? Kun se on poistettu, sitä ei voi kumota.",
  "Delete Guest": "Poista vieras",
  "Invoice number": "Laskun numero",
  "Status": "Tila",
  "Payment type": "Maksutapa",
  "Select payment method to receive fees through tickets": "Valitse maksutapa saadaksesi maksut lippujen kautta",
  "Add Code": "Lisää koodi",
  "Add End Time": "Lisää lopetusaika",
  "Discount": "Alennus",
  "Promo codes for the sales": "Tarjouskoodit myyntiin",
  "Promo codes": "Tarjouskoodit",
  "Add Ticket": "Lisää lippu",
  "Limit type": "Rajan tyyppi",
  "Paid": "Maksettu",
  "Participation tickets for your event": "Osallistumisliput tapahtumaasi",
  "Show the ticket limit": "Näytä lippujen raja",
  "Show limit": "Näytä raja",
  "Show the price on ticket": "Näytä hinta lipussa",
  "Enable and configure your ticketing system": "Ota lippujärjestelmä käyttöön ja määritä se",
  "Stop repeating here": "Lopeta toistaminen tähän",
  "Limited": "Rajoitettu",
  "Unlimited": "Rajoittamaton",
  "Thank you message title": "Kiitos viestin otsikko",
  "Submit button text": "Lähetä-painikkeen teksti",
  "Registration button text": "Rekisteröintipainikkeen teksti",
  "Texts": "Tekstit",
  "Modify the displayed texts": "Muokkaa näytettäviä tekstejä",
  "Thank you message body": "Kiitos viestin runko",
  "Notify the user when the registration is canceled": "Ilmoita käyttäjälle, kun rekisteröinti perutaan",
  "Cancellation email": "Peruutus sähköposti",
  "Send a reminder to the user one day prior to the event": "Lähetä muistutus käyttäjälle päivää ennen tapahtumaa",
  "Reminder email": "Muistutus sähköposti",
  "Send an instant email to the user once registration is completed": "Lähetä käyttäjälle välittömästi sähköposti, kun rekisteröinti on valmis",
  "Notification email": "Ilmoitus sähköposti",
  "Reminder email about the event": "Muistutus sähköpostilla tapahtumasta",
  "Email notifications to users": "Sähköposti-ilmoitukset käyttäjille",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).": "Napsauta kunkin kentän vieressä olevia vaihtopainikkeita lisätäksesi sen rekisteröintilomakkeellesi. Jos haluat tehdä kentän pakolliseksi, napsauta tähteä (*).",
  "Form Fields": "Lomakekentät",
  "Enter your form description": "Kirjoita lomakkeen kuvaus",
  "Form Title": "Lomakkeen otsikko",
  "Enter your form title": "Kirjoita lomakkeen otsikko",
  "Form Details": "Lomakkeen tiedot",
  "Configure your registration form fields": "Määritä rekisteröintilomakkeen kentät",
  "Show guest limit": "Näytä vierasrajoitus",
  "Enable Registration": "Ota rekisteröinti käyttöön",
  "Click to activate registration on this event": "Napsauta aktivoidaksesi rekisteröinnin tähän tapahtumaan",
  "Customize the general settings of registration": "Mukauta rekisteröinnin yleisiä asetuksia",
  "Enter URL": "Syötä URL",
  "Page URL": "Sivun URL-osoite",
  "Close registration when the event starts": "Sulje ilmoittautuminen tapahtuman alkaessa",
  "Redirect to a different website": "Ohjaa toiselle verkkosivustolle",
  "Where users can register": "Mihin käyttäjät voivat rekisteröityä",
  "Open event registration landing page": "Avaa tapahtuman ilmoittautumissivu",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.": "On täytynyt vaatia paljon valmistautumista valmistautuaksesi tapahtumaasi. Nyt on aika rentoutua, kunnes vieraasi kokoontuvat! Heti kun uusi rekisteröinti on tehty, tiedot vieraastasi näkyvät täällä. Palaa myöhemmin seuraamaan tapahtumasi osallistujia.",
  "You have no guests at the moment.": "Sinulla ei ole vieraita tällä hetkellä.",
  "List of people who are registered to your event": "Lista ihmisistä, jotka ovat rekisteröityneet tapahtumaasi",
  "Guest List": "Vieraslista",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.": "Tämä on toistuva tapahtuma! Kaikki tähän tapahtumaan tehdyt muutokset koskevat kaikkia toistoja.",
  "Repeated event": "Toistuva tapahtuma",
  "Delete Category": "Poista luokka",
  "Do you really want to delete selected category? Once removed, cannot be undone.": "Haluatko todella poistaa valitun luokan? Kun se on poistettu, sitä ei voi kumota.",
  "OK": "OK",
  "Exclude": "Sulje pois",
  "Custom recurrence": "Mukautettu toistuminen",
  "Duplicate": "Kopioi",
  "Delete": "Poistaa",
  "Published": "Julkaistu",
  "Drafts": "Luonnokset",
  "User events": "Käyttäjätapahtumat",
  "Add new category": "Lisää uusi luokka",
  "Manage categories": "Hallinnoi luokkia",
  "Add category": "Lisää kategoria",
  "Never": "Ei koskaan",
  "Repeat every": "Toista joka",
  "Do you really want to delete selected event? Once removed, cannot be undone": "Haluatko todella poistaa valitun tapahtuman? Kun se on poistettu, sitä ei voi kumota",
  "There are no categories yet": "Luokkia ei vielä ole",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.": "Muutosten tekeminen synkronoituun kalenteriisi seuraavien linkkien avulla. Tarkista muutokset huolellisesti.",
  "occurrences": "tapahtumia",
  "Save as draft": "Tallenna luonnoksena",
  "More Info": "Lisätietoja",
  "Book Now": "Varaa nyt",
  "Show participants": "Näytä osallistujat",
  "This service is fully booked.": "Tämä palvelu on täysin varattu.",
  "All sessions are fully booked.": "Kaikki istunnot on varattu täysin.",
  "Registration closed": "Rekisteröinti suljettu",
  "Show your Wix Bookings or Events on Calendar": "Näytä Wix -varauksesi tai tapahtumat kalenterissa",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.": "Valitse Auto kaikkien kalenterin palvelujen ja istuntojen automaattisen näytön tai manuaalisen valinnan käsikirjan.",
  "Show cancelled events": "Näytä peruutetut tapahtumat",
  "Event Color": "Tapahtumien väri",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.": "Valitse automaattinen näyttö kaikkien kalenterin tapahtumien tai manuaalisen valinnan käsikirjan.",
  "Auto": "Auto",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.": "Valitse Auto kaikkien kalenterin organisaatioiden ja järjestäjien automaattisen näytön tai manuaalisen valinnan käsikirjan.",
  "Manual": "Manuaalinen",
  "Sync method": "Synkronointimenetelmä",
  "Enable synchronization": "Ota synkronointi käyttöön",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only": "Esittele luokkasuodatin kalenterin yläosassa tai alareunassa. Asetukset koskevat vain esityslistaa, risti-, aikajanaa ja korttinäkymiä",
  "Load Events": "Lastatapahtumat",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.": "Kun kalenteri -widget on käytössä, se käännetään verkkosivuston kielen perusteella. Huomaa, että niin kauan kuin kalenterinimikkeet ja kuvaukset syötetään tekstinä, niitä ei voida kääntää.",
  "Choose plan type": "Valitse suunnitelmatyyppi",
  "Api key": "API -avain",
  "Synchronized Boxes": "Synkronoidut laatikot",
  "Choose box": "Valitse laatikko",
  "There are no synchronized boxes": "Ei ole synkronoituja laatikoita",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Lippu räätälöity synkronointi antaa sinun integroida tapahtumat ja istunnot puomikalenterisi kanssa",
  Categories: "Luokat",
  "Share this event": "Jaa tämä tapahtuma",
  Language: "Kieli",
  "Show Time Zone": "Näytä aikavyöhyke",
  "Custom Local Settings": "Mukautetut paikalliset asetukset",
  "Add and showcase events on your site using a beautiful calendar.":
    "Lisää ja esittele tapahtumia sivustollesi kauniilla kalenterilla.",
  "Week Days": "Viikkopäivät",
  "Manage Events": "Hallitse tapahtumia",
  General: "Yleinen",
  "Layout Picker": "Poiminta",
  Month: "Kuukausi",
  Monthly: "Kuukausittain",
  Week: "Viikko",
  Weekly: "Viikoittain",
  Day: "Päivä",
  Daily: "Päivittäin",
  Agenda: "Esityslista",
  "Navigation Buttons": "Navigointipainikkeet",
  "Week numbers": "Viikonumerot",
  "Include Weekends": "Sisällytä viikonloppuja",
  "All-day": "Koko päivä",
  "All Day": "Koko päivä",
  Label: "Merkitä",
  "Fit to Height": "Sopia korkeuteen",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Aseta sovellusosuudet poistamaan tämän vaihtoehdon manuaalisesti käytöstä ja muuttamaan kalenterin kokoa editorissa.",
  "Default Layout": "Laiminlyönti",
  "Monthly view": "Kuukausittainen näkymä",
  "Weekly and Daily view": "Viikko- ja päivittäinen näkymä",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Voit antaa kävijöille johdonmukaisemman kokemuksen näyttämällä saman määrän viikkoja (6) kerrallaan.",
  "Fixed Weekly Layout": "Kiinteä viikoittainen asettelu",
  back: "takaisin",
  Row: "Rivi",
  "Hours in Weekly View": "Tunnit viikoittain",
  "Hours in Daily View": "Tunteja päivittäisessä näkymässä",
  Start: "alkaa",
  End: "Loppu",
  "At This Hour": "Tähän aikaan",
  Button: "Painike",
  Buttons: "Painikkeet",
  Sunday: "sunnuntai",
  Monday: "maanantai",
  Tuesday: "tiistai",
  Wednesday: "keskiviikko",
  Thursday: "torstai",
  Friday: "perjantai",
  Saturday: "Lauantai",
  "Default Date": "Oletuspäivämäärä",
  year: "vuosi",
  month: "kuukausi",
  mo: "MO",
  days: "päivä",
  ago: "sitten",
  ahead: "eteenpäin",
  Yesterday: "Eilen",
  Today: "Tänään",
  Tomorrow: "Huomenna",
  Custom: "Mukautettu",
  "Set Daily Rows Limit": "Aseta päivittäiset rivit",
  "Set Proportions": "Aseta mittasuhteet",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Anna vierailijan lisätä tapahtumaa paikallisiin calnedarsiin: Google, Yahoo, Outlook, Icalendar.",
  Container: "Astia",
  Background: "Tausta",
  "Container Background": "Konttitausta",
  "Container Borders": "Konttien rajat",
  Calendar: "Kalenteri",
  "Event Info Tooltip": "Tapahtumatiedot työkaluvihje",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kun ihmiset leijuvat tapahtuman yli, he näkevät kaikki tiedot siitä työkaluvinkkiin.",
  "Event Info Window": "Tapahtumatietoikkuna",
  "This is the full information window that opens when someone clicks on the event.":
    "Tämä on koko tietoikkuna, joka avautuu, kun joku napsauttaa tapahtumaa.",
  "Use Gradient": "Käyttää kaltevuutta",
  Vertical: "Pystysuora",
  Horizontal: "Vaakasuora",
  First: "Ensimmäinen",
  Second: "Toinen",
  diagonal: "diagonaali",
  Radial: "Säteilevä",
  "Select option": "Valitse vaihtoehto",
  Solid: "Kiinteä",
  Dotted: "Katkoviiva",
  Dashed: "Katkoviiva",
  Double: "Kaksinkertainen",
  "Border Radius": "Reunusäde",
  Padding: "Pehmuste",
  "Date Header": "Päiväysotsikko",
  "Event Default Color": "Tapahtuman oletusväri",
  "Days of Week": "Viikonpäivät",
  "Days of Week Background": "Viikonpäivien tausta",
  Date: "Päivämäärä",
  "Event Title": "Tapahtuman otsikko",
  "Highlight today": "Korostaa tänään",
  "Highlight Color": "Korostaa väriä",
  Hide: "Piilottaa",
  "Calendar Border Color": "Kalenterin reunaväri",
  "Calendar Border Width": "Kalenterin reunan leveys",
  "Calendar Border Style": "Kalenterin rajatyyli",
  "Font Color": "Fontin väri",
  "Event Background": "Tapahtuman tausta",
  "Card Date Color": "Kortin päivämäärä",
  "Title Font": "Otsikkofontti",
  "Date Font": "Päivämäärän fontti",
  "Description Font": "Kuvaus kirjasin",
  "Button Background": "Napin tausta",
  "Button Text": "Nappiteksti",
  "Border Color": "Reunuksen väri",
  "Border Width": "Rajan leveys",
  "Border Type": "Reunatyyppi",
  Title: "Otsikko",
  Description: "Kuvaus",
  "Background Color": "Taustaväri",
  Divider: "Jakaja",
  "Event Details Font": "Tapahtumatiedot fontti",
  "Website Link Color": "Verkkosivuston väri",
  "Developer Info": "Kehittäjätiedot",
  "User Guide": "Käyttöohjeet",
  "Support e-mail": "Tukea sähköpostiviestiä",
  "Our Website": "Meidän nettisivumme",
  "App Review": "APP -arvostelu",
  "Enjoying App? Leave us a review in the App Market.":
    "Nautitko sovelluksesta?Jätä meille arvostelu sovellusmarkkinoille.",
  "Review Us": "Tarkista meidät",
  "Connect With Us": "Yhdistä meihin",
  "What's your email?": "Mikä on sähköpostisi?",
  "Invalid email address!": "Virheellinen sähköpostiosoite!",
  Comments: "Kommentit",
  "We'd love to hear from you. Send us a message.":
    "Haluaisimme kuulla sinusta.Lähetä meille viesti.",
  "Message must be at least 5 characters long":
    "Viestin on oltava vähintään 5 merkkiä pitkä",
  Send: "Lähettää",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jos haluat antaa käyttäjän vaihtaa kalenterinäkymät, ota tämä vaihtoehto käyttöön ja valitse näkymät, jotka haluat näyttää.",
  Main: "Pää-",
  Localize: "Paikallistaa",
  Settings: "asetukset",
  Layouts: "Asettelu",
  Advanced: "Pitkälle kehittynyt",
  Design: "Design",
  Support: "Tuki",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Kaikki paikalliset asetukset ovat (automaattisesti) kielen perusteella.Jos kielesi on luettelossa, tätä osaa ei tarvitse mukauttaa.",
  "Date Format": "Päivämäärämuoto",
  "Time Format": "Aikamuoto",
  "Text Direction": "Tekstin suunta",
  "Left to Right": "Vasemmalta oikealle",
  "Right to Left": "Oikealta vasemmalle",
  "Week Starts On": "Viikko alkaa",
  "Agenda Style": "Esityslistan tyyli",
  Classic: "Klassikko",
  Modern: "Moderni",
  "Agenda Header": "Esityslistan otsikko",
  "Upcoming Events": "Tulevat tapahtumat",
  "Agenda Event Limit": "Esityslistan tapahtumaraja",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Päivitä nyt ja saat paljon enemmän ominaisuuksia ja nauti sovelluksestasi kokonaan!",
  "Upgrade Now": "Päivitä nyt",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Isännöintitapahtumat, jotka kestävät koko päivän?Tämän avulla voit näyttää ne kalenterissasi.",
  "24 hours": "24 tuntia",
  Sun: "Aurinko",
  Mon: "Maanantai",
  Sat: "Istua",
  Default: "Laiminlyönti",
  "Select custom design style for your calendar.":
    "Valitse kalenterisi mukautettu suunnittelutyyli.",
  Style: "Tyyli",
  "Styles and Colors": "Tyylit ja värit",
  "Calendar Name": "Kalenterin nimi",
  "Write your Calendar name here": "Kirjoita kalenterimesi tähän",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Tämä ei ole käyttäjille näkyvä.Aseta nimet kalenterisi erottamiseksi, kun käytetään puomikalenterin synkronointitoimintoa.",
  "General Info": "Yleiset tiedot",
  Venue: "Paikka",
  Organizer: "Järjestäjä",
  Search: "Hae",
  "Add to": "Lisätä",
  calendar: "kalenteri",
  "Copy event URL": "Kopioi tapahtuman URL -osoite",
  "Copied!": "Kopioi!",
  "Add & Share": "Lisää ja jaa",
  Map: "Kartta",
  "Calendar view": "Kalenterinäkymä",
  "Add Event": "Lisätä tapahtumaa",
  Uncategorised: "Luokittelematon",
  More: "Lisää",
  Less: "Vähemmän",
  Register: "Rekisteröidä",
  Card: "Kortti",
  Guests: "Vieraat",
  unlimited: "rajoittamaton",
  "Show more": "Näytä lisää",
  "Enable Search": "Ota haku käyttöön",
  "+ Add Event": "+ Lisää tapahtuma",
  "Manage and Sync": "Hallita ja synkronoida",
  "Show event details as...": "Näytä tapahtuman yksityiskohdat ...",
  Tooltip: "Työkalu",
  Popup: "Ponnahdusikkuna",
  None: "Ei mitään",
  "Show Category": "Näyttelykategoria",
  "Header Align": "Otsikko kohdistaa",
  "Show Time": "Esitysaika",
  "Hours in Weekly/Daily View": "Tunnit viikoittain/päivittäisessä näkymässä",
  "Share Events": "Jaa tapahtumat",
  Shadow: "Varjo",
  "Inner Padding": "Sisäselvitys",
  Text: "Teksti",
  "Active Button Border": "Aktiivinen painike reuna",
  "Light Mode": "Valotila",
  "Event Text Color": "Tapahtumatekstiväri",
  Dates: "Päivämäärät",
  Skeleton: "Luuranko",
  "Skeleton Color": "Luurankoväri",
  Width: "Leveys",
  "Skeleton Style": "Luurankotyyli",
  Color: "Väri",
  "Section Titles": "Osastonimikkeet",
  "Section Content": "Osiosisältö",
  Header: "Otsikko",
  Standard: "Standardi",
  Retro: "Retro",
  Silver: "Hopea",
  Night: "Yö",
  Dark: "Tumma",
  Aubergine: "Munakoiso",
  "Map Header": "Karttaotsikko",
  "Show Title in mobile": "Näytä otsikko matkapuhelimessa",
  "Card View": "Kortinkuva",
  "Card background color": "Kortin taustaväri",
  "Title font": "Otsikkofontti",
  "Desciption font": "Desciption font",
  "Section font": "Osiofontti",
  "Section divider color": "Osanjakajan väri",
  "Add event": "Lisätä tapahtumaa",
  "All Day Event": "Koko päivän tapahtuma",
  Location: "Sijainti",
  "Choose a category": "Valitse kategoria",
  "Venue name": "Tapahtumapaikan nimi",
  "Venue phone": "Tapahtumapaikan puhelin",
  "Venue email": "Tapahtumapaikan sähköposti",
  "Venue website": "Tapahtumapaikan verkkosivusto",
  "Organizer name": "Järjestäjän nimi",
  "Organizer phone": "Järjestäjäpuhelin",
  "Organizer email": "Järjestäjän sähköposti",
  "Organizer website": "Järjestäjän verkkosivusto",
  "Personal info": "Henkilökohtaiset tiedot",
  "First name": "Etunimi",
  "Last name": "Sukunimi",
  "Email Address": "Sähköpostiosoite",
  "Additional Notes": "Lisämerkinnät",
  Back: "Takaisin",
  Save: "Tallentaa",
  Next: "Seuraava",
  "Your event has been submitted": "Tapahtumasi on lähetetty",
  "Event submittion has been failed":
    "Tapahtuman lähettäminen on epäonnistunut",
  "e.g. Birthday Party": "esim.Syntymäpäiväjuhlat",
  "First Name": "Etunimi",
  "Last Name": "Sukunimi",
  "Phone Number": "Puhelinnumero",
  Address: "Osoite",
  "Your comments": "Kommenttisi",
  "How many guests?": "Kuinka monta vierasta?",
  "Anything else we need to know?": "Mitä muuta meidän on tiedettävä?",
  "Guests:": "Vieraat:",
  Submit: "Lähetä",
  "Go to Calendar": "Mennä kalenteriin",
  "Registration completed successfully!":
    "Rekisteröinti valmistui onnistuneesti!",
  "Please check your registered email address":
    "Tarkista rekisteröity sähköpostiosoite",
  "Add to Calendar": "Lisää kalenteriin",
  "Share this Event": "Jaa tämä tapahtuma",
  "Sorry something went wrong": "Pahoittelut, jotain meni pieleen",
  "Back to registration": "Takaisin rekisteröintiin",
  "Date & Location": "Päivämäärä ja sijainti",
  "Date & Time": "Treffiaika",
  home: "Koti",
  "Header align": "Otsikko kohdistaa",
  Footer: "Alatunniste",
  "Categories Filter": "Kategoriat suodatin",
  "Show only upcoming": "Näytä vain tuleva",
  "Card(s) in a row": "Kortti (t) peräkkäin",
  "Space between cards": "Tilaa korttien välillä",
  "Shown events limit": "Näytetyt tapahtumat rajoittavat",
  "Style 1": "Tyyli 1",
  "Style 2": "Tyyli 2",
  "Style 3": "Tyyli 3",
  "Style 4": "Tyyli 4",
  "Buttons & Links": "Napit ja linkit",
  "Button corner radius": "Nappikulman säde",
  "Buttons font": "Painikkeet fontti",
  "Buttons background": "Napit",
  "Get notified by Email": "Saada ilmoitusta sähköpostitse",
  "Review events": "Tarkastele tapahtumia",
  "Click on date": "Napsauta päivämäärää",
  "Add Event button": "Lisää tapahtumapainike",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Kalenterisynkronointi antaa sinun integroida tapahtumat ja istunnot puomikalenteriin.",
  connect: "kytkeä",
  "Synchronized Calendars": "Synkronoidut kalenterit",
  "Import events": "Tuontitapahtumat",
  Disconnect: "Katkaista",
  "Choose calendar": "Valitse kalenteri",
  "Monitor your Wix events through the sync feature":
    "Seuraa WIX -tapahtumiasi synkronointiominaisuuden kautta",
  "Connect all your Boom calendars available on your website":
    "Yhdistä kaikki verkkosivustollasi käytettävissä olevat puomikalenterit",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Aikataulu, liity ja hallitse zoom -kokouksia suoraan puomikalenterimme kautta.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Seuraa Eventbrite -tapahtumiasi Eventbrite Sync -ominaisuuden kautta",
  Email: "Sähköposti",
  "Add-ons": "Lisäosat",
  "Receive notification emails as soon as users add events to your calendar.":
    "Vastaanota ilmoitussähköposteja heti, kun käyttäjät lisäävät tapahtumia kalenteriin.",
  "Enable + button on the calendar header":
    "Ota käyttöön + -painike kalenterin otsikossa",
  "Accept or decline events added by customers before making them public.":
    "Hyväksy tai hylkää asiakkaiden lisäämisen ennen niiden julkistamista.",
  "Switch Add Event": "Kytkin Lisää tapahtuma",
  "Enable your browser cookies to connect to your account.":
    "Ota selain -evästeesi yhteyden muodostamiseen tilillesi.",
  "Learn more": "Oppia lisää",
  "Print Button": "Tulostuspainike",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Anna käyttäjien tulostaa Boom -tapahtumakalenterisi millä tahansa ajanjaksolla.",
  "Show Title on mobile": "Näytä otsikko matkapuhelimella",
  "Show Skeleton on mobile": "Näytä luuranko matkapuhelimella",
  "Start 7-day Business trial": "Aloita 7 päivän yrityskoe",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Nauti kaikista rajoittamattomista ominaisuuksista, kuten myydä lippuja, rekisteröintiä, vierailutapahtumien lisäosia.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Huomaa: Koeajan lopussa sinut palautetaan nykyiseen tilaussuunnitelmaan.",
  "Not Now": "Ei nyt",
  "Start free trial": "Aloita ilmainen kokeilu",
  "Congrats!": "Onnittelut!",
  "Your 7-day Business trial has been successfully activated.":
    "Seitsemän päivän yrityskoe on aktivoitu onnistuneesti.",
  Done: "Tehty",
  "Title font color": "Otsikkofonttiväri",
  "Desciption font color": "Desciption font -väri",
  "Section font color": "Osiofonttiväri",
  "Card Header": "Kortin otsikko",
  Category: "Kategoria",
  "Display at the": "Näytä",
  top: "ylhäältä",
  bottom: "pohja",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Esittele luokkasuodatin kalenterin yläosassa tai alareunassa.Asetukset koskevat vain esityslistan ja kortinäkymiä",
  "Processing your events": "Tapahtumien käsittely",
  "Search for events": "Etsi tapahtumia",
  "There are no events added": "Tapahtumia ei ole lisätty",
  "Location: To be determined": "Sijainti: määritettävä",
  "No events for selected date": "Ei tapahtumia valitulle päivälle",
  Uncategorized: "Luokittelematon",
  "Edit event": "Muokkaustapahtuma",
  "Edit original event": "Muokkaa alkuperäinen tapahtuma",
  "Copy event": "Kopiotapahtuma",
  "Copy as new event": "Kopioi uusi tapahtuma",
  "Delete event": "Poistaa tapahtuma",
  "Stop repeating on this date": "Lopeta toistaminen tänä päivänä",
  "Exclude this date": "Sulje pois tämä päivämäärä",
  "Location is going to be announced": "Sijainti ilmoitetaan",
  "Fill your personal information": "Täytä henkilökohtaiset tietosi",
  "Check Box": "Valintaruutu",
  "Single Choice": "Yksi valinta",
  Option: "Vaihtoehto",
  "Share Event": "Jaa tapahtuma",
  "Oops! Something went wrong": "Oho!Jotain meni pieleen",
  "We are sorry this event has already taken place":
    "Olemme pahoillamme, että tämä tapahtuma on jo tapahtunut",
  "Back to calendar": "Takaisin kalenteriin",
  "This field is required": "Tämä kenttä pitää täyttää",
  Phone: "Puhelin",
  "Number field": "Lukukenttä",
  "Please provide a valid email": "Anna kelvollinen sähköposti",
  "Select at least one option": "Valitse vähintään yksi vaihtoehto",
  "Choose tickets to see total value": "Valitse liput nähdäksesi kokonaisarvon",
  tickets: "liput",
  "Choose Tickets": "Valitse liput",
  "Choose payment method": "Valitse maksutapa",
  Pay: "Maksaa",
  Total: "Kaikki yhteensä",
  Free: "Vapaa",
  "Buy tickets": "Osta lippuja",
  "Sold Out": "Loppuunmyyty",
  "Tickets are available": "Liput ovat saatavilla",
  "Sales End": "Myyntipää",
  "Availible from": "saatavilla",
  "Go to Orders": "Mennä käskyihin",
  "Go to Details": "Siirry yksityiskohtiin",
  "Group ticket": "Ryhmälippu",
  Name: "Nimi",
  Price: "Hinta",
  "Order by": "Tilata",
  "Order ID": "tilausnumero",
  Applied: "Sovellettu",
  Fees: "Palkkiot",
  "Enter promo code": "Kirjoita tarjouskoodi",
  Apply: "Käytä",
  "Promo Code": "Tarjouskoodi",
  Cash: "Käteinen raha",
  "You can find your e-tickets attached to your email or download them":
    "Löydät sähköpostiisi liitetyt sähköiset lippuja tai lataa ne",
  here: "tässä",
  Time: "Aika",
  "Invalid promo code": "Virheellinen tarjouskoodi",
  "Credit card": "Luottokortti",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Saat pian vahvistusviestin onnistuneesta rekisteröinnistä sähköpostiosoitteeseesi.",
  "You can also check your order details below.":
    "Voit myös tarkistaa tilauksen yksityiskohdat alla.",
  at: "at",
  Buy: "Ostaa",
  Donation: "Lahjoitus",
  "Enter price": "Antaa hintaan",
  Choose: "Valita",
  Chosen: "Valittu",
  "Choose your plan": "Valitse suunnitelmasi",
  week: "viikko",
  wk: "viitat",
  "Choose plan cycle": "Valitse suunnitelma sykli",
  months: "kuukaudet",
  years: "vuotta",
  weeks: "viikot",
  "Copy Event Url": "Kopioi tapahtuman URL -osoite",
  "You can find your e-tickets attached to your email or print them":
    "Löydät sähköpostiisi liitetyt sähköiset lippuja tai tulosta ne",
  "Guest Info": "Vierastiedot",
  "Ticket Info": "Lipputiedot",
  "Ticket name": "Lipun nimi",
  "Ticket price": "Lipun hinta",
  "Ticket ID": "Lipputunnus",
  "If you have any questions contact to organizer":
    "Jos sinulla on kysyttävää järjestäjälle",
  "As soon as event ends": "Heti kun tapahtuma päättyy",
  "1 day after event ends": "1 päivä tapahtuman päättymisen jälkeen",
  "7 days after event ends": "7 päivää tapahtuman päättymisen jälkeen",
  "14 days after event ends": "14 päivää tapahtuman päättymisen jälkeen",
  "30 days after event ends": "30 päivää tapahtuman päättymisen jälkeen",
  Menu: "Valikko",
  "No event for selected date": "Ei tapahtumaa valitulle päivälle",
  view: "näkymä",
  List: "Lista",
  Year: "Vuosi",
  Yearly: "Vuosittain",
  "Year view header": "Vuodenäkymäotsikko",
  "Yearly Style": "Vuosittainen tyyli",
  "There are no events": "Tapahtumia ei ole",
  Autotranslation: "Autotranslaatio",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Kun kalenteri -widget on käytössä, se käännetään verkkosivuston kielen perusteella.*Huomaa, että niin kauan kuin kalenterin otsikko ja kuvaukset on syötettyjä tekstejä, niitä ei voida kääntää.",
  "Note on mobile": "Huomautus matkapuhelimesta",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Sammuta tai muuta ”ei tapahtumia” -palkin tekstiä kalenterin mobiiliversiossa",
  Autodeletion: "Automaatti",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Vaihtoehdon ottaminen käyttöön poistaa menneisyyden tapahtumat automaattisesti kalenterista.",
  "This does not apply to repeating events!":
    "Tämä ei koske tapahtumien toistamista!",
  "Notify event creators about the guest": "Ilmoita käyttäjille vieraasta",
  "Send event creators notification emails as soon as guests register for their events":
    "Lähetä tapahtumantekijöille ilmoitussähköposteja heti, kun vieraat ilmoittautuvat tapahtumiinsa",
  "List View Type": "Listanäkymätyyppi",
  "Description font": "Kuvaus kirjasin",
  Connect: "Kytkeä",
  "You have no events": "Sinulla ei ole tapahtumia",
  Synchronize: "Synkronoida",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google -kalenterisynkronointi antaa sinun integroida tapahtumat ja istunnot puomikalenteriin.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook -kalenterisynkronointi antaa sinun integroida tapahtumat ja istunnot puomikalenteriin.",
  "Your message has been sent successfully!":
    "Viestisi on lähetetty onnistuneesti!",
  "There are no synchronized calendars": "Ei ole synkronoituja kalentereita",
  "to view more than 7 events": "nähdä yli 7 tapahtumaa",
  "Mobile app": "Mobiilisovellus",
  "Admin Account": "Järjestelmänvalvojatili",
  Password: "Salasana",
  "Second User": "Toinen käyttäjä",
  Edit: "Muokata",
  "Guest limit": "Vierasraja",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Kaikki paikalliset asetukset ovat (automaattisesti) kielen perusteella.Jos kielesi on luettelossa, tätä osaa ei tarvitse mukauttaa.",
  available: "saatavilla",
  next: "Seuraava",
  Tickets: "Liput",
  Quantity: "Määrä",
  "Promo code": "Tarjouskoodi",
  "Select a payment method": "Valitse maksutapa",
  Fee: "Maksu",
  Book: "Kirja",
  "All the tickets have been sold out": "Kaikki liput on loppuunmyyty",
  "Choose at least one ticket": "Valitse vähintään yksi lippu",
  "First choose ticket": "Valitse ensin lippu",
  "Please fill out your personal information.":
    "Täytä henkilökohtaiset tietosi.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Jos haluat tehdä onnistuneen ostoksen, valitsemalla ensisijainen maksutapa ja kirjoita promokoodi alennettuihin lippuihin.",
  "Credit/Debit card": "Luotto-/maksukortti",
  "print here.": "Tulosta täällä.",
  "QR code for all tickets": "QR -koodi kaikille lipuille",
  Duration: "Kesto",
  "Full Name": "Koko nimi",
  "Ticket id": "Lipputunnus",
  "Group id": "Ryhmätunnus",
  "Choose your ticket.": "Valitse lippu.",
  "Fill out your personal information.": "Täytä henkilökohtaiset tietosi.",
  "Add the payment details.": "Lisää maksutiedot.",
  "To be determined": "Olla päättäväinen",
  "You can find your e-tickets attached to the email or":
    "Löydät sähköpostille liitetyt sähköiset lippuja tai",
  "print here": "tulosta täällä",
  "Full name": "Koko nimi",
  "Group ID": "Ryhmätunnus",
  "to Book": "varata",
  "Unfortunately, your card has been declined":
    "Valitettavasti korttisi on hylätty",
  "Thank you for your purchase!": "Kiitos ostoksestasi!",
  "Find your printable e-tickets attached to the confirmation email":
    "Etsi tulostettavat e-lippujen liitetyt vahvistusviestiin",
  Confirm: "Vahvistaa",

  "Add event": "Lisää tapahtuma",
  Events: "Tapahtumat",
  "Event details": "Tapahtuman Yksityiskohdat",
  Registration: "Rekisteröinti",
  "Guests list": "Vieraat luettelo",
  Ticket: "Lippu",
  "General Info": "Yleiset tiedot",
  "Customize the general settings of your event":
    "Mukauta tapahtuman yleisiä asetuksia",
  "Event Title": "Tapahtuman otsikko",
  "e.g. Birthday Party": "esim. Syntymäpäiväjuhlat",
  "All Day Event": "Koko päivän tapahtuma",
  Cross: "Ylittää",
  Timeline: "Aikajana",
  "Repeating event": "Toistuva tapahtuma",
  Location: "Sijainti",
  "Venue name": "Tapahtumapaikan nimi",
  Description: "Kuvaus",
  Image: "Kuva",
  Color: "Väri",
  Category: "Kategoria",
  "Add your events to color categories and let your users classify them easily":
    "Lisää tapahtumasi väriluokkiin ja anna käyttäjien luokitella ne helposti",
  "Category name": "Kategorian nimi",
  "e.g. Birthdays": "esim. Syntymäpäivät",
  Venue: "Paikka",
  "Where the event takes place": "Missä tapahtuma tapahtuu",
  "Venue name": "Tapahtumapaikan nimi",
  "Venue phone": "Tapahtumapaikan puhelin",
  "Venue email": "Tapahtumapaikan sähköposti",
  "Venue website": "Tapahtumapaikan verkkosivusto",
  Organizer: "Järjestäjä",
  "Person who makes the event": "Henkilö, joka tekee tapahtuman",
  "Organizer name": "Järjestäjän nimi",
  "Organizer phone": "Järjestäjäpuhelin",
  "Organizer email": "Järjestäjän sähköposti",
  "Organizer website": "Järjestäjän verkkosivusto",
  Save: "Tallentaa",
  Cancel: "Peruuttaa",
  Import: "Tuonti",
  Past: "Menneisyys",
  All: "Kaikki",
  Upcoming: "Tuleva",
  Uncategorised: "Luokittelematon",
  "Date Ascending": "Päivämäärä nouseva",
  "Date Descending": "Laskevan päivämäärä",
  "Title by A-Z": "Otsikko A-Z",
  "Title by Z-A": "Otsikko Z-A",
  "There are no events for this period": "Tälle ajanjaksolle ei ole tapahtumia",

  "Auto-Convert Date & Time": "Automaattinen muunnospäivä ja aika",
  TimeZone: "Aikavyöhyke",
  Autodeletion: "Automaatti",
  "Layout Settings": "Asetteluasetukset",
  "Yeatly view": "Katsella",
  "Monthly view header": "Kuukausittainen näkymä otsikko",
  "Weekly/Daily view header": "Viikko-/päivittäinen näkymäotsikko",
  Acendings: "Acendings",
  Descending: "Laskeva",
  Standart: "Standardi",
  Silver: "Hopea",
  Retro: "Retro",
  Dark: "Tumma",
  Night: "Yö",
  Aubergine: "Munakoiso",
  "List view header": "Listanäkymäotsikko",
  "Side by Side View": "Vierekkäin näkymä",
  "Customize Proportions": "Mukauta mittasuhteita",
  "Card Margins": "Korttikate",
  "Image opacity (%)": "Kuvan opasiteetti (%)",
  "Side by Side Header": "Vierekkäin",
  "Text Align": "Teksti kohdistaa",
  "Timeline View": "Aikajanan näkymä",
  "Title font color": "Otsikkofonttiväri",
  "Desciption font color": "Desciption font -väri",
  "Line color": "Linjaväri",
  "Date Font color": "Päivämäärä fontin väri",
  "Daily events background": "Päivittäiset tapahtumat tausta",
  Alignment: "Linjaus",
  Vertical: "Pystysuora",
  Horizontal: "Vaakasuora",
  "Vertical Alignment": "Pystysuunta",
  Right: "Oikea",
  Center: "Keskusta",
  "Horizontal Alignment": "Vaakasuora kohdistaminen",
  Top: "Ylhäältä",
  Center: "Keskusta",
  Bottom: "Pohja",
  "Dates Circle Design": "Päivämäärien ympyrän suunnittelu",
  "Next To The Circle": "Ympyrän vieressä",
  "In The Circle": "Ympyrässä",
  "Timeline Header": "Aikajanan otsikko",
  Timeline: "Aikajana",
  "Show only upcoming": "Näytä vain tuleva",
  "Order by": "Tilata",
  "Timeline Event Limit": "Aikataulu",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Anna vierailijan lisätä tapahtumaa paikallisiin calnedarsiin: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Anna vierailijan jakaa tapahtumasi Facebookiin, LinkedIniin, Twitteriin ja jne.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Lisää kalenteriin hakuvaihtoehto, jotta ihmiset voivat etsiä tapahtumiasi otsikon, tapahtumapaikan, jne.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Anna käyttäjien tulostaa Boom -tapahtumakalenterisi millä tahansa ajanjaksolla.",
  "Click to apply a theme to Calendar":
    "Napsauta käyttääksesi teemaa kalenteriin",
  "Date container color": "Päiväyssäiliön väri",
  "Daily events background": "Päivittäiset tapahtumat tausta",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Asenna kalentereihisi edistyneiden ominaisuuksien lisäosat, mikä tekee niistä toiminnallisempia!",
  "Open Add-ons Store": "Avaa lisäosat",
  Monday: "maanantai",
  Tuesday: "tiistai",
  Wednesday: "keskiviikko",
  Thursday: "torstai",
  Friday: "perjantai",
  Saturday: "Lauantai",
  Sunday: "sunnuntai",
  "Yearly view": "Vuosittainen näkymä",
  Ascending: "Nouseva",
  "Show event time next to title": "Näytä tapahtuma -aika otsikon vieressä",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Säädä tapahtuman päivämäärä ja aika käyttäjän paikalliseen aikaan heidän aikavyöhykkeensä perusteella.",
  "Display the time zone alongside the event date.":
    "Näytä aikavyöhyke tapahtuman päivämäärän rinnalla.",
  "Show event time next to title": "Näytä tapahtuma -aika otsikon vieressä",
  "Time Zone": "Aikavyöhyke",
  "Upload Image": "Lataa kuva",
  "Choose a Category": "Valitse kategoria",
  "Color you have chosen will not be shown as you choose category":
    "Valitsemasi väriä ei näytetä, kun valitset luokan",
  Website: "Verkkosivusto",
  Next: "Seuraava",
  Save: "Tallentaa",
  "Last Name": "Sukunimi",
  "Personal Info": "Henkilökohtaiset tiedot",
  Back: "Takaisin",
  "This field is required": "Tämä kenttä pitää täyttää",
  "Your event has been submitted": "Tapahtumasi on lähetetty",
  "Enter a location": "Syötä sijainti",
  "Display the time zone alongside the event date.":
    "Näytä aikavyöhyke tapahtuman päivämäärän rinnalla.",
  Home: "Koti",
  "Side By Side Event Limit": "Vierekkäin tapahtumaraja",
  "Mobille App": "Mobille -sovellus",
  category: "kategoria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Pidä kirjaa aikataulustasi helposti tuomalla Facebook-tapahtumasi kalenteriisi.",
  "Synchronized Pages": "Synkronoidut sivut",
  "There are no synchronized pages": "Synkronoituja sivuja ei ole",
  "Choose page": "Valitse sivu",
  "You have no events": "Sinulla ei ole tapahtumia",
  "Add Script": "Lisää komentosarja",
  "script bound": "Tämä kirjoitus on jo sidottu, valitse muut tiedot!",
  "Choose account": "Valitse tili",
  "Choose resource": "Valitse resurssi",
  "Reconnect": "Yhdistää uudelleen",
  "script disappear": "Tätä käsikirjoitusta ei ole, lisää komentosarja Google Analyticsiin!",
  "Reset Layouts Dimensions": "Nollaa asettelu mitat",
  "Clear": "Selkeä",
  "Undo": "Kumota",
  "Redo": "Tehdä uudelleen",
  "Code Panel": "Koodipaneeli",
  "Code Panel Notify": "Koodin muokkaaminen voi rikkoa asettelu- tai sovellustoiminnot. Muokkaa vain, jos tiedät mitä teet!",
  "Clear Editor": "Selkeä toimittaja",
  "Clear Editor Notify": "Oletko varma, että haluat tyhjentää editorin? Kaikki edistyminen katoaa!",
  "Nothing to edit": "Mikään ei ole muokattava!",
  "Shapes": "Muodot",
  "Delete The Shape": "Poista muoto",
  "Add shapes": "Lisää muotoja asettelun välillä ja mukauta!",
  "Preview unavailable": "Komponenttien esikatselu ei ole käytettävissä komponentille",
  "component removed": "Komponentti, joka on poistettu editorista.",
  "component duplicate": "Komponentti lisätty, Huomaa: Kopioi merkintä!",
  "component added": "Komponentti lisätty toimittajaan onnistuneesti.",
  "Component Preview": "Komponenttien esikatselu",
  "Height": "Korkeus",
  "Font Family": "Fonttiperhe",
  "Select Font": "Valitse fontti",
  "Font Weight": "Fonttipaino",
  "Font Size": "Fontin koko",
  "Text Alignment": "Tekstin suuntaus",
  "Left Alignment": "Vasen kohdistus",
  "Center Alignment": "Keskikohde",
  "Right Alignment": "Oikea linjaus",
  "Text Decoration": "Tekstikoriste",
  "Overline": "Ylikuormitus",
  "Line Through": "Katkaista",
  "Underline": "Korostaa",
  "Underline and Overline": "Korostaa ja ylittää",
  "Without Decoration": "Koristelua",
  "Left": "Vasen",
  "Angle": "Kulma",
  "Distance": "Etäisyys",
  "Blur": "Sumeus",
  "Size": "Koko",
  "Edit individually": "Muokkaa erikseen",
  "Apply to all corners": "Levitä kaikkiin kulmiin",
  "Date Box Visual": "Päivämäärälaatikko visuaalinen",
  "One Line": "Yksi rivi",
  "Show Icons": "Näytä kuvakkeet",
  "Design Settings": "Suunnitteluasetukset",
  "Personalize your editor to match your style and preferences, customize every detail in this settings tab !": "Mukauta editoria vastaamaan tyyliäsi ja mieltymyksiäsi, mukauta kaikki yksityiskohdat tässä Asetukset -välilehdessä!",
  "Divider": "Jakaja",
  "Ellipse": "Ellipsi",
  "Rhombus": "Roomu",
  "Heart": "Sydän",
  "Hexagon": "Kuusikulmio",
  "Circle": "Ympyrä",
  "Rectangle": "Suorakulmio",
  "Square": "Neliö",
  "Triangle": "Kolmio",
  "Star": "Tähti",
};
export default fi;
