let lt = {
  "Custom Link": "Tinkinta nuoroda",
  "Link to event page": "Nuoroda į renginio puslapį",
  "No link": "Nėra nuorodos",
  "Attach File": "Pridėti failą",
  "To be announced": "Bus paskelbta",
  "Online": "Prisijungę",
  "Physical": "Fizinis",
  "Select Categories to display events related to them, or manually choose specific events under Events": "Pasirinkite Kategorijos, kad būtų rodomi su jomis susiję įvykiai, arba rankiniu būdu pasirinkite konkrečius įvykius dalyje Įvykiai",
  "Automatically approve events from these addresses": "Automatiškai patvirtinti įvykius iš šių adresų",
  "Approve events": "Patvirtinti įvykius",
  "Payable with a plan": "Mokama pagal planą",
  "Service Details": "Paslaugos informacija",
  "participants": "dalyvių",
  "To": "Į",
  "From": "Iš",
  "Ahead": "Pirmyn",
  "Ago": "Prieš",
  "Change the category": "Keisti kategoriją",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "„Ticket Tailor“ sinchronizavimas leidžia integruoti įvykius ir seansus su „Boom“ kalendoriumi.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Rodyti įvykio laiką šalia pavadinimo. Šis nustatymas taikomas tik mėnesio, dienos ir savaitės rodiniams.",
  "Show Staff Member": "Rodyti personalo narį",
  "Show Price": "Rodyti kainą",
  "To Event Page": "Į renginio puslapį",
  "Layout": "Išdėstymas",
  "Acending": "Didėjantis",
  "Yearly": "Kasmet",
  "Layout device": "Išdėstymo įrenginys",
  "Date container font": "Datos konteinerio šriftas",
  "Hide Fully Booked Slots": "Slėpti visiškai rezervuotus laiko tarpsnius",
  "Enable": "Įgalinti",
  "Limit": "Riba",
  "Export": "Eksportuoti",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Ketinate pakeisti išsamią įvykio informaciją. Kai pakeisite, jūsų svečių sąrašas bus prarastas.",
  "Change Date": "Keisti datą",
  "Ends": "Baigiasi",
  "On": "Įjungta",
  "After": "Po to",
  "Accept": "Priimti",
  "Show less": "Rodyti mažiau",
  "Venue detail": "Vietos detalė",
  "Reject": "Atmesti",
  "See guest list": "Žiūrėti svečių sąrašą",
  "Submit Date": "Pateikimo data",
  "Total guests": "Iš viso svečių",
  "Do you really want to delete selected user? Once removed, cannot be undone.": "Ar tikrai norite ištrinti pasirinktą naudotoją? Pašalinus, jo anuliuoti negalima.",
  "Delete Guest": "Ištrinti svečią",
  "Invoice number": "Sąskaitos numeris",
  "Status": "Būsena",
  "Payment type": "Mokėjimo tipas",
  "Select payment method to receive fees through tickets": "Pasirinkite mokėjimo būdą, kad gautumėte mokesčius už bilietus",
  "Payment Method": "Mokėjimo būdas",
  "Add Code": "Pridėti kodą",
  "Add End Time": "Pridėti pabaigos laiką",
  "Discount": "Nuolaida",
  "Promo codes for the sales": "Pardavimų reklamos kredito kodai",
  "Promo codes": "Reklamos kodai",
  "Add Ticket": "Pridėti bilietą",
  "Limit type": "Ribos tipas",
  "Paid": "Mokama",
  "Participation tickets for your event": "Dalyvavimo bilietai į Jūsų renginį",
  "Show the ticket limit": "Parodykite bilietų limitą",
  "Show limit": "Rodyti limitą",
  "Show the price on ticket": "Kainą parodykite ant bilieto",
  "Enable and configure your ticketing system": "Įgalinkite ir sukonfigūruokite bilietų pardavimo sistemą",
  "Stop repeating here": "Nustokite kartoti čia",
  "Limited": "Ribotas",
  "Unlimited": "Neribota",
  "Thank you message title": "Ačiū žinutės pavadinimas",
  "Submit button text": "Pateikti mygtuko tekstą",
  "Registration button text": "Registracijos mygtuko tekstas",
  "Texts": "Tekstai",
  "Modify the displayed texts": "Pakeiskite rodomus tekstus",
  "Thank you message body": "Padėkos pranešimo tekstas",
  "Notify the user when the registration is canceled": "Praneškite vartotojui, kai registracija atšaukiama",
  "Cancellation email": "Atšaukimo el",
  "Send a reminder to the user one day prior to the event": "Išsiųskite priminimą vartotojui vieną dieną prieš renginį",
  "Reminder email": "Priminimo el",
  "Send an instant email to the user once registration is completed": "Kai tik registracija bus baigta, išsiųskite vartotojui momentinį el. laišką",
  "Notification email": "Pranešimas el",
  "Reminder email about the event": "Priminimo el. laiškas apie įvykį",
  "Email notifications to users": "Pranešimai vartotojams el. paštu",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).": "Spustelėkite šalia kiekvieno lauko esančius perjungimo mygtukus, kad pridėtumėte jį prie registracijos formos. Jei norite, kad laukas būtų privalomas, spustelėkite žvaigždutę (*).",
  "Form Fields": "Formos laukai",
  "Enter your form description": "Įveskite formos aprašymą",
  "Form Title": "Formos pavadinimas",
  "Enter your form title": "Įveskite formos pavadinimą",
  "Form Details": "Išsami informacija apie formą",
  "Configure your registration form fields": "Sukonfigūruokite registracijos formos laukus",
  "Show guest limit": "Rodyti svečių limitą",
  "Enable Registration": "Įgalinti registraciją",
  "Click to activate registration on this event": "Spustelėkite norėdami suaktyvinti registraciją šiame renginyje",
  "Customize the general settings of registration": "Tinkinkite bendruosius registracijos nustatymus",
  "Enter URL": "Įveskite URL",
  "Page URL": "Puslapio URL",
  "Close registration when the event starts": "Uždaryti registraciją prasidėjus renginiui",
  "Redirect to a different website": "Peradresuoti į kitą svetainę",
  "Where users can register": "Kur vartotojai gali užsiregistruoti",
  "Open event registration landing page": "Atidarykite renginio registracijos nukreipimo puslapį",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.": "Turbūt reikėjo daug pasiruošti, kad pasiruoštumėte savo renginiui. Dabar pats laikas atsisėsti ir atsipalaiduoti, kol susirinks jūsų svečiai! Kai tik bus atlikta nauja registracija, čia bus rodoma informacija apie jūsų svečią. Grįžkite vėliau ir stebėkite savo renginio dalyvius.",
  "You have no guests at the moment.": "Šiuo metu neturite svečių.",
  "List of people who are registered to your event": "Žmonių, užsiregistravusių jūsų renginyje, sąrašas",
  "Guest List": "Svečių sąrašas",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.": "Tai pasikartojantis įvykis! Bet kokie šio įvykio pakeitimai bus taikomi visiems pasikartojimams.",
  "Repeated event": "Pakartotinis įvykis",
  "Delete Category": "Ištrinti kategoriją",
  "Do you really want to delete selected category? Once removed, cannot be undone.": "Ar tikrai norite ištrinti pasirinktą kategoriją? Pašalinus, jo anuliuoti negalima.",
  "OK": "Gerai",
  "Exclude": "Neįtraukti",
  "Custom recurrence": "Pasirinktinis pasikartojimas",
  "Duplicate": "Pasikartoti",
  "Delete": "Ištrinti",
  "Published": "Paskelbta",
  "Drafts": "Juodraščiai",
  "User events": "Vartotojo įvykiai",
  "Add new category": "Pridėti naują kategoriją",
  "Manage categories": "Tvarkyti kategorijas",
  "Add category": "Pridėti kategoriją",
  "Never": "Niekada",
  "Exclude": "Neįtraukti",
  "Repeat every": "Pakartokite kiekvieną",
  "Do you really want to delete selected event? Once removed, cannot be undone": "Ar tikrai norite ištrinti pasirinktą įvykį? Pašalinus, jo anuliuoti negalima",
  "There are no categories yet": "Kategorijų dar nėra",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.": "Atlikite sinchronizuoto kalendoriaus pakeitimus naudodami šias nuorodas. Atidžiai peržiūrėkite pakeitimus.",
  "occurrences": "įvykių",
  "Save as draft": "Išsaugoti kaip juodraštį",
  "More Info": "Daugiau informacijos",
  "Book Now": "Užsakyti dabar",
  "Show participants": "Šou dalyviai",
  "This service is fully booked.": "Ši paslauga yra visiškai rezervuota.",
  "All sessions are fully booked.": "Visos sesijos yra visiškai rezervuotos.",
  "Registration closed": "Registracija uždaryta",
  "Show your Wix Bookings or Events on Calendar": "Parodykite savo „Wix“ užsakymus ar renginius kalendoriuje",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.": "Pasirinkite automatinį visų paslaugų ir sesijų rodymą kalendoriuje arba rankiniu būdu rankiniam pasirinkimui.",
  "Show cancelled events": "Rodyti atšauktus įvykius",
  "Event Color": "Įvykio spalva",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.": "Pasirinkite „Auto“ automatiškai rodyti visus kalendoriaus įvykius arba rankinį rankiniu būdu.",
  "Auto": "Automatinis",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.": "Pasirinkite automatinį visų organizacijų ir organizatorių rodymą kalendoriuje arba rankiniu būdu.",
  "Manual": "Vadovas",
  "Sync method": "Sinchronizavimo metodas",
  "Enable synchronization": "Įgalinti sinchronizaciją",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only": "Parodykite kategorijos filtrą viršuje arba kalendoriaus apačioje. Nustatymai taikomi tik darbotvarkės, kryžminio, laiko juostos ir kortelių peržiūrai",
  "Load Events": "Įkelti įvykius",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.": "Įjungus jūsų kalendoriaus valdiklis bus išverstas pagal svetainės kalbą. Atminkite, kad kol kalendoriaus pavadinimai ir aprašymai įvedami kaip tekstas, jų negalima išversti.",
  "Choose plan type": "Pasirinkite plano tipą",
  "Api key": "API raktas",
  "Synchronized Boxes": "Sinchronizuotos dėžutės",
  "Choose box": "Pasirinkite langelį",
  "There are no synchronized boxes": "Nėra sinchronizuotų dėžučių",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "„Ticket Siulor Sync“ leidžia integruoti renginius ir sesijas su „Boom“ kalendoriumi",
  Categories: "Kategorijos",
  "Share this event": "Pasidalykite šiuo įvykiu",
  Language: "Kalba",
  "Show Time Zone": "Rodyti laiko juostą",
  "Custom Local Settings": "Individualūs vietiniai nustatymai",
  "Add and showcase events on your site using a beautiful calendar.":
    "Pridėkite ir demonstruokite įvykius savo svetainėje naudodami gražų kalendorių.",
  "Week Days": "Darbo dienomis",
  "Manage Events": "Tvarkykite įvykius",
  General: "Bendrasis",
  "Layout Picker": "Išdėstymo rinkėjas",
  Month: "Mėnuo",
  Monthly: "Mėnesinis",
  Week: "Savaitė",
  Weekly: "Savaitraštis",
  Day: "Diena",
  Daily: "Kasdien",
  Agenda: "Darbotvarkė",
  "Navigation Buttons": "Navigacijos mygtukai",
  "Week numbers": "Savaitės numeriai",
  "Include Weekends": "Įtraukite savaitgalius",
  "All-day": "Visą dieną",
  "All Day": "Visą dieną",
  Label: "Etiketė",
  "Fit to Height": "Tinka į aukštį",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Norėdami nustatyti programos proporcijas rankiniu būdu išjungti šią parinktį ir pakeisti kalendorių redaktoriuje.",
  "Default Layout": "Numatytasis išdėstymas",
  "Monthly view": "Mėnesio vaizdas",
  "Weekly and Daily view": "Savaitės ir dienos vaizdas",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Lankytojams galite suteikti nuoseklesnę patirtį parodydami tą patį savaičių skaičių (6) vienu metu.",
  "Fixed Weekly Layout": "Fiksuotas savaitinis išdėstymas",
  back: "atgal",
  Row: "Eilė",
  "Hours in Weekly View": "Valandos savaitės vaizde",
  "Hours in Daily View": "Valandos kasdienis vaizdas",
  Start: "Pradėti",
  End: "Galas",
  "At This Hour": "Šią valandą",
  Button: "Mygtukas",
  Buttons: "Mygtukai",
  Sunday: "Sekmadienis",
  Monday: "Pirmadienis",
  Tuesday: "Antradienis",
  Wednesday: "Trečiadienis",
  Thursday: "Ketvirtadienis",
  Friday: "Penktadienis",
  Saturday: "Šeštadienis",
  "Default Date": "Numatytoji data",
  year: "metai",
  month: "mėnuo",
  days: "dienos",
  ago: "prieš",
  ahead: "priekyje",
  Yesterday: "Vakar",
  Today: "Šiandien",
  Tomorrow: "Rytoj",
  Custom: "Paprotys",
  "Set Daily Rows Limit": "Nustatykite dienos eilučių ribą",
  "Set Proportions": "Nustatytos proporcijos",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Leiskite lankytojui pridėti įvykių į vietinius „Caledars“: „Google“, „Yahoo“, „Outlook“, „Icalendar“.",
  Container: "Konteineris",
  Background: "Fonas",
  "Container Background": "Konteinerio fonas",
  "Container Borders": "Konteinerių sienos",
  Calendar: "Kalendorius",
  "Event Info Tooltip": "Įvykio informacijos patarimas",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Kai žmonės svyruoja per renginį, jie pamatys visą informaciją apie tai patarime.",
  "Event Info Window": "Informacijos apie įvykį langas",
  "This is the full information window that opens when someone clicks on the event.":
    "Tai yra visas informacijos langas, kuris atsidaro, kai kas nors spustelėja įvykį.",
  "Use Gradient": "Naudokite gradientą",
  Vertical: "Vertikali",
  Horizontal: "Horizontalus",
  First: "Pirmas",
  Second: "Antra",
  diagonal: "įstrižainė",
  Radial: "Radialinis",
  "Select option": "Pasirinkite Parinktį",
  Solid: "Kietas",
  Dotted: "Punktyvas",
  Dashed: "Punktyvas",
  Double: "Dvigubai",
  "Border Radius": "Pasienio spindulys",
  Padding: "Paminkštinimas",
  "Date Header": "Datos antraštė",
  "Event Default Color": "Įvykio numatytoji spalva",
  "Days of Week": "Savaitės dienos",
  "Days of Week Background": "Savaitės dienos fonas",
  Date: "Data",
  "Event Title": "Įvykio pavadinimas",
  "Highlight today": "Pabrėžkite šiandien",
  "Highlight Color": "Paryškinkite spalvą",
  Hide: "Paslėpti",
  "Calendar Border Color": "Kalendoriaus krašto spalva",
  "Calendar Border Width": "Kalendoriaus sienos plotis",
  "Calendar Border Style": "Kalendoriaus pasienio stilius",
  "Font Color": "Šrifto spalva",
  "Event Background": "Įvykio fonas",
  "Card Date Color": "Kortelės datos spalva",
  "Title Font": "Pavadinimo šriftas",
  "Date Font": "Datos šriftas",
  "Description Font": "Aprašymo šriftas",
  "Button Background": "Mygtuko fonas",
  "Button Text": "Mygtuko tekstas",
  "Border Color": "Pasienio spalva",
  "Border Width": "Sienos plotis",
  "Border Type": "Pasienio tipas",
  Title: "Pavadinimas",
  Description: "apibūdinimas",
  "Background Color": "Fono spalva",
  Divider: "Daliklis",
  "Event Details Font": "Informacija apie įvykį šriftas",
  "Website Link Color": "Svetainės nuorodos spalva",
  "Developer Info": "Kūrėjo informacija",
  "User Guide": "Naudotojo gidas",
  "Support e-mail": "Palaikykite el. Paštą",
  "Our Website": "Mūsų svetainė",
  "App Review": "Programos apžvalga",
  "Enjoying App? Leave us a review in the App Market.":
    "Mėgaukitės programa?Palikite mums apžvalgą programų rinkoje.",
  "Review Us": "Peržiūrėkite mus",
  "Connect With Us": "Susisiekti su mumis",
  "What's your email?": "Koks tavo elektroninis paštas?",
  "Invalid email address!": "Neteisingas el. pašto adresas!",
  Comments: "Komentarai",
  "We'd love to hear from you. Send us a message.":
    "Mes norėtume išgirsti iš jūsų.Atsiųskite mums pranešimą.",
  "Message must be at least 5 characters long":
    "Pranešimas turi būti bent 5 simbolių ilgio",
  Send: "Siųsti",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jei norite leisti vartotojui perjungti kalendoriaus rodinius, įgalinti šią parinktį ir pasirinkti rodinius, kuriuos norite parodyti.",
  Main: "Pagrindinis",
  Localize: "Lokalizuoti",
  Settings: "Nustatymai",
  Layouts: "Išdėstymas",
  Advanced: "Pažengęs",
  Design: "Dizainas",
  Support: "Palaikymas",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Visi vietiniai nustatymai yra (automatiškai), atsižvelgiant į jūsų kalbą.Jei jūsų kalba yra sąraše, nereikia tinkinti šio skyriaus.",
  "Date Format": "Datos formatas",
  "Time Format": "Laiko formatas",
  "Text Direction": "Teksto kryptis",
  "Left to Right": "Iš kairės į dešinę",
  "Right to Left": "Iš dešinės į kairę",
  "Week Starts On": "Savaitė prasideda",
  "Agenda Style": "Darbotvarkės stilius",
  Classic: "Klasikinis",
  Modern: "Modernus",
  "Agenda Header": "Darbotvarkės antraštė",
  "Upcoming Events": "Artimiausi renginiai",
  "Agenda Event Limit": "Darbotvarkės įvykių riba",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Atnaujinkite dabar ir gaukite daug daugiau funkcijų ir mėgaukitės visa savo programa!",
  "Upgrade Now": "Patobulinti dabar",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Renginių, kurie trunka visą dieną, rengimas?Tai leidžia juos parodyti savo kalendoriuje.",
  "24 hours": "24 valandos",
  Sat: "SAT",
  Sun: "Saulė",
  Mon: "Pirmadienis",
  Default: "Numatytas",
  "Select custom design style for your calendar.":
    "Savo kalendoriui pasirinkite pasirinktinį dizaino stilių.",
  Style: "Stilius",
  "Styles and Colors": "Stiliai ir spalvos",
  "Calendar Name": "Kalendoriaus pavadinimas",
  "Write your Calendar name here": "Parašykite savo kalendoriaus vardą čia",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Tai nematyti jūsų vartotojams.Nustatykite pavadinimus, kad diferencijuotumėte savo kalendorius, kai naudojate „Boom Calendar Sync“ funkciją.",
  "General Info": "Bendroji informacija",
  Venue: "Vieta",
  Organizer: "Organizatorius",
  Search: "Paieška",
  "Add to": "Pridėti prie",
  calendar: "kalendorius",
  "Copy event URL": "Kopijuoti įvykio URL",
  "Copied!": "Nukopijuota!",
  "Add & Share": "Pridėti ir bendrinti",
  Map: "Žemėlapis",
  "Calendar view": "Kalendoriaus vaizdas",
  "Add Event": "Pridėti įvykį",
  Uncategorised: "Nekategorizuotas",
  More: "Daugiau",
  Less: "Mažiau",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Leiskite mokiniams bendrinti jūsų įvykį Facebook, Linkedin, Twitter ir kt.",
  Register: "Registruotis",
  Card: "Kortelė",
  "There are no events": "Nėra įvykių",
  Guests: "Svečiai",
  "show event time": "rodyti renginio laiką",
  unlimited: "neribotas",
  "Order by": "Rūšiuoti pagal",
  "Show more": "Rodyti daugiau",
  "Enable Search": "Įgalinti paiešką",
  "+ Add Event": "+ Pridėti įvykį",
  "Manage and Sync": "Tvarkyti ir sinchronizuoti",
  "Show event details as...": "Rodyti renginio detales kaip ...",
  Tooltip: "Patarimas",
  Popup: "POPUP",
  None: "Nė vienas",
  "Search for events": "Ieškokite įvykių",
  "Show Category": "Parodyti kategoriją",
  "Header Align": "Antraštė",
  "Show Time": "Pasirodymas",
  "Hours in Weekly/Daily View": "Valandos per savaitę/dienos vaizdas",
  "Share Events": "Dalykitės įvykiais",
  Shadow: "Šešėlis",
  "Inner Padding": "Vidinis paminkštinimas",
  Text: "Tekstas",
  "Active Button Border": "Aktyvus mygtuko kraštas",
  "Light Mode": "Šviesos režimas",
  "Event Text Color": "Įvykio teksto spalva",
  Dates: "Datos",
  Skeleton: "Skeletas",
  "Skeleton Color": "Skeleto spalva",
  Width: "Plotis",
  "Skeleton Style": "Skeleto stilius",
  Color: "Spalva",
  "Section Titles": "Skyrių pavadinimai",
  "Section Content": "Skyriaus turinys",
  Header: "Antraštė",
  Standard: "Standartas",
  Retro: "Retro",
  Silver: "sidabras",
  Night: "Naktis",
  Dark: "Tamsi",
  Aubergine: "Baklažanas",
  "Map Header": "Žemėlapio antraštė",
  "Show Title in mobile": "Rodyti pavadinimą mobiliajame telefone",
  "Card View": "Vaizdas kortelėje",
  "Card background color": "Kortelės fono spalva",
  "Title font": "Pavadinimo šriftas",
  "Desciption font": "„Desciption“ šriftas",
  "Section font": "Skyriaus šriftas",
  "Section divider color": "Skyriaus daliklio spalva",
  "Add event": "Pridėti įvykį",
  "All Day Event": "Visos dienos renginys",
  Location: "Vieta",
  "Choose a category": "Pasirinkite kategoriją",
  "Venue name": "Vietos pavadinimas",
  "Venue phone": "Vietos telefonas",
  "Venue email": "Vietos el. Paštas",
  "Venue website": "Vietos svetainė",
  "Organizer name": "Organizatoriaus vardas",
  "Organizer phone": "Organizatoriaus telefonas",
  "Organizer email": "Organizatoriaus el. Paštas",
  "Organizer website": "Organizatorių svetainė",
  "Personal info": "Asmeninė informacija",
  "First name": "Pirmas vardas",
  "Last name": "Pavardė",
  "Email Address": "Elektroninio pašto adresas",
  "Additional Notes": "papildomi užrašai",
  Back: "Atgal",
  Save: "Sutaupyti",
  Next: "Kitas",
  "Your event has been submitted": "Jūsų renginys buvo pateiktas",
  "Event submittion has been failed": "Įvykio pateikimas nepavyko",
  "e.g. Birthday Party": "pvz.Gimtadienio vakarėlis",
  "First Name": "Pirmas vardas",
  "Last Name": "Pavardė",
  "Phone Number": "Telefono numeris",
  Address: "Adresas",
  "Your comments": "Tavo komentarai",
  "How many guests?": "Kiek svečių?",
  "Anything else we need to know?": "Dar ką nors turime žinoti?",
  "Guests:": "Svečiai:",
  Submit: "Pateikti",
  "Go to Calendar": "Eikite į kalendorių",
  "Registration completed successfully!": "Registracija sėkmingai baigta!",
  "Please check your registered email address":
    "Patikrinkite registruotą el. Pašto adresą",
  "Add to Calendar": "Pridėti prie kalendoriaus",
  "Share this Event": "Pasidalykite šiuo įvykiu",
  "Sorry something went wrong": "Gaila, kad kažkas nutiko ne taip",
  "Back to registration": "Grįžti į registraciją",
  "Date & Location": "Data ir vieta",
  "Date & Time": "Data ir laikas",
  home: "namai",
  "Header align": "Antraštė",
  Footer: "Poraštė",
  "Categories Filter": "Kategorijų filtras",
  "Show only upcoming": "Parodykite tik būsimą",
  "Card(s) in a row": "Kortelė (-os) iš eilės",
  "Space between cards": "Tarpas tarp kortelių",
  "Shown events limit": "Parodyta įvykių riba",
  "Style 1": "1 stilius",
  "Style 2": "2 stilius",
  "Style 3": "3 stilius",
  "Style 4": "4 stilius",
  "Buttons & Links": "Mygtukai ir nuorodos",
  "Button corner radius": "Mygtuko kampo spindulys",
  "Buttons font": "Mygtukų šriftas",
  "Buttons background": "Mygtukų fonas",
  "Get notified by Email": "Gaukite pranešimą el. Paštu",
  "Review events": "Peržiūrėkite įvykius",
  "Click on date": "Spustelėkite datą",
  "Add Event button": "Pridėti įvykio mygtuką",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "„Calendar Sync“ leidžia integruoti įvykius ir sesijas su „Boom“ kalendoriumi.",
  connect: "Prisijungti",
  "Synchronized Calendars": "Sinchronizuoti kalendoriai",
  "Import events": "Importuoti įvykius",
  Disconnect: "Atjungti",
  "Choose calendar": "Pasirinkite kalendorių",
  "Monitor your Wix events through the sync feature":
    "Stebėkite savo „Wix“ įvykius naudodamiesi sinchronizavimo funkcija",
  "Connect all your Boom calendars available on your website":
    "Prijunkite visus savo „Boom“ kalendorius, kuriuos galite rasti savo svetainėje",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Suplanuokite, prisijunkite ir tvarkykite mastelio keitimo susitikimus tiesiai per mūsų „Boom“ kalendorių.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Stebėkite savo „Eventbrite“ įvykius naudodamiesi „Eventbrite Sync“ funkcija",
  Email: "El. Paštas",
  "Add-ons": "Priedai",
  "Receive notification emails as soon as users add events to your calendar.":
    "Gaukite pranešimų el. Laiškus, kai tik vartotojai prideda įvykių prie jūsų kalendoriaus.",
  "Enable + button on the calendar header":
    "Įgalinti + mygtuką kalendoriaus antraštėje",
  "Accept or decline events added by customers before making them public.":
    "Prieš paskelbdami juos viešai, priimkite ar atsisakykite įvykių.",
  "Switch Add Event": "Jungiklio pridėjimo įvykis",
  "Enable your browser cookies to connect to your account.":
    "Įgalinkite naršyklės slapukus prisijungti prie jūsų paskyros.",
  "Learn more": "Sužinokite daugiau",
  "Print Button": "Spausdinti mygtuką",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Leiskite vartotojams atsispausdinti „Boom“ įvykių kalendorių bet kuriame datos diapazone.",
  "Show Title on mobile": "Rodyti pavadinimą mobiliajame telefone",
  "Show Skeleton on mobile": "Rodyti skeletą mobiliajame telefone",
  "Start 7-day Business trial": "Pradėkite 7 dienų verslo bandymą",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Mėgaukitės visomis neribotomis funkcijomis, tokiomis kaip parduoti bilietus, registraciją, lankytojų renginių priedus.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Atkreipkite dėmesį: bandymo laikotarpio pabaigoje būsite grąžinti į esamą prenumeratos planą.",
  "Not Now": "Ne dabar",
  "Start free trial": "Pradėkite nemokamą bandymą",
  "Congrats!": "Sveikinimai!",
  "Your 7-day Business trial has been successfully activated.":
    "Jūsų 7 dienų verslo bandymas buvo sėkmingai suaktyvintas.",
  Done: "padaryta",
  "Title font color": "Pavadinimo šrifto spalva",
  "Desciption font color": "„Desciption“ šrifto spalva",
  "Section font color": "Skyriaus šrifto spalva",
  "Card Header": "Kortelės antraštė",
  Category: "Kategorija",
  "Display at the": "Rodyti",
  top: "viršus",
  bottom: "apačia",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Parodykite kategorijos filtrą viršuje arba kalendoriaus apačioje.Nustatymai taikomi tik darbotvarkės ir kortelių rodiniams",
  Autotranslation: "Autotransliacija",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Įjungus jūsų kalendoriaus valdiklis bus išverstas pagal svetainės kalbą.*Atminkite, kad tol, kol kalendoriaus pavadinimas ir aprašymai yra įvesti tekstai, jie negali būti išversti.",
  "Note on mobile": "Pastaba mobiliajame telefone",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Išjunkite arba pakeiskite juostos „No įvykių“ tekstą mobiliojoje „Calendar“ versijoje",
  "As soon as event ends": "Kai tik baigsis įvykis",
  "1 day after event ends": "1 diena po įvykio pabaigos",
  "7 days after event ends": "7 dienos po įvykio pabaigos",
  "14 days after event ends": "14 dienų po įvykio pabaigos",
  "30 days after event ends": "30 dienų po įvykio pabaigos",
  Autodeletion: "Autodelecija",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Įgalinus parinktį, automatiškai pašalinsite savo praeities įvykius iš kalendoriaus.",
  "This does not apply to repeating events!":
    "Tai netaikoma pakartotiniams įvykiams!",
  "Notify event creators about the guest":
    "Praneškite renginių kūrėjams apie svečią",
  "Send event creators notification emails as soon as guests register for their events":
    "Siųskite renginių kūrėjų pranešimų el. Laiškus, kai tik svečiai užsiregistruos į savo renginius",
  view: "vaizdas",
  List: "Sąrašas",
  "List View Type": "Sąrašo rodinio tipas",
  Year: "Metai",
  Cash: "Grynieji pinigai",
  "Credit/Debit card": "Kredito / debeto kortelė",
  Total: "Iš viso",
  "Total:": "Iš viso:",
  Confirm: "Patvirtinti",
  "You can find your e-tickets attached to the email or":
    "Savo elektroninius bilietus galite rasti prie el. laiško arba",
  "Full name": "Pilnas vardas",
  Data: "Duomenys",
  "Data:": "Duomenys:",
  Duration: "Trukmė",
  "print here.": "spausdinti čia.",
  "Group ID": "Grupės ID",
  available: "prieinama",
  "Fill out your personal information.":
    "Užpildykite savo asmeninę informaciją.",
  "Add the payment details.": "Pridėkite mokėjimo informaciją.",
  "Choose your ticket.": "Pasirinkite savo bilietą.",

  "Add event": "Pridėkite įvykį",
  Events: "Įvykiai",
  "Event details": "Informacija apie įvykį",
  Registration: "Registracija",
  "Guests list": "Svečių sąrašas",
  Ticket: "Bilietas",
  "General Info": "Bendroji informacija",
  "Customize the general settings of your event":
    "Tinkinkite bendrus savo įvykio nustatymus",
  "Event Title": "Įvykio pavadinimas",
  "e.g. Birthday Party": "pvz. Gimtadienio vakarėlis",
  "All Day Event": "Visos dienos renginys",
  Cross: "Kirsti",
  Timeline: "Laiko juosta",
  "Repeating event": "Kartojantis įvykis",
  Location: "Vieta",
  "Venue name": "Vietos pavadinimas",
  Description: "apibūdinimas",
  Image: "Vaizdas",
  Color: "Spalva",
  Category: "Kategorija",
  "Add your events to color categories and let your users classify them easily":
    "Pridėkite savo įvykius į spalvų kategorijas ir leiskite vartotojams lengvai juos klasifikuoti",
  "Category name": "Kategorijos pavadinimas",
  "e.g. Birthdays": "pvz. Gimtadieniai",
  Venue: "Vieta",
  "Where the event takes place": "Kur vyksta renginys",
  "Venue name": "Vietos pavadinimas",
  "Venue phone": "Vietos telefonas",
  "Venue email": "Vietos el. Paštas",
  "Venue website": "Vietos svetainė",
  Organizer: "Organizatorius",
  "Person who makes the event": "Asmuo, kuris rengia renginį",
  "Organizer name": "Organizatoriaus vardas",
  "Organizer phone": "Organizatoriaus telefonas",
  "Organizer email": "Organizatoriaus el. Paštas",
  "Organizer website": "Organizatorių svetainė",
  Save: "Sutaupyti",
  Cancel: "Atšaukti",
  Import: "Importuoti",
  Past: "Praeitis",
  All: "Viskas",
  Upcoming: "Būsimas",
  Uncategorised: "Nekategorizuotas",
  "Date Ascending": "Data kylanti",
  "Date Descending": "Data mažėja",
  "Title by A-Z": "A-Z pavadinimas",
  "Title by Z-A": "Pavadinimas pagal Z-A.",
  "There are no events for this period": "Nėra šio laikotarpio įvykių",

  "Auto-Convert Date & Time": "Automatinis konvertavimo data ir laikas",
  TimeZone: "Laiko zona",
  Autodeletion: "Autodelecija",
  "Layout Settings": "Išdėstymo nustatymai",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Mėnesio rodinio antraštė",
  "Weekly/Daily view header": "Savaitės/„Daily View“ antraštė",
  Acendings: "Kendencijos",
  Descending: "Mažėjantis",
  Standart: "Standartas",
  Silver: "sidabras",
  Retro: "Retro",
  Dark: "Tamsu",
  Night: "Naktis",
  Aubergine: "Baklažanas",
  "List view header": "Sąrašo rodinio antraštė",
  "Side by Side View": "Vaizdas vienas šalia kito",
  "Customize Proportions": "Tinkinti proporcijas",
  "Card Margins": "Kortelių paraštės",
  "Image opacity (%)": "Vaizdo neskaidrumas (%)",
  "Side by Side Header": "Šoninis antraštė",
  "Text Align": "Teksto lygiavertis",
  "Timeline View": "Laiko juostos vaizdas",
  "Title font color": "Pavadinimo šrifto spalva",
  "Desciption font color": "„Desciption“ šrifto spalva",
  "Line color": "Linijos spalva",
  "Date Font color": "Datos šrifto spalva",
  "Daily events background": "Kasdieniniai įvykių fonas",
  Alignment: "Suderinimas",
  Vertical: "Vertikali",
  Horizontal: "Horizontalus",
  "Vertical Alignment": "Vertikalus išlyginimas",
  Right: "Teisingai",
  Center: "Centras",
  "Horizontal Alignment": "Horizontalus derinimas",
  Top: "Viršus",
  Center: "Centras",
  Bottom: "Apačia",
  "Dates Circle Design": "Datos apskritimo dizainas",
  "Next To The Circle": "Šalia apskritimo",
  "In The Circle": "Ratu",
  "Timeline Header": "Laiko juostos antraštė",
  Timeline: "Laiko juosta",
  "Show only upcoming": "Parodykite tik būsimą",
  "Order by": "Rūšiuoti pagal",
  "Timeline Event Limit": "Laiko linijos įvykių riba",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Leiskite lankytojui pridėti įvykius vietiniams „Caledars“: „Google“, „Yahoo“, „Outlook“, „Icalendar“.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Leiskite lankytojui pasidalyti savo renginiu į „Facebook“, „LinkedIn“, „Twitter“ ir kt.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Pridėkite savo kalendoriaus paieškos parinktį, kad žmonės leistų žmonėms ieškoti jūsų įvykių pagal pavadinimą, vietą ir kt.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Leiskite vartotojams atsispausdinti „Boom“ įvykių kalendorių bet kuriame datos diapazone.",
  "Click to apply a theme to Calendar":
    "Spustelėkite, jei norite pritaikyti temą kalendoriui",
  "Date container color": "Datos konteinerio spalva",
  "Daily events background": "Kasdieniniai įvykių fonas",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Norėdami įdiegti išplėstines funkcijas savo kalendoriuose, naudokite priedus, kad jos būtų funkcionalesnės!",
  "Open Add-ons Store": "Atidarykite priedų parduotuvę",
  Monday: "Pirmadienis",
  Tuesday: "Antradienis",
  Wednesday: "Trečiadienis",
  Thursday: "Ketvirtadienis",
  Friday: "Penktadienis",
  Saturday: "Šeštadienis",
  Sunday: "Sekmadienis",
  "Show event time next to title": "Rodyti įvykio laiką šalia pavadinimo",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Remdamiesi jų laiko juosta, sureguliuokite įvykio datą ir laiką pagal vartotojo vietos laiką.",
  "Display the time zone alongside the event date.":
    "Parodykite laiko juostą kartu su įvykio data.",
  "Show event time next to title": "Rodyti įvykio laiką šalia pavadinimo",
  "Time Zone": "Laiko zona",
  "Upload Image": "Įkelti paveikslėlį",
  "Choose a Category": "Pasirinkite kategoriją",
  "Color you have chosen will not be shown as you choose category":
    "Pasirinkta spalva nebus rodoma, kai pasirenkate kategoriją",
  Website: "Interneto svetainė",
  Next: "Kitas",
  Save: "Sutaupyti",
  "Last Name": "Pavardė",
  "Personal Info": "Asmeninė informacija",
  Back: "Atgal",
  "This field is required": "Šį lauką būtina užpildyti",
  "Your event has been submitted": "Jūsų renginys buvo pateiktas",
  "Enter a location": "Įveskite vietą",
  "Display the time zone alongside the event date.":
    "Parodykite laiko juostą kartu su įvykio data.",
  Home: "Namai",
  "Side By Side Event Limit": "Viršutinio įvykio riba",
  "Mobille App": "„Mobille“ programa",
  category: "Kategorija",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Lengvai stebėkite savo tvarkaraštį importuodami „Facebook“ įvykius į kalendorių.",
  "Synchronized Pages": "Sinchronizuoti puslapiai",
  "There are no synchronized pages": "Sinchronizuotų puslapių nėra",
  "Choose page": "Pasirinkite puslapį",
  "You have no events": "Jūs neturite įvykių",
  "Add Script": "Pridėti scenarijų",
  "script bound": "Šis scenarijus jau yra surištas, pasirinkite kitą informaciją!",
  "Choose account": "Pasirinkite sąskaitą",
  "Choose resource": "Pasirinkite šaltinį",
  "Reconnect": "Vėl prisijungti",
  "script disappear": "Šis scenarijus neegzistuoja, pridėkite scenarijų į savo „Google Analytics“!",
  "Reset Layouts Dimensions": "Atstatymo išdėstymo matmenys",
  "Clear": "Aišku",
  "Undo": "Anuliuoti",
  "Redo": "Perdaryti",
  "Code Panel": "Kodo skydelis",
  "Code Panel Notify": "Kodo modifikavimas tiesiogiai gali nutraukti išdėstymo ar programos funkcionalumą. Redaguokite tik tuo atveju, jei žinote, ką darote!",
  "Clear Editor": "Aiškus redaktorius",
  "Clear Editor Notify": "Ar tikrai norite išvalyti redaktorių? Visa pažanga bus prarasta!",
  "Nothing to edit": "Nėra ko redaguoti!",
  "Shapes": "Formos",
  "Delete The Shape": "Ištrinkite formą",
  "Add shapes": "Pridėkite figūras tarp išdėstymo ir tinkinti!",
  "Preview unavailable": "Komponentų peržiūra neprieinama komponentui",
  "component removed": "Komponentas pašalintas iš redaktoriaus.",
  "component duplicate": "Pridedama komponentas, pastaba: įrašas kopijuoja!",
  "component added": "Komponentas sėkmingai pridėtas prie redaktoriaus.",
  "Component Preview": "Komponentų peržiūra",
  "Height": "Ūgis",
  "Font Family": "Šriftų šeima",
  "Select Font": "Pasirinkite šriftą",
  "Font Weight": "Šrifto svoris",
  "Font Size": "Šrifto dydis",
  "Text Alignment": "Teksto derinimas",
  "Left Alignment": "Kairysis derinimas",
  "Center Alignment": "Centrinis derinimas",
  "Right Alignment": "Teisingas derinimas",
  "Text Decoration": "Teksto dekoravimas",
  "Overline": "Pernelyg linija",
  "Line Through": "Linija",
  "Underline": "Pabraukite",
  "Underline and Overline": "Pabraukite ir per daug",
  "Without Decoration": "Be dekoravimo",
  "Left": "Kairėje",
  "Angle": "Kampas",
  "Distance": "Atstumas",
  "Blur": "Suliejimas",
  "Size": "Dydis",
  "Edit individually": "Redaguoti atskirai",
  "Apply to all corners": "Kreipkitės į visus kampus",
  "Date Box Visual": "Datos dėžutė Vaizdinė",
  "One Line": "Viena eilutė",
  "Show Icons": "Rodyti piktogramas",
  "Design Settings": "Dizaino nustatymai",
  "Personalize your editor to match your style and preferences, customize every detail in this settings tab !": "Suasmeninkite savo redaktorių, kad atitiktumėte savo stilių ir nuostatas, pritaikykite kiekvieną išsamią informaciją šiame nustatymų skirtuke!",
  "Divider": "Daliklis",
  "Ellipse": "Elipsė",
  "Rhombus": "Rombas",
  "Heart": "Širdis",
  "Hexagon": "Šešiakampis",
  "Circle": "Ratas",
  "Rectangle": "Stačiakampis",
  "Square": "Kvadratas",
  "Triangle": "Trikampis",
  "Star": "Žvaigždė",
};
export default lt;
