let lt = {
  Language: "Kalba",
  "Show Time Zone": "Rodyti laiko juostą",
  "Custom Local Settings": "Pasirinktiniai vietiniai nustatymai",
  "Add and showcase events on your site using a beautiful calendar.":
    "Sukurkite ir pridėkite įvykius savo svetainėje naudodami gražų kalendorių",
  "Week Days": "Savaitės Dienos",
  "Manage Events": "Tvarkyti įvykius",
  General: "Bendrosios nuostatos",
  "Layout Picker": "Maketo parinkimas",
  Month: "Męnuo",
  Monthly: "Mėnesinis",
  Week: "Savaitė",
  Weekly: "Savaitinis",
  Day: "Diena",
  Daily: "Kasdienis",
  Agenda: "Darbotvarkė",
  "Navigation Buttons": "Naršymo mygtukai",
  "Week numbers": "Savaičių skaičius",
  "Include Weekends": "Įtraukti savaitgalius",
  "All-day": "Visos dienos",
  "All Day": "Visą dieną",
  Label: "Etiketė",
  "Fit to Height": "Pritaikyti prie aukščio",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Jei norite rankiniu būdu nustatyti programėlės proporcijas, išjunkite šią parinktį ir pakeiskite Kalendoriaus dydį Redaktoriuje.",
  "Default Layout": "Numatytasis išdėstymas",
  "Monthly view": "Mėnesio vaizdas",
  "Weekly and Daily view": "Savaitės ir dienos vaizdas",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Galite suteikti lankytojams geresnę patirtį rodydami tą patį savaičių skaičių vienu metu.",
  "Fixed Weekly Layout": "Fiksuotas savaitės išdėstymas",
  back: "atgal",
  Row: "Eilutė",
  "Hours in Weekly View": "Valandos savaitės rodinyje",
  "Hours in Daily View": "Valandos dienos rodinyje",
  Start: "Pradžia",
  End: "Pabaiga",
  "At This Hour": "Šią valandą",
  "Add to": "Pridėti prie",
  Button: "Mygtukas",
  Buttons: "Mygtukai",
  Sunday: "Sekmadienis",
  Monday: "Pirmadienis",
  Tuesday: "Antradienis",
  Wednesday: "Trečiadienis",
  Thursday: "Ketvirtadienis",
  Friday: "Penktadienis",
  Saturday: "Šeštadienis",
  "Default Date": "Numatytoji data",
  year: "Metai",
  month: "Mėnuo",
  months: "Mėnesiai",
  days: "Dienos",
  ago: "prieš",
  ahead: "priekyje",
  Yesterday: "Vakar",
  Today: "Šiandien",
  Tomorrow: "Rytoj",
  Custom: "Pasirinktinis",
  "Set Daily Rows Limit": "Nustatyti dienos eilučių limitą",
  "Set Proportions": "Nustatyti proporcijas",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Leisti lankytojui pridėti įvykį prie vietinių kalendorių: Google, Yahoo, Outlook, iCalendar.",
  Container: "Talpykla",
  Background: "Fonas",
  "Container Background": "Talpyklos fonas",
  "Container Borders": "Talpyklos kraštai",
  Calendar: "Kalendorius",
  "Event Info Tooltip": "Įvyki informacijos iššokantis langas",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Užvedus pelės žymeklį ant įvykio, bus rodoma visa informacija apie įvykį.",
  "Event Info Window": "Įvykio informacijos langas",
  "This is the full information window that opens when someone clicks on the event.":
    "Tai visos informacijos langas, kuris atsidaro, kai kas nors paspaudžia ant įvykio",
  "Use Gradient": "Naudoti gradientą",
  Vertical: "Vertikaliai",
  Horizontal: "Horizontaliai",
  First: "Pirmas",
  Second: "Antras",
  diagonal: "Įstrižainė",
  Radial: "Spindulys",
  "Select option": "Pasirinkti parinktį",
  Solid: "Vientisas",
  Dotted: "Punktyrinis",
  Dashed: "Brūkšninis",
  Double: "Dvigubas",
  "Border Radius": "Kraštų spindulys",
  Padding: "Užpildas",
  "Date Header": "Datos antraštė",
  "Event Default Color": "Numatytoji įvykio spalva",
  "Days of Week": "Savaitės dienos",
  "Days of Week Background": "Savaitės dienų fonas",
  Date: "Data",
  "Event Title": "Įvykio pavadinimas",
  "Highlight today": "Pažymėti šiandieną",
  "Highlight Color": "Žymėjimo spalva",
  Hide: "Paslėpti",
  "Calendar Border Color": "Kalendoriaus apvado spalva",
  "Calendar Border Width": "Kalendoriaus krašto plotis",
  "Calendar Border Style": "Kalendoriaus apvado stilius",
  "Section Titles": "Skyrių pavadinimai",
  "Section Content": "Skyriaus turinys",
  "Event Background": "Įvykio fonas",
  "Card Date Color": "Kortelės datos spalva",
  "Title Font": "Pavadinimo šriftas",
  "Date Font": "Datos šriftas",
  "Description Font": "Aprašymo šriftas",
  "Button Background": "Mygtuko fonas",
  "Button Text": "Mygtuko tekstas",
  "Border Color": "Apvado spalva",
  "Border Width": "Apvado plotis",
  "Border Type": "Apvado tipas",
  Title: "Pavadinimas",
  Description: "Aprašymas",
  "Background Color": "Fono spalva",
  Divider: "Daliklis",
  "Event Details Font": "Įvykio informacijos šriftas",
  "Website Link Color": "Nuorodos spalva",
  "Developer Info": "Kūrėjo informacija",
  "User Guide": "Vartotojo vadovas",
  "Guides & Chat": "Gidai ir Pokalbiai",
  "Support e-mail": "Pagalbos el. paštas",
  "Our Website": "Mūsų svetainė",
  "App Review": "Programėlės apžvalga",
  "Enjoying App? Leave us a review in the App Market":
    "Patiko programėlė? Palikite atsiliepimą apie mus App Market",
  "Review Us": "Įvertinkite mus",
  "Connect With Us": "Susisiekite su mumis",
  "What's your email?": "Koks jūsų el. paštas?",
  "Invalid email address!": "Neteisingai įvestas el. paštas!",
  Comments: "Komentarai",
  "We'd love to hear from you. Send us a message.":
    "Norėtume išgirsti jūsų nuomonę. Siųskite mums žinutę.",
  "Message must be at least 5 characters long":
    "Žinutė turi būti ne trumpesnė nei 5 ženklų ilgio.",
  Send: "Siųsti",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jeigu norite leisti naudotojui keisti kalendoriaus rodinius, įjunkite šią parinktį ir pasirinkite norimus rodinius.",
  Main: "Pagrindinis",
  Localize: "Lokalizuoti",
  Settings: "Nustatymai",
  Layouts: "Maketai",
  Advanced: "Išplėstinis",
  Design: "Dizainas",
  Support: "Pagalba",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Visi vietiniai nustatymai (automatiškai) pagal jūsų kalbą. Jei jūsų kalba sąraše, tada šio skyriaus pritaikyti nereikia.",
  "Date Format": "Datos formatas",
  "Time Format": "Laiko formatas",
  "Text Direction": "Teksto kryptis",
  "Left to Right": "Iš kairės į dešinę",
  "Right to Left": "Iš dešinės į kairę",
  "Week Starts On": "Savaitė prasideda nuo",
  "Agenda Style": "Darbotvarkės stilius",
  Classic: "Klasikinis",
  Modern: "Modernus",
  AgendaHeader: "Darbotvarkės antraštė",
  UpcomingEvents: "Būsimi įvykiai",
  AgendaEventLimit: "Darbotvarkės įvykių limitas",
  UpgradeNowMessage:
    "Nusipirkite pilną versiją ir gaukite daug daugiau funkcijų bei mėgaukitės visa programėle!",
  UpgradeNow: "Pirkti pilną versiją",
  AllDayEventsMessage:
    "Organizuojate renginius, kurie trunka visą dieną? Tai leidžia juos rodyti kalendoriuje",
  "24Hours": "24 valandos",
  Sun: "S",
  Mon: "P",
  Sat: "Š",
  Default: "Numatytas",
  Style: "Stilius",
  CalendarName: "Kalendoriaus pavadinimas",
  WriteCalendarNameMessage: "Čia įrašykite savo kalendoriaus pavadinimą",
  EnableSearch: "Įgalinti paiešką",
  VisibleToUsersMessage:
    "Tai nematoma jūsų naudotojams. Nustatykite pavadinimus, kad galėtumėte atskirti savo kalendorius, kai naudojate 'Boom Calendar Sync' funkciją.",
  AddEvent: "+ Pridėti įvykį",
  ManageAndSync: "Tvarkyti ir sinchronizuoti",
  ShowEventDetails: "Rodyti įvykio informaciją kaip...",
  Tooltip: "Įrankių užuomina",
  Popup: "Iššokantis langas",
  None: "Nėra",
  ShowCategory: "Rodyti kategoriją",
  HeaderAlign: "Antraštės lygiavimas",
  ShowTime: "Rodyti laiką",
  HoursInWeeklyView: "Valandos savaitės/dieniniame rodinyje",
  ShareEvents: "Bendrinti įvykius",
  Shadow: "Šešėlis",
  "Inner Padding": "Vidinis užpildas",
  Text: "Tekstas",
  "Active Button Border": "Aktyvaus mygtuko apvadas",
  "Light Mode": "Šviesus režimas",
  "Event Text Color": "Įvykio teksto spalva",
  Dates: "Datos",
  Skeleton: "Griaučiai",
  "Skeleton Color": "Griaučių spalva",
  Width: "Plotis",
  "Skeleton Style": "Griaučių stilius",
  Color: "Spalva",
  Header: "Antraštė",
  Map: "Žemėlapis",
  Standard: "Standartinis",
  Retro: "Retro",
  Silver: "Sidabrinis",
  Night: "Naktinis",
  Dark: "Tamsus",
  Aubergine: "Baklažanas",
  "Map Header": "Žemėlapio antraštė",
  "Show Title in mobile": "Rodyti antraštę mobiliajame telefone",
  Card: "Kortelė",
  "Card View": "Kortelės vaizdas",
  "Card background color": "Kortelės fono spalva",
  "Title font": "Pavadinimo šriftas",
  "Desciption font": "Aprašymo šriftas",
  "Section font": "Skyriaus šriftas",
  "Section divider color": "Skyriaus skirtuko spalva",
  "Font Color": "Šrifto spalva",
  "General Info": "Bendra informacija",
  Venue: "Vieta",
  Organizer: "Organizatorius",
  Search: "Paieška",
  calendar: "Kalendorius",
  "Share this event": "Dalintis šiuo įvykiu",
  "Copy event URL": "Kopijuoti renginio nuorodą",
  "Copied!": "Nukopijuota!",
  "Add & Share": "Pridėti ir bendrinti",
  "Calendar view": "Kalendoriaus rodinys",
  "Add Event": "Pridėti įvykį",
  Uncategorised: "Be kategorijos",
  Shadow: "Šešėlis",
  "Inner Padding": "Vidinis užpildas",
  Text: "Tekstas",
  "Active Button Border": "Aktyvaus mygtuko apvadas",
  "Light Mode": "Šviesus režimas",
  "Event Text Color": "Įvykio teksto spalva",
  Dates: "Datos",
  Skeleton: "Griaučiai",
  "Skeleton Color": "Griaučių spalva",
  Width: "Plotis",
  "Skeleton Style": "Griaučių stilius",
  Color: "Spalva",
  Header: "Antraštė",
  Map: "Žemėlapis",
  Standard: "Standartinis",
  Retro: "Retro",
  Silver: "Sidabrinis",
  Night: "Naktinis",
  Dark: "Tamsus",
  Aubergine: "Baklažanas",
  "Map Header": "Žemėlapio antraštė",
  "Show Title in mobile": "Rodyti antraštę mobiliajame telefone",
  Card: "Kortelė",
  "Card View": "Kortelės vaizdas",
  "Card background color": "Kortelės fono spalva",
  "Title font": "Pavadinimo šriftas",
  "Desciption font": "Aprašymo šriftas",
  "Section font": "Skyriaus šriftas",
  "Section divider color": "Skyriaus skirtuko spalva",
  "Font Color": "Šrifto spalva",
  "General Info": "Bendra informacija",
  Venue: "Vieta",
  Organizer: "Organizatorius",
  Search: "Paieška",
  calendar: "Kalendorius",
  "Share this event": "Dalintis šiuo įvykiu",
  "Copy event URL": "Kopijuoti renginio nuorodą",
  "Copied!": "Nukopijuota!",
  "Add & Share": "Pridėti ir bendrinti",
  "Calendar view": "Kalendoriaus rodinys",
  "Add Event": "Pridėti įvykį",
  Uncategorised: "Be kategorijos",
  Categories: "Kategorijos",
  More: "Daugiau",
  Less: "Mažiau",
  Register: "Registruotis",
  Guests: "Svečiai",
  unlimited: "neribotas",
  "Show more": "Rodyti daugiau",
  "Add event ": "Pridėti įvykį",
  "All Day Event": "Visos dienos renginys",
  Location: "Vieta",
  "Choose a category": "Pasirinkti kategoriją",
  "Venue name": "Vietos pavadinimas",
  "Venue phone": "Vietos telefonas",
  "Venue email": "Vietos el. paštas",
  "Venue website": "Vietos svetainė",
  "Organizer name": "Organizatoriaus pavadinimas",
  "Organizer phone": "Organizatoriaus telefonas",
  "Organizer email": "Organizatoriaus el. paštas",
  "Organizer website": "Organizatoriaus svetainė",
  "Personal info": "Asmeninė informacija",
  "First name": "Vardas",
  "Last name": "Pavardė",
  "Email Address": "El. paštas",
  "Additional Notes": "Papildoma informacija",
  Back: "Grįžti",
  Save: "Išsaugoti",
  Next: "Toliau",
  "Your event has been submitted": "Jūsų įvykis yra pridėtas",
  "Event submittion has been failed": "Įvykio nepavyko pridėti",
  "e.g. Birthday Party": "Pvz.: Gimtadienio vakarėlis",
  "Phone Number": "Telefono numeris",
  Address: "Adresas",
  "Your comments": "Jūsų komentaras",
  "How many guests?": "Kiek svečių?",
  "Anything else we need to know?": "Ką mums dar reikėtų žinoti?",
  "Guests:": "Svečiai:",
  Submit: "Pateikti",
  "Go to Calendar": "Eiti į kalendorių",
  "Registration completed successfully!": "Registracija baigta sėkmingai!",
  "Please check your registered email address":
    "Patikrinkite savo registruotą el. pašto adresą",
  "Add to Calendar": "Įtraukti į kalendorių",
  "Share this Event": "Dalintis šiuo renginiu",
  "Sorry something went wrong": "Atsiprašome, kad kažkas nutiko",
  "Back to registration": "Grįžti į registraciją",
  "Date & Location": "Data ir vieta",
  "Date & Time": "Data ir laikas",
  home: "Pradžia",
  "Header align": "Antraštės lygiuotė",
  Footer: "Poraštė",
  "Categories Filter": "Kategorijų filtras",
  "Show only upcoming": "Rodyti tik būsimus",
  "Card(s) in a row": "Kortelė (-ės) iš eilės",
  "Space between cards": "Tarpas tarp kortelių",
  "Shown events limit": "Rodomų įvykių limitas",
  "Style 1": "Stilius 1",
  "Style 2": "Stilius 2",
  "Style 3": "Stilius 3",
  "Style 4": "Stilius 4",
  "Buttons & Links": "Mygtukai ir nuorodos",
  "Button corner radius": "Mygtuko kampo spindulys",
  "Buttons font": "Mygtukų šriftas",
  "Buttons background": "Mygtukų fonas",
  "Get notified by Email": "Gauti pranešimą el. paštu",
  "Review events": "Peržiūrėti įvykius",
  "Click on date": "Paspausti ant datos",
  "Add Event button": "Pridėti įvykio mygtuką",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Kalendoriaus sinchronizavimas leidžia integruoti įvykius ir sesijas su 'Boom' kalendoriumi.",
  connect: "Prisijungti",

  "Synchronized Calendars": "Sinchronizuoti kalendoriai",
  "Import events": "Importuoti įvykius",
  Disconnect: "Atsijungti",
  "Choose calendar": "Pasirinkti kalendorių",
  "Monitor your Wix events through the sync feature":
    'Stebėkite "Wix" įvykius naudodami sinchronizavimo funkciją',
  "Connect all your Boom calendars available on your website":
    'Sujunkite visus savo "Boom" kalendorius, esančius jūsų svetainėje',
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    'Planuokite, prisijunkite ir valdykite "Zoom" susitikimus tiesiai per "Boom" kalendorių.',
  "Monitor your Event Brite events through the Event Brite sync feature":
    'Stebėkite "Event Brite" įvykius naudodami "Event Brite" sinchronizavimo funkciją',
  Email: "El. paštas",
  "Add-ons": "Priedai",
  "Switch Add Event": "Perjungti pridėti įvykį",
  "Enable your browser cookies to connect to your account.":
    "Įjunkite naršyklės slapukus, kad galėtumėte prisijungti prie savo paskyros.",
  "Learn more": "Sužinokite daugiau",
  "Print Button": "Spausdinimo mygtukas",
  "Permit your users to print your Boom Event Calendar in any date range.":
    'Leiskite naudotojams spausdinti "Boom" įvykių kalendorių bet kuriuo datų intervalu.',
  "Show Title on mobile": "Rodyti pavadinimą mobiliajame telefone",
  "Show Skeleton on mobile": "Rodyti skeletą mobiliajame telefone",
  "Start 7-day Business trial": "Pradėti 7 dienų verslo bandomąją versiją",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    'Mėgaukitės visomis neišbandytomis funkcijomis, tokiomis kaip "Parduoti bilietus", "Registracija", “Lankytojų renginių priedai”.',

  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    " Atkreipkite dėmesį: pasibaigus bandomajam laikotarpiui būsite grąžinti prie ",
  "Not Now": "Ne dabar",
  "Start free trial": "Pradėti nemokamą bandomąjį laikotarpį",
  "Congrats!": "Sveikiname!",
  "Your 7-day Business trial has been successfully activated.":
    "Jūsų 7 dienų verslo bandomasis laikotarpis sėkmingai aktyvuotas.",
  Done: "Atlikta",
  "Title font color": "Pavadinimo šrifto spalva",
  "Desciption font color": "Aprašymo šrifto spalva",
  "Section font color": "Skyriaus šrifto spalva",
  "Card Header": "Kortelės antraštė",
  Category: "Kategorija",
  "Display at the": "Rodyti viršuje",
  top: "viršuje",
  bottom: "apačioje",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Parodykite kategorijos filtrą kalendoriaus viršuje arba apačioje. Nustatymai taikomi tik Darbotvarkės ir Kortelės rodiniams",
  "Processing your events": "Įvykių apdorojimas",
  "Search for events": "Įvykių paieška",
  "There are no events added": "Nėra pridėtų įvykių",
  "Location: To be determined":
    "Vieta, kurioje vyksta renginiai: Bus nustatyta",
  "No events for selected date": "Nėra pasirinktos datos renginių",
  Uncategorized: "Be kategorijos",
  "Edit event": "Redaguoti įvykį",
  "Edit original event": "Redaguoti pirminį įvykį",
  "Copy event": "Kopijuoti įvykį",
  "Copy as new event": "Kopijuoti kaip naują įvykį",
  "Delete event": "Ištrinti įvykį",
  "Stop repeating on this date": "Nustoti kartoti šią dieną",
  "Exclude this date": "Neįtraukti šios datos",
  "Location is going to be announced": "Vieta dar bus paskelbta",
  "Fill your personal information": "Užpildykite savo asmeninę informaciją",
  "Check Box": "Pažymėti langelį",
  "Single Choice": "Vienas pasirinkimas",
  Option: "Pasirinkimas",
  "Share Event": "Bendrinti įvykį",
  "Oops! Something went wrong": "Oops! Kažkas nutiko ne taip",
  "We are sorry this event has already taken place":
    "Atsiprašome, šis įvykis jau įvyko",
  "Back to calendar": "Atgal į kalendorių",
  "This field is required": "Šis laukas yra privalomas",
  Phone: "Telefonas",
  "Number field": "Numerio laukas",
  "Check Box": "Pažymėjimo langelis",
  "Single Choice": "Vienas pasirinkimas",
  "Please provide a valid email": "Nurodykite galiojantį el. pašto adresą",
  "Select at least one option": "Pasirinkite bent vieną parinktį",
  "Choose tickets to see total value":
    "Pasirinkite bilietus, kad pamatytumėte bendrą vertę.",
  tickets: "bilietai",
  "Choose Tickets": "Pasirinkite bilietus",
  "Choose payment method": "Pasirinkite mokėjimo būdą",
  Pay: "Mokėti",
  Total: "Iš viso",
  Free: "Nemokamai",
  "Buy tickets": "Pirkti bilietus",
  "Sold Out": "Išparduota",
  "Tickets are available": "Bilietų yra",
  "Sales End": "Pardavimų pabaiga",
  "Availible from": "Galima nuo",
  "Go to Orders": "Eiti į užsakymus",
  "Go to Details": "Eiti į informaciją",
  "Group ticket": "Grupės bilietas",
  Name: "Pavadinimas",
  Price: "Kaina",
  "Order by": "Užsakyti pagal",
  "Order ID": "Užsakymo Numeris",
  Applied: "Pritaikytas",
  Fees: "Mokesčiai",
  "Enter promo code": "Įveskite nuolaidos kodą",
  Apply: "Pritaikyti",
  "Promo Code": "Nuolaidos kodas",
  Cash: "Grynais",
  "You can find your e-tickets attached to your email or download them":
    "Elektroninius bilietus rasite prisegtus prie el. pašto arba atsisiųskite juos",
  here: "čia",
  Time: "Laikas",
  "Invalid promo code": "Neteisingas nuolaidos kodas",
  "Credit card": "Kreditinė kortelė",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Netrukus į savo el. pašto adresą gausite sėkmingos registracijos patvirtinimo pranešimą.",
  "You can also check your order details below.":
    "Toliau taip pat galite patikrinti savo užsakymo informaciją.",
  at: "adresu",
  Buy: "Pirkti",
  Donation: "Paaukoti",
  "Enter price": "Įveskite kainą",
  Choose: "Pasirinkite",
  Chosen: "Pasirinktas",
  "Choose your plan": "Pasirinkite planą",
  week: "savaitė",
  "Choose plan cycle": "Pasirinkti plano ciklą",
  months: "mėnesiai",
  years: "metai",
  weeks: "savaitės",
  "Copy Event Url": "Kopijuoti įvykio nuorodą",
  "You can find your e-tickets attached to your email or print them":
    "Elektroninius bilietus galite rasti prisegtus prie el. laiško arba atsispausdinti",
  "Guest Info": "Informacija svečiams",
  "Ticket Info": "Informacija apie bilietus",
  "Ticket name": "Bilieto pavadinimas",
  "Ticket price": "Bilieto kaina",
  "Ticket ID": "Bilieto numeris",
  "If you have any questions contact to organizer":
    "Jei turite klausimų, kreipkitės į organizatorių",
  "As soon as event ends": "Iš karto po renginio pabaigos",
  "1 day after event ends": "1 diena po renginio pabaigos",
  "7 days after event ends": "7 dienos po renginio pabaigos",
  "14 days after event ends": "14 dienų po renginio pabaigos",
  "30 days after event ends": "30 dienų po renginio pabaigos",
  Menu: "Meniu",
  "No event for selected date": "Nėra įvykio pasirinktoje datoje",
};
