let mk = {
  "Your Api Key": "Вашиот Api клуч",
  "Fahrenheit": "Фаренхајт",
  "Celsius": "Целзиусови",
  "Select the city from the suggestions": "Изберете го градот од предлозите",
  "Weather Forecast": "Временска прогноза",
  "Cross Event Limit": "Вкрстено ограничување на настанот",
  "Show events limit": "Прикажи ограничување на настани",
  "Show tooltip/popup": "Прикажи совет/скокачки прозорец",
  "Bold Monthly Dividers": "Задебелени месечни разделувачи",
  "Scroll to see more events": "Скролувајте за да видите повеќе настани",
  "Show additional date": "Прикажи дополнителен датум",
  "Custom Link": "Прилагодена врска",
  "Link to event page": "Врска до страницата за настан",
  "No link": "Нема врска",
  "Attach File": "Прикачи датотека",
  "To be announced": "Да се ​​објави",
  "Online": "Онлајн",
  "Physical": "Физички",
  "Select Categories to display events related to them, or manually choose specific events under Events": "Изберете Категории за прикажување настани поврзани со нив или рачно изберете конкретни настани под Настани",
  "Automatically approve events from these addresses": "Автоматски одобрувајте настани од овие адреси",
  "Approve events": "Одобри настани",
  "Payable with a plan": "Се плаќа со план",
  "Service Details": "Детали за услугата",
  "participants": "учесниците",
  "To": "На",
  "From": "Од",
  "Ahead": "Напред",
  "Ago": "Пред",
  "Change the category": "Променете ја категоријата",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Синхронизацијата на Ticket Tailor ви овозможува да ги интегрирате вашите настани и сесии со вашиот Boom Calendar.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Прикажи го времето на настанот до насловот. Оваа поставка е применлива само за месечни, дневни и неделни прикази.",
  "Show Staff Member": "Прикажи член на персоналот",
  "Show Price": "Прикажи цена",
  "To Event Page": "До страницата за настан",
  "Layout": "Распоред",
  "Acending": "Надополнување",
  "Yearly": "Годишно",
  "Layout device": "Уред за распоред",
  "Date container font": "Фонт на контејнер за датум",
  "Hide Fully Booked Slots": "Сокриј ги целосно резервираните слотови",
  "Enable": "Овозможи",
  "Limit": "Граница",
  "Export": "Извоз",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Ќе ги промените деталите за вашиот настан. Откако ќе се промени, вашата листа на гости ќе се изгуби.",
  "Change Date": "Променете го датумот",
  "Ends": "Завршува",
  "On": "На",
  "After": "По",
  "Accept": "Прифати",
  "Show less": "Покажете помалку",
  "Venue detail": "Детали за местото на одржување",
  "Reject": "Отфрли",
  "See guest list": "Погледнете го списокот на гости",
  "Submit Date": "Датум на поднесување",
  "Total guests": "Вкупно гости",
  "Do you really want to delete selected user? Once removed, cannot be undone.": "Дали навистина сакате да го избришете избраниот корисник? Откако ќе се отстрани, не може да се врати.",
  "Delete Guest": "Избриши го гостинот",
  "Invoice number": "Број на фактура",
  "Status": "Статус",
  "Payment type": "Начин на плаќање",
  "Select payment method to receive fees through tickets": "Изберете начин на плаќање за да добивате такси преку билети",
  "Add Code": "Додадете код",
  "Add End Time": "Додадете време на завршување",
  "Discount": "Попуст",
  "Promo codes for the sales": "Промо кодови за продажба",
  "Promo codes": "Промо кодови",
  "Add Ticket": "Додадете билет",
  "Limit type": "Тип на ограничување",
  "Paid": "Платено",
  "Participation tickets for your event": "Билети за учество за вашиот настан",
  "Show the ticket limit": "Покажете го лимитот на билетите",
  "Show limit": "Прикажи ограничување",
  "Show the price on ticket": "Покажете ја цената на билетот",
  "Enable and configure your ticketing system": "Овозможете и конфигурирајте го вашиот систем за билети",
  "Stop repeating here": "Престанете да повторувате овде",
  "Limited": "Ограничени",
  "Unlimited": "Неограничено",
  "Thank you message title": "Наслов на пораката за благодарност",
  "Submit button text": "Испрати текст на копчето",
  "Registration button text": "Текст на копчето за регистрација",
  "Texts": "Текстови",
  "Modify the displayed texts": "Изменете ги прикажаните текстови",
  "Thank you message body": "Тело на пораката за благодарност",
  "Notify the user when the registration is canceled": "Известете го корисникот кога регистрацијата е откажана",
  "Cancellation email": "Е-пошта за откажување",
  "Send a reminder to the user one day prior to the event": "Испратете потсетник до корисникот еден ден пред настанот",
  "Reminder email": "Е-пошта за потсетување",
  "Send an instant email to the user once registration is completed": "Испратете инстант е-пошта до корисникот откако ќе заврши регистрацијата",
  "Notification email": "Е-пошта за известување",
  "Reminder email about the event": "Е-пошта за потсетување за настанот",
  "Email notifications to users": "Известувања по е-пошта до корисниците",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).": "Кликнете на копчињата за менување до секое поле за да го додадете во формуларот за регистрација. Ако сакате да го направите полето потребно, кликнете на ѕвездичката (*).",
  "Form Fields": "Полиња за формулари",
  "Enter your form description": "Внесете го описот на вашата форма",
  "Form Title": "Наслов на формуларот",
  "Enter your form title": "Внесете го насловот на вашата форма",
  "Form Details": "Детали за формуларот",
  "Configure your registration form fields": "Конфигурирајте ги полињата за формуларот за регистрација",
  "Show guest limit": "Прикажи го ограничувањето за гости",
  "Enable Registration": "Овозможи Регистрација",
  "Click to activate registration on this event": "Кликнете за да ја активирате регистрацијата на овој настан",
  "Customize the general settings of registration": "Прилагодете ги општите поставки за регистрација",
  "Enter URL": "Внесете URL",
  "Page URL": "URL на страницата",
  "Close registration when the event starts": "Затворете ја регистрацијата кога ќе започне настанот",
  "Redirect to a different website": "Пренасочете се на друга веб-локација",
  "Where users can register": "Каде што корисниците можат да се регистрираат",
  "Open event registration landing page": "Отворете целна страница за регистрација на настан",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.": "Мора да ви требаше многу подготовка за да се подготвите за вашиот настан. Сега е време да седнете и да се опуштите додека вашите гости не се соберат наоколу! Штом се направи нова регистрација, информациите за вашиот гостин ќе се појават овде. Вратете се подоцна за да ги следите присутните на вашиот настан.",
  "You have no guests at the moment.": "Немате гости во моментов.",
  "List of people who are registered to your event": "Список на луѓе кои се регистрирани на вашиот настан",
  "Guest List": "Листа на гости",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.": "Ова е настан што се повторува! Сите промени направени на овој настан ќе се применуваат на сите повторувања.",
  "Repeated event": "Повторен настан",
  "Delete Category": "Избришете ја категоријата",
  "Do you really want to delete selected category? Once removed, cannot be undone.": "Дали навистина сакате да ја избришете избраната категорија? Откако ќе се отстрани, не може да се врати.",
  "OK": "добро",
  "Exclude": "Исклучи",
  "Custom recurrence": "Прилагодено повторување",
  "Duplicate": "Дупликат",
  "Delete": "Избриши",
  "Published": "Објавено",
  "Drafts": "Нацртови",
  "User events": "Кориснички настани",
  "Add new category": "Додадете нова категорија",
  "Manage categories": "Управувајте со категориите",
  "Add category": "Додадете категорија",
  "Never": "Никогаш",
  "Repeat every": "Повторете секој",
  "Do you really want to delete selected event? Once removed, cannot be undone": "Дали навистина сакате да го избришете избраниот настан? Откако ќе се отстрани, не може да се врати",
  "There are no categories yet": "Сè уште нема категории",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.": "Правење промени во вашиот синхронизиран календар со следните врски. Ве молиме внимателно разгледајте ги вашите промени.",
  "occurrences": "појави",
  "Save as draft": "Зачувате како нацрт",
  "More Info": "Повеќе информации",
  "Book Now": "Резервирајте сега",
  "Show participants": "Прикажи учесници",
  "This service is fully booked.": "Оваа услуга е целосно резервирана.",
  "All sessions are fully booked.": "Сите сесии се целосно резервирани.",
  "Registration closed": "Регистрацијата е затворена",
  "Show your Wix Bookings or Events on Calendar": "Покажете ги вашите резервации или настани на календарот",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.": "Изберете Auto за автоматско прикажување на сите услуги и сесии на календарот или прирачник за рачен избор.",
  "Show cancelled events": "Покажете откажани настани",
  "Event Color": "Боја на настани",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.": "Изберете Auto за автоматско прикажување на сите настани на календарот или прирачник за рачен избор.",
  "Auto": "Автоматско",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.": "Изберете Auto за автоматско прикажување на сите организации и организатори на календарот или прирачник за рачен избор.",
  "Manual": "Прирачник",
  "Sync method": "Метод на синхронизација",
  "Enable synchronization": "Овозможете синхронизација",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only": "Покажете го филтерот за категорија на горниот или на дното на календарот. Поставките се однесуваат само на агендата, крстот, временската рамка и прегледот на картичките",
  "Load Events": "Оптоварување настани",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.": "Откако ќе се овозможи, вашиот додаток за календар ќе биде преведен врз основа на јазикот на веб -страницата. Забележете дека сè додека насловите и описите на календарот се внесуваат како текст, тие не можат да бидат преведени.",
  "Choose plan type": "Изберете Тип на план",
  "Api key": "API клуч",
  "Synchronized Boxes": "Синхронизирани кутии",
  "Choose box": "Изберете кутија",
  "There are no synchronized boxes": "Нема синхронизирани кутии",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Синхронизација за прилагодување на билетите ви овозможува да ги интегрирате вашите настани и сесии со вашиот календар за бум",
  Categories: "Категории",
  "Share this event": "Споделете го овој настан",
  Language: "Јазик",
  "Show Time Zone": "Покажете временска зона",
  "Custom Local Settings": "Прилагодени локални поставки",
  "Add and showcase events on your site using a beautiful calendar.":
    "Додадете и покажете настани на вашата страница користејќи прекрасен календар.",
  "Week Days": "Неделни денови",
  "Manage Events": "Управувајте со настани",
  General: "Општо",
  "Layout Picker": "Избирач на распоред",
  Month: "Месец",
  Monthly: "Месечно",
  Week: "Недела",
  Weekly: "Неделно",
  Day: "Ден",
  Daily: "Дневно",
  Agenda: "Агенда",
  "Navigation Buttons": "Копчиња за навигација",
  "Week numbers": "Неделни броеви",
  "Include Weekends": "Вклучете викенди",
  "All-day": "Цел ден",
  "All Day": "Цел ден",
  Label: "Етикета",
  "Fit to Height": "Одговара на висина",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "За да ги поставите пропорциите на апликацијата, мануларно оневозможете ја оваа опција и да ја промените големината на календарот во уредникот.",
  "Default Layout": "Стандарден распоред",
  "Monthly view": "Месечен поглед",
  "Weekly and Daily view": "Неделен и дневен преглед",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Можете да им дадете на посетителите поконзистентно искуство покажувајќи ист број на недели (6) истовремено.",
  "Fixed Weekly Layout": "Фиксен неделен распоред",
  back: "назад",
  Row: "Ред",
  "Hours in Weekly View": "Часови во неделен преглед",
  "Hours in Daily View": "Часови во секојдневен преглед",
  Start: "Започнете",
  End: "Крај",
  "At This Hour": "Во овој час",
  Button: "Копче",
  Buttons: "Копчиња",
  Sunday: "Недела",
  Monday: "Понеделник",
  Tuesday: "вторник",
  Wednesday: "Среда",
  Thursday: "Четврток",
  Friday: "Петок",
  Saturday: "Сабота",
  "Default Date": "Стандарден датум",
  year: "година",
  month: "месец",
  mo: "Мо",
  days: "денови",
  ago: "пред",
  ahead: "напред",
  Yesterday: "Вчера",
  Today: "Денес",
  Tomorrow: "Утре",
  Custom: "Обичај",
  "Set Daily Rows Limit": "Поставете ограничување на дневните редови",
  "Set Proportions": "Поставете пропорции",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозволете му на посетителот да додаде настан на локалните Калнедари: Google, Yahoo, Outlook, Icalendar.",
  Container: "Контејнер",
  Background: "Позадина",
  "Container Background": "Позадина на контејнерот",
  "Container Borders": "Граници на контејнери",
  Calendar: "Календар",
  "Event Info Tooltip": "Информации за настани Информации за алатки",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Кога луѓето лебдат над некој настан, ќе ги видат сите информации за тоа во алатката.",
  "Event Info Window": "Прозорец за инфо за настани",
  "This is the full information window that opens when someone clicks on the event.":
    "Ова е целосен прозорец за информации што се отвора кога некој ќе кликне на настанот.",
  "Use Gradient": "Користете градиент",
  Vertical: "Вертикално",
  Horizontal: "Хоризонтална",
  First: "Прво",
  Second: "Второ",
  diagonal: "Дијагонала",
  Radial: "Радијален",
  "Select option": "Изберете опција",
  Solid: "Цврст",
  Dotted: "Испрекинат",
  Dashed: "Испрекинато",
  Double: "Двојно",
  "Border Radius": "Граничен радиус",
  Padding: "Подлога",
  "Date Header": "Заглавие на датумот",
  "Event Default Color": "Стандардна боја на настан",
  "Days of Week": "Денови на недела",
  "Days of Week Background": "Денови на позадина на неделата",
  Date: "Датум",
  "Event Title": "Наслов на настанот",
  "Highlight today": "Означете денес",
  "Highlight Color": "Означете ја бојата",
  Hide: "Крие",
  "Calendar Border Color": "Календарска гранична боја",
  "Calendar Border Width": "Ширина на границата со календарот",
  "Calendar Border Style": "Календарски граничен стил",
  "Font Color": "Боја на фонтот",
  "Event Background": "Позадина на настанот",
  "Card Date Color": "Боја на датумот на картичката",
  "Title Font": "Фонт за наслов",
  "Date Font": "Фонт за датум",
  "Description Font": "Опис Фонт",
  "Button Background": "Позадина на копчето",
  "Button Text": "Текст на копчето",
  "Border Color": "Гранична боја",
  "Border Width": "Ширина на границата",
  "Border Type": "Тип на граница",
  Title: "Наслов",
  Description: "Опис",
  "Background Color": "Боја на позадина",
  Divider: "Делител",
  "Event Details Font": "Детали за настанот Фонт",
  "Website Link Color": "Боја на врската на веб -страницата",
  "Developer Info": "Информации за развивачи",
  "User Guide": "Упатство за корисникот",
  "Support e-mail": "Поддршка е-пошта",
  "Our Website": "Нашата веб -страница",
  "App Review": "Преглед на апликации",
  "Enjoying App? Leave us a review in the App Market.":
    "Уживате во апликација? Оставете ни преглед на пазарот на апликации.",
  "Review Us": "Прегледајте нè",
  "Connect With Us": "Поврзете се со нас",
  "What's your email?": "Која е твојата е-пошта?",
  "Invalid email address!": "Невалидна адреса за е -пошта!",
  Comments: "Коментари",
  "We'd love to hear from you. Send us a message.":
    "Ние би сакале да чуеме од вас. Испратете ни порака.",
  "Message must be at least 5 characters long":
    "Пораката мора да биде долга најмалку 5 карактери",
  Send: "Испрати",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Ако сакате да му дозволите на корисникот да се префрли помеѓу прегледите на календарот, да ја овозможи оваа опција и да ги изберете прегледите што сакате да ги покажете.",
  Main: "Главна",
  Localize: "Локализирај",
  Settings: "Поставки",
  Layouts: "Распоред",
  Advanced: "Напредно",
  Design: "Дизајн",
  Support: "Поддршка",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Сите локални поставки се (автоматски) засновани на вашиот јазик. Ако вашиот јазик е на списокот, нема потреба да го прилагодите овој дел.",
  "Date Format": "Формат на датум",
  "Time Format": "Формат на време",
  "Text Direction": "Насока на текст",
  "Left to Right": "Лево кон десно",
  "Right to Left": "Десно кон лево",
  "Week Starts On": "Неделата започнува",
  "Agenda Style": "Агенда стил",
  Classic: "Класичен",
  Modern: "Модерно",
  "Agenda Header": "Заглавие на агендата",
  "Upcoming Events": "Престојни настани",
  "Agenda Event Limit": "Ограничување на настанот на агендата",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Надградете сега и добијте многу повеќе карактеристики и уживајте во вашата апликација во целост!",
  "Upgrade Now": "Надогради сега",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Домаќини настани што траат цел ден? Ова ви овозможува да ги покажете на вашиот календар.",
  "24 hours": "24 часа",
  Sat: "САТ",
  Sun: "Сонце",
  Mon: "Пон",
  Default: "Стандардно",
  "Select custom design style for your calendar.":
    "Изберете стил на прилагодено дизајнирање за вашиот календар.",
  Style: "Стил",
  "Styles and Colors": "Стилови и бои",
  "Calendar Name": "Име на календарот",
  "Write your Calendar name here": "Напишете го вашето име на календарот овде",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Ова не е видливо за вашите корисници. Поставете имиња за да ги разликувате вашите календари кога ја користите функцијата за синхронизација на календарот за бум.",
  "General Info": "Општи информации",
  Venue: "Место",
  Organizer: "Организатор",
  Search: "Пребарување",
  "Add to": "Додадете на",
  calendar: "Календар",
  "Copy event URL": "Копирајте ја URL -то на настанот",
  "Copied!": "Копирани!",
  "Add & Share": "Додај и сподели",
  Map: "Карта",
  "Calendar view": "Преглед на календарот",
  "Add Event": "Додадете настан",
  Uncategorised: "Некатегоризирано",
  More: "Повеќе",
  Less: "Помалку",
  Register: "Регистар",
  Card: "Картичка",
  Guests: "Гости",
  unlimited: "Неограничено",
  "Show more": "Покажете повеќе",
  "Enable Search": "Овозможете пребарување",
  "+ Add Event": " + Додај настан",
  "Manage and Sync": "Управувајте и синхронизирајте",
  "Show event details as...": "Покажете детали за настанот како ...",
  Tooltip: "Алатки",
  Popup: "Пукање",
  None: "Ништо",
  "Show Category": "Категорија на шоу",
  "Header Align": "Усогласување на заглавието",
  "Show Time": "Време за забава",
  "Hours in Weekly/Daily View": "Часови во неделно/дневно прегледување",
  "Share Events": "Споделете настани",
  Shadow: "Сенка",
  "Inner Padding": "Внатрешно подлога",
  Text: "Текст",
  "Active Button Border": "Активно граница на копчињата",
  "Light Mode": "Режим на светлина",
  "Event Text Color": "Боја на текст на настанот",
  Dates: "Датуми",
  Skeleton: "Скелет",
  "Skeleton Color": "Боја на скелети",
  Width: "Ширина",
  "Skeleton Style": "Стил на скелет",
  Color: "Боја",
  "Section Titles": "Наслови на секции",
  "Section Content": "Содржина на дел",
  Header: "Заглавие",
  Standard: "Стандард",
  Retro: "Ретро",
  Silver: "Сребро",
  Night: "Ноќ",
  Dark: "Темно",
  Aubergine: "Модар патлиџан",
  "Map Header": "Заглавие на картата",
  "Show Title in mobile": "Покажи наслов во Мобиле",
  "Card View": "Преглед на картичка",
  "Card background color": "Боја во позадина на картичката",
  "Title font": "Фонт за наслов",
  "Desciption font": "Фонт за отпуштање",
  "Section font": "Фонт во дел",
  "Section divider color": "Боја на делот",
  "Add event": "Додадете настан",
  "All Day Event": "Цел ден настан",
  Location: "Локација",
  "Choose a category": "Изберете категорија",
  "Venue name": "Име на место",
  "Venue phone": "Телефон на место",
  "Venue email": "Место за е -пошта",
  "Venue website": "Веб -страница на место",
  "Organizer name": "Име на организатор",
  "Organizer phone": "Телефон на организатор",
  "Organizer email": "Организатор е -пошта",
  "Organizer website": "Организатор веб -страница",
  "Personal info": "Лични информации",
  "First name": "Име",
  "Last name": "Презиме",
  "Email Address": "И-мејл адреса",
  "Additional Notes": "дополнителни забелешки",
  Back: "Назад",
  Save: "Зачувај",
  Next: "Следно",
  "Your event has been submitted": "Вашиот настан е доставен",
  "Event submittion has been failed": "Поднесувањето на настанот е неуспешна",
  "e.g. Birthday Party": "на пр. Роденденска забава",
  "First Name": "Име",
  "Last Name": "Презиме",
  "Phone Number": "Телефонски број",
  Address: "Адреса",
  "Your comments": "Вашите коментари",
  "How many guests?": "Колку гости?",
  "Anything else we need to know?": "Нешто друго што треба да знаеме?",
  "Guests:": "Гости:",
  Submit: "Достави",
  "Go to Calendar": "Одете во календарот",
  "Registration completed successfully!": "Регистрацијата успешно заврши!",
  "Please check your registered email address":
    "Проверете ја вашата регистрирана адреса за е -пошта",
  "Add to Calendar": "Додадете во календарот",
  "Share this Event": "Споделете го овој настан",
  "Sorry something went wrong": "Извини, нешто тргна наопаку",
  "Back to registration": "Назад на регистрација",
  "Date & Location": "Датум и локација",
  "Date & Time": "Датум време",
  home: "дома",
  "Header align": "Усогласување на заглавието",
  Footer: "Подножје",
  "Categories Filter": "Филтер за категории",
  "Show only upcoming": "Покажете само претстојно",
  "Card(s) in a row": "Картичка (и) по ред",
  "Space between cards": "Простор помеѓу картички",
  "Shown events limit": "Прикажани ограничувања на настаните",
  "Style 1": "Стил 1",
  "Style 2": "Стил 2",
  "Style 3": "Стил 3",
  "Style 4": "Стил 4",
  "Buttons & Links": "Копчиња и врски",
  "Button corner radius": "Радиус на аголот на копчето",
  "Buttons font": "Копчиња Фонт",
  "Buttons background": "Позадина на копчињата",
  "Get notified by Email": "Се известуваат по е -пошта",
  "Review events": "Преглед на настани",
  "Click on date": "Кликнете на датумот",
  "Add Event button": "Додадете копче за настан",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронизација на календарот ви овозможува да ги интегрирате вашите настани и сесии со вашиот календар за бум.",
  connect: "Поврзете се",
  "Synchronized Calendars": "Синхронизирани календари",
  "Import events": "Увоз на настани",
  Disconnect: "Исклучување",
  "Choose calendar": "Изберете календар",
  "Monitor your Wix events through the sync feature":
    "Следете ги вашите WIX настани преку функцијата за синхронизација",
  "Connect all your Boom calendars available on your website":
    "Поврзете ги сите ваши календари за бум достапни на вашата веб -страница",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Распоред, придружете се и управувајте со состаноци за зумирање точно преку нашиот календар за бум.",
  "Monitor your Event Brite events through the Event Brite sync feature.":
    "Следете го вашиот настан Brite настани преку настанот Brite Sync функција",
  Email: "Е -пошта",
  "Add-ons": "Додатоци",
  "Receive notification emails as soon as users add events to your calendar.":
    "Добијте е -пошта за известување веднаш штом корисниците додаваат настани во вашиот календар.",
  "Enable + button on the calendar header":
    "Овозможете + копче на заглавието на календарот",
  "Accept or decline events added by customers before making them public.":
    "Прифатете ги или одбијте ги настаните додадени од клиентите пред да ги објават.",
  "Switch Add Event": "Прекинувач Додај настан",
  "Enable your browser cookies to connect to your account.":
    "Овозможете ги колачињата од прелистувачот да се поврзат со вашата сметка.",
  "Learn more": "Научи повеќе",
  "Print Button": "Копче за печатење",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозволете им на вашите корисници да го отпечатат вашиот календар за настани за бум во кој било опсег на датум.",
  "Show Title on mobile": "Покажи наслов на мобилен телефон",
  "Show Skeleton on mobile": "Покажете скелет на мобилен телефон",
  "Start 7-day Business trial": "Започнете 7-дневно деловно испитување",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Уживајте во сите неограничени карактеристики, како што се билети за продажба, регистрација, додатоци за настани за посетители.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Забележете: На крајот на пробниот период, ќе бидете вратени на постојниот план за претплата.",
  "Not Now": "Не сега",
  "Start free trial": "Започнете бесплатно проба",
  "Congrats!": "Честитки!",
  "Your 7-day Business trial has been successfully activated.":
    "Вашето 7-дневно деловно испитување е успешно активирано.",
  Done: "Направено",
  "Title font color": "Наслов на бојата на фонтот",
  "Desciption font color": "Боја на фонтот за отпуштање",
  "Section font color": "Боја на фонтот на дел",
  "Card Header": "Заглавие на картички",
  Category: "Категорија",
  "Display at the": "Приказ на",
  top: "врв",
  bottom: "дно",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Покажете го филтерот за категорија на горниот или на дното на календарот. Поставките се однесуваат само на агендата и прегледите на картичките",
  "Processing your events": "Обработка на вашите настани",
  "Search for events": "Барајте настани",
  "There are no events added": "Нема додадени настани",
  "Location: To be determined": "Локација: Да се ​​утврди",
  "No events for selected date": "Нема настани за избраниот датум",
  Uncategorized: "Некатегоризирано",
  "Edit event": "Уреди настан",
  "Edit original event": "Уреди оригинален настан",
  "Copy event": "Копирајте настан",
  "Copy as new event": "Копирајте како нов настан",
  "Delete event": "Избриши настан",
  "Stop repeating on this date": "Престанете да повторувате на овој датум",
  "Exclude this date": "Исклучете го овој датум",
  "Location is going to be announced": "Локацијата ќе биде објавена",
  "Fill your personal information": "Пополнете ги вашите лични информации",
  "Check Box": "Поле за проверка",
  "Single Choice": "Единечен избор",
  Option: "Опција",
  "Share Event": "Споделете настан",
  "Oops! Something went wrong": "Упс! Нешто тргна наопаку",
  "We are sorry this event has already taken place":
    "Areал ни е што веќе се случи овој настан",
  "Back to calendar": "Назад во календарот",
  "This field is required": "Ова поле е задолжително",
  Phone: "Телефон",
  "Number field": "Поле за број",
  "Please provide a valid email": "Ве молиме, наведете валидна е -пошта",
  "Select at least one option": "Изберете барем една опција",
  "Choose tickets to see total value":
    "Изберете билети за да ја видите вкупната вредност",
  tickets: "Билети",
  "Choose Tickets": "Изберете билети",
  "Choose payment method": "Изберете начин на плаќање",
  Pay: "Плати",
  Total: "Вкупно",
  Free: "Бесплатно",
  "Buy tickets": "Купете билети",
  "Sold Out": "Продадено",
  "Tickets are available": "Билетите се достапни",
  "Sales End": "Крај на продажбата",
  "Availible from": "Достапно од",
  "Go to Orders": "Одете на нарачки",
  "Go to Details": "Одете на детали",
  "Group ticket": "Групно билет",
  Name: "Име",
  Price: "Цена",
  "Order by": "Нарачка од",
  "Order ID": "ID на нарачка",
  Applied: "Применето",
  Fees: "Такси",
  "Enter promo code": "Внесете промо -код",
  Apply: "Применуваат",
  "Promo Code": "Промотивен код",
  Cash: "Готовина",
  "You can find your e-tickets attached to your email or download them":
    "Можете да ги најдете вашите е-билети прикачени на вашата е-пошта или да ги преземете",
  here: "Еве",
  Time: "Време",
  "Invalid promo code": "Невалиден промо -код",
  "Credit card": "Кредитна картичка",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Наскоро ќе добиете порака за потврда за успешна регистрација на вашата адреса за е -пошта.",
  "You can also check your order details below.":
    "Можете исто така да ги проверите деталите за вашата нарачка подолу.",
  at: "на",
  Buy: "Купи",
  Donation: "Донација",
  "Enter price": "Внесете ја цената",
  Choose: "Изберете",
  Chosen: "Избран",
  "Choose your plan": "Изберете го вашиот план",
  week: "недела",
  wk: "wk",
  "Choose plan cycle": "Изберете плански циклус",
  months: "месеци",
  years: "години",
  weeks: "Недели",
  "Copy Event Url": "Копирајте ја URL -то на настанот",
  "You can find your e-tickets attached to your email or print them":
    "Можете да ги најдете вашите е-билети прикачени на вашата е-пошта или да ги отпечатите",
  "Guest Info": "Информации за гости",
  "Ticket Info": "Информации за билети",
  "Ticket name": "Име на билет",
  "Ticket price": "Цена на билетите",
  "Ticket ID": "ID на билет",
  "If you have any questions contact to organizer":
    "Ако имате какви било прашања контактирајте го на организаторот",
  "As soon as event ends": "Штом ќе заврши настанот",
  "1 day after event ends": "1 ден по завршувањето на настанот",
  "7 days after event ends": "7 дена по завршувањето на настанот",
  "14 days after event ends": "14 дена по завршувањето на настанот",
  "30 days after event ends": "30 дена по завршувањето на настанот",
  Menu: "Мени",
  "No event for selected date": "Нема настан за избраниот датум",
  view: "преглед",
  List: "Список",
  Year: "Година",
  Yearly: "Годишно",
  "Year view header": "Заглавие на годишниот преглед",
  "Yearly Style": "Годишен стил",
  "There are no events": "Нема настани",
  Autotranslation: "Авторанслација",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Откако ќе се овозможи, вашиот додаток за календар ќе биде преведен врз основа на јазикот на веб -страницата. *Забележете дека сè додека насловот на календарот и описите се внесени текстови, тие не можат да се преведат.",
  "Note on mobile": "Белешка за мобилен телефон",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Исклучете го или променете го текстот на лентата „без настани“ на мобилната верзија на календарот",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Овозможувањето на опцијата, автоматски ќе ги отстрани вашите минати настани од календарот.",
  "This does not apply to repeating events!":
    "Ова не се однесува на повторување на настаните!",
  "Notify event creators about the guest":
    "Известете ги креаторите на настани за гостинот",
  "Send event creators notification emails as soon as guests register for their events":
    "Испратете ги е -поштата за известување за креатори на настани веднаш штом гостите се регистрираат за своите настани",
  "List View Type": "Тип на преглед на список",
  "Description font": "Опис Фонт",
  Connect: "Поврзете се",
  "You have no events": "Немате настани",
  Synchronize: "Синхронизираат",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронизација на календарот на Google ви овозможува да ги интегрирате вашите настани и сесии со вашиот календар за бум.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронизацијата на календарот Outlook ви овозможува да ги интегрирате вашите настани и сесии со вашиот календар за бум.",
  "Your message has been sent successfully!":
    "Вашата порака е испратена успешно!",
  "There are no synchronized calendars": "Нема синхронизирани календари",
  "to view more than 7 events": "да види повеќе од 7 настани",
  "Mobile app": "Мобилна апликација",
  "Admin Account": "Административна сметка",
  Password: "Лозинка",
  "Second User": "Втор корисник",
  Edit: "Уредување",
  "Guest limit": "Граница на гости",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Сите локални поставки се (автоматски) засновани на вашиот јазик. Ако вашиот јазик е на списокот, нема потреба да го прилагодите овој дел.",
  available: "достапно",
  next: "Следно",
  Tickets: "Билети",
  Quantity: "Квантитет",
  "Promo code": "Промотивен код",
  "Select a payment method": "Изберете начин на плаќање",
  Fee: "Надоместок",
  Book: "Книга",
  "All the tickets have been sold out": "Сите билети се распродадени",
  "Choose at least one ticket": "Изберете барем еден билет",
  "First choose ticket": "Прво изберете билет",
  "Please fill out your personal information.":
    "Пополнете ги вашите лични информации.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "За да направите успешна набавка, изберете го вашиот најпосакуван начин на плаќање и внесете го промо -кодот за намалени билети.",
  "Credit/Debit card": "Кредитна/дебитна картичка",
  "print here.": "Печатете овде.",
  "QR code for all tickets": "QR код за сите билети",
  Duration: "Времетраење",
  "Full Name": "Целосно име",
  "Ticket id": "ID на билет",
  "Group id": "Групна лична карта",
  "Choose your ticket.": "Изберете го вашиот билет.",
  "Fill out your personal information.":
    "Пополнете ги вашите лични информации.",
  "Add the payment details.": "Додадете ги деталите за плаќање.",
  "To be determined": "Да се ​​утврди",
  "You can find your e-tickets attached to the email or":
    "Можете да ги најдете вашите е-билети прикачени на е-поштата или",
  "print here": "Печатете овде",
  "Full name": "Целосно име",
  "Group ID": "Групна лична карта",
  "to Book": "да резервира",
  "Unfortunately, your card has been declined":
    "За жал, вашата картичка е одбиена",
  "Thank you for your purchase!": "Ви благодариме за вашето купување!",
  "Find your printable e-tickets attached to the confirmation email":
    "Пронајдете ги вашите печатени е-билети прикачени на е-поштата за потврда",
  Confirm: "Потврди",

  "Add event": "Додадете настан",
  Events: "Настани",
  "Event details": "Детали за настанот",
  Registration: "Регистрација",
  "Guests list": "Список на гости",
  Ticket: "Билет",
  "General Info": "Општи информации",
  "Customize the general settings of your event":
    "Прилагодете ги општите поставки на вашиот настан",
  "Event Title": "Наслов на настанот",
  "e.g. Birthday Party": "на пр. Роденденска забава",
  "All Day Event": "Цел ден настан",
  Cross: "Крст",
  Timeline: "Временска рамка",
  "Repeating event": "Повторувачки настан",
  Location: "Локација",
  "Venue name": "Име на место",
  Description: "Опис",
  Image: "Слика",
  Color: "Боја",
  Category: "Категорија",
  "Add your events to color categories and let your users classify them easily":
    "Додадете ги вашите настани во категориите во боја и оставете ги вашите корисници лесно да ги класифицираат",
  "Category name": "Име на категорија",
  "e.g. Birthdays": "на пр. Родендени",
  Venue: "Место",
  "Where the event takes place": "Каде се одржува настанот",
  "Venue name": "Име на место",
  "Venue phone": "Телефон на место",
  "Venue email": "Место за е -пошта",
  "Venue website": "Веб -страница на место",
  Organizer: "Организатор",
  "Person who makes the event": "Лице кое го прави настанот",
  "Organizer name": "Име на организатор",
  "Organizer phone": "Телефон на организатор",
  "Organizer email": "Организатор е -пошта",
  "Organizer website": "Организатор веб -страница",
  Save: "Зачувај",
  Cancel: "Откажи",
  Import: "Увоз",
  Past: "Минато",
  All: "Сите",
  Upcoming: "Претстојни",
  Uncategorised: "Некатегоризирано",
  "Date Ascending": "Датум на искачување",
  "Date Descending": "Датум што се спушта",
  "Title by A-Z": "Наслов на А-З",
  "Title by Z-A": "Наслов на З-А",
  "There are no events for this period": "Нема настани за овој период",

  "Auto-Convert Date & Time": "Датум и време за автоматско-конвертирање",
  TimeZone: "Временска зона",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Поставки за распоред",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Месечен заглавие за преглед",
  "Weekly/Daily view header": "Неделен/заглавие на дневен преглед",
  Acendings: "Ацеденди",
  Descending: "Опаѓачки",
  Standart: "Standart",
  Silver: "Сребро",
  Retro: "Ретро",
  Dark: "Темно",
  Night: "Ноќ",
  Aubergine: "Модар патлиџан",
  "List view header": "Заглавие на списокот со глава",
  "Side by Side View": "Рамо до рамо погледот",
  "Customize Proportions": "Прилагодете ги пропорциите",
  "Card Margins": "Маргини со карти",
  "Image opacity (%)": "Непроacирност на сликата (%)",
  "Side by Side Header": "Заглавие рамо до рамо",
  "Text Align": "Усогласен текст",
  "Timeline View": "Преглед на временска рамка",
  "Title font color": "Наслов на бојата на фонтот",
  "Desciption font color": "Боја на фонтот за отпуштање",
  "Line color": "Боја на линија",
  "Date Font color": "Датум на бојата на фонтот",
  "Daily events background": "Позадина на дневни настани",
  Alignment: "Усогласување",
  Vertical: "Вертикално",
  Horizontal: "Хоризонтална",
  "Vertical Alignment": "Вертикално усогласување",
  Right: "Десно",
  Center: "Центар",
  "Horizontal Alignment": "Хоризонтално усогласување",
  Top: "Врв",
  Center: "Центар",
  Bottom: "Дно",
  "Dates Circle Design": "Дизајн на кружни датуми",
  "Next To The Circle": "До кругот",
  "In The Circle": "Во кругот",
  "Timeline Header": "Заглавие на временската рамка",
  Timeline: "Временска рамка",
  "Show only upcoming": "Покажете само претстојно",
  "Order by": "Нарачка од",
  "Timeline Event Limit": "Ограничување на настанот на временската рамка",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Дозволете му на посетителот да додаде настан на локалните Калнедари: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Дозволете му на посетителот да го сподели вашиот настан на Facebook, LinkedIn, Twitter и др.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Додадете опција за пребарување на вашиот календар за да им овозможите на луѓето да ги пребаруваат вашите настани по наслов, место, итн.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Дозволете им на вашите корисници да го отпечатат вашиот календар за настани за бум во кој било опсег на датум.",
  "Click to apply a theme to Calendar":
    "Кликнете за да нанесете тема во календарот",
  "Date container color": "Боја на контејнери за датум",
  "Daily events background": "Позадина на дневни настани",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Користете ги додатоците за да инсталирате напредни карактеристики на вашите календари, правејќи ги пофункционални!",
  "Open Add-ons Store": "Отворена продавница за додатоци",
  Monday: "Понеделник",
  Tuesday: "вторник",
  Wednesday: "Среда",
  Thursday: "Четврток",
  Friday: "Петок",
  Saturday: "Сабота",
  Sunday: "Недела",
  "Yearly view": "Годишен поглед",
  Ascending: "Растечки",
  "Show event time next to title": "Покажи време на настанот до титулата",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Прилагодете го датумот и времето на настанот на локалното време на корисникот врз основа на нивната временска зона.",
  "Display the time zone alongside the event date.":
    "Покажете ја временската зона заедно со датумот на настанот.",
  "Show event time next to title": "Покажи време на настанот до титулата",
  "Time Zone": "Временска зона",
  "Upload Image": "Поставете слика",
  "Choose a Category": "Изберете категорија",
  "Color you have chosen will not be shown as you choose category":
    "Бојата што сте ја одбрале нема да биде прикажана како што ќе изберете категорија",
  Website: "Веб -страница",
  Next: "Следно",
  Save: "Зачувај",
  "Last Name": "Презиме",
  "Personal Info": "Лични информации",
  Back: "Назад",
  "This field is required": "Ова поле е задолжително",
  "Your event has been submitted": "Вашиот настан е доставен",
  "Enter a location": "Внесете локација",
  "Display the time zone alongside the event date.":
    "Покажете ја временската зона заедно со датумот на настанот.",
  Home: "Дома",
  "Side By Side Event Limit": "Ограничување на настанот рамо до рамо",
  "Mobille App": "Апликација Мобил",
  category: "категорија",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Следете го вашиот распоред лесно со увезување на настаните на Facebook во вашиот календар.",
  "Synchronized Pages": "Синхронизирани страници",
  "There are no synchronized pages": "Нема синхронизирани страници",
  "Choose page": "Изберете страница",
  "You have no events": "Немате настани",
  "Add Script": "Додадете скрипта",
  "script bound": "Оваа скрипта е веќе ограничена, изберете други детали!",
  "Choose account": "Изберете сметка",
  "Choose resource": "Изберете ресурс",
  "Reconnect": "Повторно поврзување",
  "script disappear": "Оваа скрипта не постои, ве молиме додадете скрипта во вашата Google Analytics!",
  "Reset Layouts Dimensions": "Ресетирајте ги димензиите на распоредот",
  "Clear": "Чиста",
  "Undo": "Вратете",
  "Redo": "Повторно",
  "Code Panel": "Код панел",
  "Code Panel Notify": "Модифицирање на кодот директно може да го сруши распоредот или функционалноста на апликацијата. Уреди само ако знаете што правите!",
  "Clear Editor": "Јасен уредник",
  "Clear Editor Notify": "Дали сте сигурни дека сакате да го исчистите уредникот? Целиот напредок ќе биде изгубен!",
  "Nothing to edit": "Нема што да се уредува!",
  "Shapes": "Форми",
  "Delete The Shape": "Избришете ја формата",
  "Add shapes": "Додадете форми помеѓу распоредот и прилагодете!",
  "Preview unavailable": "Преглед на компонентата недостапно за компонентата",
  "component removed": "компонента отстранета од уредникот.",
  "component duplicate": "Додадена компонента, белешка: дупликат влез!",
  "component added": "компонентата успешно додадена на уредникот.",
  "Component Preview": "Преглед на компонентата",
  "Height": "Висина",
  "Font Family": "Семејство на фонт",
  "Select Font": "Изберете фонт",
  "Font Weight": "Тежина на фонт",
  "Font Size": "Големина на фонтот",
  "Text Alignment": "Усогласување на текст",
  "Left Alignment": "Лево усогласување",
  "Center Alignment": "Усогласување на центарот",
  "Right Alignment": "Право усогласување",
  "Text Decoration": "Декорација на текст",
  "Overline": "Преклопени",
  "Line Through": "Линија низ",
  "Underline": "Подвлечете",
  "Underline and Overline": "Потенцирајте и преклопете",
  "Without Decoration": "Без декорација",
  "Left": "Лево",
  "Angle": "Агол",
  "Distance": "Растојание",
  "Blur": "Замаглување",
  "Size": "Големина",
  "Edit individually": "Уреди индивидуално",
  "Apply to all corners": "Се применуваат на сите агли",
  "Date Box Visual": "Визуелна кутија за датум",
  "One Line": "Една линија",
  "Show Icons": "Покажете икони",
  "Design Settings": "Поставки за дизајн",
  "Personalize your editor to match your style and preferences, customize every detail in this settings tab !": "Персонализирајте го вашиот уредник да одговара на вашиот стил и преференции, прилагодете ги сите детали во табулаторот за поставки!",
  "Divider": "Делител",
  "Ellipse": "Елипса",
  "Rhombus": "Ромб",
  "Heart": "Срце",
  "Hexagon": "Шестоаголник",
  "Circle": "Круг",
  "Rectangle": "Правоаголник",
  "Square": "Плоштад",
  "Triangle": "Триаголник",
  "Star": "Starвезда",
};
export default mk;
