let no = {
  "Payable with a plan": "Betales med en plan",
  "Service Details": "Tjenestedetaljer",
  "participants": "deltakere",
  "To": "Til",
  "From": "Fra",
  "Ahead": "Foran",
  "Ago": "siden",
  "Change the category": "Endre kategori",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Ticket Tailor-synkronisering lar deg integrere arrangementene og øktene dine med Boom-kalenderen.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Vis hendelsestid ved siden av tittelen. Denne innstillingen gjelder bare for månedlig, daglig og ukentlig visning.",
  "Show Staff Member": "Vis medarbeider",
  "Show Price": "Vis pris",
  "To Event Page": "Til hendelsessiden",
  "Layout": "Oppsett",
  "Acending": "Acending",
  "Yearly": "Årlig",
  "Layout device": "Layoutenhet",
  "Date container font": "Datobeholderskrift",
  "Hide Fully Booked Slots": "Skjul fullbookede spilleautomater",
  Enable: "Muliggjøre",
  Limit: "Grense",
  Export: "Eksport",
  "You are about to change the details of your event. Once changed, your guest list will be lost.":
    "Du er i ferd med å endre detaljene for arrangementet ditt. Når den er endret, vil gjestelisten din gå tapt.",
  "Change Date": "Endre dato",
  Ends: "Slutter",
  On: "På",
  After: "Etter",
  Accept: "Aksepterer",
  "Show less": "Vis mindre",
  "Venue detail": "Stedsdetalj",
  Reject: "Avvis",
  "See guest list": "Se gjesteliste",
  "Submit Date": "Innsendingsdato",
  "Total guests": "Totalt gjester",
  "Do you really want to delete selected user? Once removed, cannot be undone.":
    "Vil du virkelig slette valgt bruker? Når den er fjernet, kan den ikke angres.",
  "Delete Guest": "Slett gjest",
  "Invoice number": "Fakturanummer",
  Status: "Status",
  "Payment type": "Betalings type",
  "Select payment method to receive fees through tickets":
    "Velg betalingsmetode for å motta gebyrer via billetter",
  "Add Code": "Legg til kode",
  "Add End Time": "Legg til sluttid",
  Discount: "Rabatt",
  "Promo codes for the sales": "Kampanjekoder for salget",
  "Promo codes": "Kampanjekoder",
  "Add Ticket": "Legg til billett",
  "Limit type": "Begrens type",
  Paid: "Betalt",
  "Participation tickets for your event":
    "Deltakerbilletter til ditt arrangement",
  "Show the ticket limit": "Vis billettgrensen",
  "Show limit": "Vis grense",
  "Show the price on ticket": "Vis pris på billetten",
  "Enable and configure your ticketing system":
    "Aktiver og konfigurer billettsystemet ditt",
  "Stop repeating here": "Slutt å gjenta her",
  Limited: "Begrenset",
  Unlimited: "Ubegrenset",
  "Thank you message title": "Takk meldingstittel",
  "Submit button text": "Send inn knapptekst",
  "Registration button text": "Tekst på registreringsknapp",
  Texts: "Tekster",
  "Modify the displayed texts": "Endre de viste tekstene",
  "Thank you message body": "Takk meldingsteksten",
  "Notify the user when the registration is canceled":
    "Varsle brukeren når registreringen er kansellert",
  "Cancellation email": "Avbestillings-e-post",
  "Send a reminder to the user one day prior to the event":
    "Send en påminnelse til brukeren en dag før arrangementet",
  "Reminder email": "Påminnelse på e-post",
  "Send an instant email to the user once registration is completed":
    "Send en umiddelbar e-post til brukeren når registreringen er fullført",
  "Notification email": "E-postvarsel",
  "Reminder email about the event": "E-postpåminnelse om arrangementet",
  "Email notifications to users": "E-postvarsler til brukere",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).":
    "Klikk på veksleknappene ved siden av hvert felt for å legge det til i registreringsskjemaet. Hvis du vil gjøre feltet obligatorisk, klikk på stjernen (*).",
  "Form Fields": "Skjemafelt",
  "Enter your form description": "Skriv inn skjemabeskrivelsen",
  "Form Title": "Skjematittel",
  "Enter your form title": "Skriv inn skjematittelen",
  "Form Details": "Skjemadetaljer",
  "Configure your registration form fields":
    "Konfigurer registreringsskjemafeltene dine",
  "Show guest limit": "Vis gjestegrense",
  "Enable Registration": "Aktiver registrering",
  "Click to activate registration on this event":
    "Klikk for å aktivere registrering på dette arrangementet",
  "Customize the general settings of registration":
    "Tilpass de generelle innstillingene for registrering",
  "Enter URL": "Skriv inn URL",
  "Page URL": "Side URL",
  "Close registration when the event starts":
    "Lukk påmeldingen når arrangementet starter",
  "Redirect to a different website": "Omdirigere til et annet nettsted",
  "Where users can register": "Hvor brukere kan registrere seg",
  "Open event registration landing page":
    "Åpne landingssiden for eventregistrering",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.":
    "Det må ha tatt deg mye forberedelse for å gjøre deg klar til arrangementet ditt. Nå er det på tide å lene seg tilbake og slappe av til gjestene dine samles rundt! Så snart en ny registrering er gjort, vil informasjonen om din gjest vises her. Kom tilbake senere for å holde oversikt over deltakerne på arrangementet.",
  "You have no guests at the moment.": "Du har ingen gjester for øyeblikket.",
  "List of people who are registered to your event":
    "Liste over personer som er registrert på arrangementet ditt",
  "Guest List": "Gjesteliste",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.":
    "Dette er en gjenganger! Eventuelle endringer som gjøres på dette arrangementet, vil bli brukt på alle repetisjoner.",
  "Repeated event": "Gjentatt hendelse",
  "Delete Category": "Slett kategori",
  "Do you really want to delete selected category? Once removed, cannot be undone.":
    "Vil du virkelig slette valgt kategori? Når den er fjernet, kan den ikke angres.",
  OK: "OK",
  Exclude: "Utelukke",
  "Custom recurrence": "Tilpasset gjentakelse",
  Duplicate: "Duplisere",
  Delete: "Slett",
  Published: "Publisert",
  Drafts: "Utkast",
  "User events": "Brukerhendelser",
  "Add new category": "Legg til ny kategori",
  "Manage categories": "Administrer kategorier",
  "Add category": "Legg til kategori",
  Never: "Aldri",
  "Repeat every": "Gjenta hver",
  "Do you really want to delete selected event? Once removed, cannot be undone":
    "Vil du virkelig slette den valgte hendelsen? Når den er fjernet, kan den ikke angres",
  "There are no categories yet": "Det er ingen kategorier ennå",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.":
    "Gjør endringer i din synkroniserte kalender med følgende koblinger. Se nøye gjennom endringene.",
  occurrences: "hendelser",
  "Save as draft": "Lagre som kladd",
  "More Info": "Mer informasjon",
  "Book Now": "Bestill nå",
  "Show participants": "Vis deltakere",
  "This service is fully booked.": "Denne tjenesten er fullbooket.",
  "All sessions are fully booked.": "Alle økter er fullbooket.",
  "Registration closed": "Registreringen ble avsluttet",
  "Show your Wix Bookings or Events on Calendar":
    "Vis Wix -bestillinger eller arrangementer i kalenderen",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.":
    "Velg Auto for automatisk visning av alle tjenester og økter på kalenderen, eller manuell for manuelt valg.",
  "Show cancelled events": "Vis kansellerte hendelser",
  "Event Color": "Hendelsesfarge",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.":
    "Velg Auto for automatisk visning av alle hendelser i kalenderen, eller manuell for manuelt valg.",
  Auto: "Bil",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.":
    "Velg Auto for automatisk visning av alle organisasjoner og arrangører i kalenderen, eller manuell for manuelt valg.",
  Manual: "Håndbok",
  "Sync method": "Synkroniseringsmetode",
  "Enable synchronization": "Aktiver synkronisering",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only":
    "Vis frem kategorifilteret øverst eller nederst i kalenderen. Innstillingene gjelder kun agenda, kryss, tidslinje og kortvisning",
  "Load Events": "Last inn hendelser",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.":
    "Når den er aktivert, vil kalenderwidgeten bli oversatt basert på nettstedets språk. Vær oppmerksom på at så lenge kalendertitler og beskrivelser legges inn som tekst, kan de ikke oversettes.",
  "Choose plan type": "Velg plantype",
  "Api key": "API -nøkkel",
  "Synchronized Boxes": "Synkroniserte bokser",
  "Choose box": "Velg boks",
  "There are no synchronized boxes": "Det er ingen synkroniserte bokser",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Ticket Tailor Sync lar deg integrere hendelsene og øktene dine med din bomkalender",
  Categories: "Kategorier",
  "Share this event": "Del dette arrangementet",
  Language: "Språk",
  "Show Time Zone": "Vis tidssone",
  "Custom Local Settings": "Tilpassede lokale innstillinger",
  "Add and showcase events on your site using a beautiful calendar.":
    "Legg til og vis hendelser på nettstedet ditt ved hjelp av en vakker kalender . ",
  "Week Days": "Ukedager",
  "Manage Events": "Administrer hendelser",
  General: "Generell",
  "Layout Picker": "Oppsettvelger",
  Month: "Måned",
  Monthly: "Månedlig",
  Week: "Uke",
  Weekly: "Ukentlig",
  Day: "Dag",
  Daily: "Daglig",
  Agenda: "Dagsorden",
  "Navigation Buttons": "Navigasjonsknapper",
  "Week numbers": "Ukenummer",
  "Include Weekends": "Inkluder helger",
  "All-day": "Hele dagen",
  "All Day": "Hele dagen",
  Label: "Merkelapp",
  "Fit to Height": "Fit to Height",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Slik angir du app-proporsjoner manuelt deaktiverer dette alternativet og endrer størrelse på kalender i Editor. ",
  "Default Layout": "Standardoppsett",
  "Monthly view": "Månedsvisning",
  "Weekly and Daily view": "Ukentlig og daglig visning",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Du kan gi besøkende en mer konsistent opplevelse ved å vise samme antall uker ( 6) om gangen.",
  "Fixed Weekly Layout": "Fast ukesoppsett",
  back: " tilbake ",
  Row: "Rad",
  "Hours in Weekly View": "Timer i ukesvisning",
  "Hours in Daily View": "Timer i daglig visning",
  Start: "Start",
  End: "Slutt",
  "At This Hour": "På denne timen",
  Button: "Knapp",
  Buttons: "Knapper",
  Sunday: "Søndag",
  Monday: "Mandag",
  Tuesday: "Tirsdag",
  Wednesday: "Onsdag",
  Thursday: " Torsdag ",
  Friday: "Fredag",
  Saturday: "Lørdag",
  "Default Date": "Standard dato",
  year: " år ",
  month: " måned ",
  mo: " måned ",
  days: " dager ",
  ago: " siden ",
  ahead: " fremover ",
  Yesterday: "I går",
  Today: "I dag",
  Tomorrow: "I morgen",
  Custom: "Tilpasset",
  "Set Daily Rows Limit": "Angi grense for daglige rader",
  "Set Proportions": "Angi proporsjoner",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Tillat besøkende å legge til hendelser i lokale kalendere , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Container",
  Background: "Bakgrunn",
  "Container Background": "Beholder bakgrunn",
  "Container Borders": "Beholdergrenser",
  Calendar: "Kalender",
  "Event Info Tooltip": "Verktøytips for hendelsesinfo",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Når folk svever over et arrangement, vil de se all informasjonen om det i en verktøytips. ",
  "Event Info Window": "Vinduet med hendelsesinfo",
  "This is the full information window that opens when someone clicks on the event.":
    "Dette er det fullstendige informasjonsvinduet som åpnes når noen klikker på hendelsen. ",
  "Use Gradient": "Bruk gradient",
  Vertical: "Vertical",
  Horizontal: "Horisontal",
  First: "Først",
  Second: "Sekund",
  diagonal: " diagonal ",
  Radial: "Radial",
  "Select option": "Velg alternativ",
  Solid: "Fast",
  Dotted: "Prikket",
  Dashed: "Stiplet",
  Double: "Dobbelt",
  "Border Radius": "Border Radius",
  Padding: "Padding",
  "Date Header": "Datohode",
  "Event Default Color": "Standardfarge på arrangement",
  "Days of Week": "Dager i uken",
  "Days of Week Background": "Days of Week bakgrunn",
  Date: "Dato",
  "Event Title": "Event title",
  "Highlight today": "Uthev i dag",
  "Highlight Color": "Uthev farge",
  Hide: "Gjemme seg",
  "Calendar Border Color": "Kalenderramme farge",
  "Calendar Border Width": "Kalendergrensebredde",
  "Calendar Border Style": "Kalendergrensestil",
  "Font Color": "Skriftfarge",
  "Event Background": "Hendelsesbakgrunn",
  "Card Date Color": "Farge på kortdato",
  "Title Font": "Tittelfont",
  "Date Font": "Datoskrift",
  "Description Font": "Beskrivelse Font",
  "Button Background": "Knappbakgrunn",
  "Button Text": "Knapptekst",
  "Border Color": "Grensefarge",
  "Border Width": "Border Width",
  "Border Type": "Grensetype",
  Title: "Tittel",
  Description: "Beskrivelse",
  "Background Color": "Bakgrunnsfarge",
  Divider: "Deler",
  "Event Details Font": "Fontdetaljer for hendelsesdetaljer",
  "Website Link Color": "Nettstedslinkfarge",
  "Developer Info": "Utviklerinfo",
  "User Guide": "Brukerhåndboken",
  "Support e-mail": "Støtte e-post",
  "Our Website": "Vår nettside",
  "App Review": "Appanmeldelse",
  "Enjoying App? Leave us a review in the App Market.":
    "Nyter appen? Gi oss en anmeldelse i appmarkedet. ",
  "Review Us": "Gjennomgå oss",
  "Connect With Us": "Koble til oss",
  "What's your email?": "Hva er e-postmeldingen din? ",
  "Invalid email address!": "Ugyldig e-postadresse! ",
  Comments: "Kommentarer",
  "We'd love to hear from you. Send us a message.":
    "Vi vil gjerne høre fra deg. Send oss ​​en melding. ",
  "Message must be at least 5 characters long":
    "Meldingen må være minst 5 tegn lang",
  Send: "Sende",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Hvis du vil la brukeren bytte mellom kalendervisninger, aktiverer du dette alternativet og velger visningene du vil vise. ",
  Main: "Hoved",
  Localize: "Lokal",
  Settings: "innstillinger",
  Layouts: "oppsett",
  Advanced: "Avansert",
  Design: "Design",
  Support: "Brukerstøtte",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Alle lokale innstillinger er (automatisk) basert på språket ditt. Hvis språket ditt er på listen, er det ikke nødvendig å tilpasse denne delen.",
  "Date Format": "Datoformat",
  "Time Format": "Tidsformat",
  "Text Direction": "Tekstretning",
  "Left to Right": "Venstre til høyre",
  "Right to Left": "Høyre til venstre",
  "Week Starts On": "Uken starter",
  "Agenda Style": "Agenda stil",
  Classic: "Klassisk",
  Modern: "Moderne",
  "Agenda Header": "Overskrift for agenda",
  "Upcoming Events": "Kommende arrangementer",
  "Agenda Event Limit": "Agenda begivenhetsgrense",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Oppgrader nå og få mange flere funksjoner og nyt appen din i sin helhet!",
  "Upgrade Now": "Oppgrader nå",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting av arrangementer som varer hele dagen? Dette lar deg vise dem i kalenderen din.",
  "24 hours": "24 timer",
  Sun: "Søn",
  Mon: "Man",
  Sat: "Lør",
  Default: "Misligholde",
  "Select custom design style for your calendar.":
    "Velg tilpasset designstil for kalenderen.",
  Style: "Stil",
  "Styles and Colors": "Stiler og farger",
  "Calendar Name": "Kalendernavn",
  "Write your Calendar name here": "Skriv kalendernavnet ditt her",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Dette er ikke synlig for brukerne dine. Angi navn for å differensiere kalenderne dine når du bruker Boom Calendar Sync-funksjonen.",
  "General Info": "Generell info",
  Venue: "spillested",
  Organizer: "Planlegger",
  Search: "Søk",
  "Add to": "Legge til",
  calendar: "kalender",
  "Copy event URL": "Kopier URL-adresse",
  "Copied!": "Kopiert!",
  "Add & Share": "Legg til og del",
  Map: "Kart",
  "Calendar view": "Kalenderweergave",
  "Add Event": "Voeg evenement toe",
  Uncategorised: "Ukategorisert",
  More: "Mer",
  Less: "Mindre",
  Register: "Registrere",
  Card: "Kaart",
  Guests: "Gjestene",
  unlimited: "ubegrenset",
  "Show more": "Vis mer",
  "Enable Search": "Aktiver søk",
  "+ Add Event": "+ Legg til hendelseAdministrer og synkroniser",
  "Manage and Sync": "Administrer og synkroniser",
  "Show event details as...": "Vis hendelsesdetaljer som ...",
  Tooltip: "tooltip",
  Popup: "Info-boksen",
  None: "Ingen",
  "Show Category": "Vis kategori",
  "Header Align": "Topplinje Juster",
  "Show Time": "Vis tid",
  "Hours in Weekly/Daily View": "Timer i ukevis / daglig visning",
  "Share Events": "Del hendelser",
  Shadow: "skygge",
  "Inner Padding": "Indre polstring",
  Text: "Tekst",
  "Active Button Border": "Aktiv knappekant",
  "Light Mode": "Lysmodus",
  "Event Text Color": "Farge på hendelsestekst",
  Dates: "datoer",
  Skeleton: "Skjelett",
  "Skeleton Color": "Skjelettfarge",
  Width: "Bredde",
  "Skeleton Style": "Skjelettstil",
  Color: "Farge",
  "Section Titles": "Seksjonstitler",
  "Section Content": "Seksjonens innhold",
  Header: "Overskrift",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Sølv",
  Night: "Natt",
  Dark: "Mørk",
  Aubergine: "Aubergine",
  "Map Header": "Karthode",
  "Show Title in mobile": "Vis tittel på mobil",
  "Card View": "Kaartweergave",
  "Card background color": "Achtergrondkleur van de kaart",
  "Title font": "Titel lettertype",
  "Desciption font": "Beschrijving lettertype",
  "Section font": "Lettertype sectie",
  "Section divider color": "Kleur sectiescherm",
  "Add event": "Legg til hendelse",
  "All Day Event": "Heldags hendelse",
  Location: "Plassering",
  "Choose a category": "Velg en kategori",
  "Venue name": "Stedets navn",
  "Venue phone": "Lokaltelefon",
  "Venue email": "E-poststed",
  "Venue website": "Stedets nettsted",
  "Organizer name": "Arrangørens navn",
  "Organizer phone": "Organiser-telefon",
  "Organizer email": "Organiser-e-post",
  "Organizer website": "Arrangørens nettsted",
  "Personal info": "Personlig informasjon",
  "First name": "Fornavn",
  "Last name": "Etternavn",
  "Email Address": "Epostadresse",
  "Additional Notes": "Tilleggsmerknader",
  Back: "Tilbake",
  Save: "Lagre",
  Next: "Neste",
  "Your event has been submitted": "Arrangementet ditt er sendt inn",
  "Event submittion has been failed": "Innlevering av hendelse mislyktes",
  "e.g. Birthday Party": "f.eks. Bursdagsfest",
  "First Name": "Voornaam",
  "Last Name": "Etternavn",
  "Phone Number": "Telefonnummer",
  Address: "Adresse",
  "Your comments": "Dine kommentarer",
  "How many guests?": "Hvor mange gjester?",
  "Anything else we need to know?": "Is er nog iets dat we moeten weten?",
  "Guests:": "Gasten:",
  Submit: "Verzenden",
  "Go to Calendar": "Gå til Kalender",
  "Registration completed successfully!": "Registreringen fullført!",
  "Please check your registered email address":
    "Controleer uw geregistreerde e-mailadres",
  "Add to Calendar": "Legg til i kalenderen",
  "Share this Event": "Del denne hendelsen",
  "Sorry something went wrong": "Beklager, noe gikk galt",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Dato og beliggenhet",
  "Date & Time": "Dato tid",
  home: "hjem",
  "Header align": "Hodejustering",
  Footer: "Bunntekst",
  "Categories Filter": "kategorier Filter",
  "Show only upcoming": "Vis bare kommende",
  "Card(s) in a row": "Kort (er) på rad",
  "Space between cards": "Plass mellom kort",
  "Shown events limit": "Viste begivenhetsgrenser",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Stil 4.",
  "Buttons & Links": "Knapper og lenker",
  "Button corner radius": "Knapp hjørneradius",
  "Buttons font": "Knapper font",
  "Buttons background": "Knapper bakgrunn",
  "Get notified by Email": "Bli varslet via e-post",
  "Review events": "Gjennomgå hendelser",
  "Click on date": "Klikk på dato",
  "Add Event button": "Legg til hendelsesknapp",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Kalendersynkronisering lar deg integrere hendelser og økter med Boom-kalenderen.",
  connect: "koble",
  "Synchronized Calendars": "Synkroniserte kalendere",
  "Import events": "Importer hendelser",
  Disconnect: "Koble fra",
  "Choose calendar": "Velg Kalender",
  "Monitor your Wix events through the sync feature":
    "Overvåke Wix-hendelsene dine gjennom synkroniseringsfunksjonen",
  "Connect all your Boom calendars available on your website":
    "Koble til alle dine Boom-kalendere som er tilgjengelige på nettstedet ditt",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Planlegg, bli med, og administrer zoommøter rett gjennom vår boomkalender.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Overvåk Event Brite-hendelsene dine gjennom Event Brite-synkroniseringsfunksjonen",
  Email: "E-post",
  "Add-ons": "Tillegg",
  "Receive notification emails as soon as users add events to your calendar.":
    "Motta varslingsmeldinger så snart brukerne legger til hendelser i kalenderen din.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Godta eller avslå hendelser lagt til av kunder før de gjør dem offentlige.",
  "Switch Add Event": "Bytt Legg til arrangement",
  "Enable your browser cookies to connect to your account.":
    "Aktiver nettleserkakene dine for å koble til kontoen din.",
  "Learn more": "Lære mer",
  "Print Button": "Wydrukuj przycisk",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Tillat brukerne å skrive ut Boom Event-kalenderen i et hvilket som helst datoport.",
  "Show Title on mobile": "Vis tittel på mobil",
  "Show Skeleton on mobile": "Vis skjelett på mobilen",
  "Start 7-day Business trial": "Start din 7-dagers forretningsprøve",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Nyt alle ubegrensede funksjoner, for eksempel selger billetter, registrering, tilleggsavsetninger.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Vennligst merk: Ved slutten av prøveperioden vil du bli returnert til din eksisterende abonnementsplan.",
  "Not Now": "Ikke nå",
  "Start free trial": "Start gratis prøveperiode",
  "Congrats!": "Gratulerer!",
  "Your 7-day Business trial has been successfully activated.":
    "Din 7-dagers forretningsprøve har blitt aktivert.",
  Done: "Gjort",
  "Title font color": "Tittel Font Color.",
  "Desciption font color": "Beskrivelse Font Color.",
  "Section font color": "Seksjonsfont Color.",
  "Card Header": "Kort header.",
  Category: "Kategori",
  "Display at the": "Vis på det",
  top: "topp",
  bottom: "bunn",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Vis at kategorifilteret øverst eller nederst på kalenderen.Innstillingene gjelder bare for agenda- og kortvisninger",
  "Processing your events": "Behandler hendelsene dine",
  "Search for events": "Søk etter arrangementer",
  "There are no events added": "Det er ingen hendelser lagt til",
  "Location: To be determined": "Sted: For å bli bestemt",
  "No events for selected date": "Ingen hendelser for valgt dato",
  Uncategorized: "Ukategorisert",
  "Edit event": "Rediger hendelse",
  "Edit original event": "Rediger original hendelse",
  "Copy event": "Kopi -arrangement",
  "Copy as new event": "Kopier som ny begivenhet",
  "Delete event": "Slett hendelse",
  "Stop repeating on this date": "Slutt å gjenta på denne datoen",
  "Exclude this date": "Ekskluder denne datoen",
  "Location is going to be announced":
    "Plasseringen kommer til å bli kunngjort",
  "Fill your personal information": "Fyll din personlige informasjon",
  "Check Box": "Avkrysningsrute",
  "Single Choice": "Enkelt valg",
  Option: "Alternativ",
  "Share Event": "Aksjearrangement",
  "Oops! Something went wrong": "Ups!Noe gikk galt",
  "We are sorry this event has already taken place":
    "Vi beklager at denne hendelsen har allerede funnet sted",
  "Back to calendar": "Tilbake til kalenderen",
  "This field is required": "Dette feltet er obligatorisk",
  Phone: "Telefon",
  "Number field": "Nummerfelt",
  "Please provide a valid email": "Vennligst oppgi en gyldig e -post",
  "Select at least one option": "Velg minst ett alternativ",
  "Choose tickets to see total value": "Velg billetter for å se total verdi",
  tickets: "billetter",
  "Choose Tickets": "Velg billetter",
  "Choose payment method": "Velge betalingsmetode",
  Pay: "Betale",
  Total: "Total",
  Free: "Gratis",
  "Buy tickets": "Kjøpe billetter",
  "Sold Out": "Utsolgt",
  "Tickets are available": "Billetter er tilgjengelige",
  "Sales End": "Salgsslutt",
  "Availible from": "Tilgjengelig fra",
  "Go to Orders": "Gå til bestillinger",
  "Go to Details": "Gå til detaljer",
  "Group ticket": "Gruppebillett",
  Name: "Navn",
  Price: "Pris",
  "Order by": "Rekkefølge etter",
  "Order ID": "Bestillings ID",
  Applied: "Anvendt",
  Fees: "Gebyrer",
  "Enter promo code": "Skriv inn kampanjekode",
  Apply: "Søke om",
  "Promo Code": "Rabattkode",
  Cash: "Penger",
  "You can find your e-tickets attached to your email or download them":
    "Du kan finne e-billedtene dine som er knyttet til e-posten din eller last ned dem",
  here: "her",
  Time: "Tid",
  "Invalid promo code": "Ugyldig kampanjekode",
  "Credit card": "Kredittkort",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Du vil snart motta en bekreftelsesmelding om vellykket registrering på e -postadressen din.",
  "You can also check your order details below.":
    "Du kan også sjekke bestillingsdetaljene dine nedenfor.",
  at: "på",
  Buy: "Kjøpe",
  Donation: "Donasjon",
  "Enter price": "Bedriften",
  Choose: "Velge",
  Chosen: "Valgt ut",
  "Choose your plan": "Velg planen din",
  week: "uke",
  wk: "uke",
  "Choose plan cycle": "Velg Plan -syklus",
  months: "måneder",
  years: "år",
  weeks: "uker",
  "Copy Event Url": "Kopier hendelses url",
  "You can find your e-tickets attached to your email or print them":
    "Du kan finne e-billedene dine som er knyttet til e-posten din eller skrive dem ut",
  "Guest Info": "Gjesteinfo",
  "Ticket Info": "Billettinfo",
  "Ticket name": "Billettnavn",
  "Ticket price": "Billettpris",
  "Ticket ID": "Billett -id",
  "If you have any questions contact to organizer":
    "Hvis du har spørsmål, kontakt til arrangør",
  "As soon as event ends": "Så snart hendelsen slutter",
  "1 day after event ends": "1 dag etter at hendelsen slutter",
  "7 days after event ends": "7 dager etter at hendelsen slutter",
  "14 days after event ends": "14 dager etter at hendelsen slutter",
  "30 days after event ends": "30 dager etter at hendelsen er slutt",
  Menu: "Meny",
  "No event for selected date": "Ingen hendelse for valgt dato",
  view: "utsikt",
  List: "Liste",
  Year: "År",
  "Yearly Style": "Årlig stil",
  "There are no events": "Det er ingen hendelser",
  Autotranslation: "Autotranslation.",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Når det er aktivert, vil kalenderens widget bli oversatt basert på nettstedets språk.* Merk at så lenge kalendertittel, og beskrivelser blir lagt inn tekster, kan de ikke oversettes.",
  "Note on mobile": "Merk på Mobile.",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Slå av eller endre teksten til 'No Events' -linjen på mobilversjonen av kalenderen",
  Autodeletion: "Autosletting",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Aktivering av alternativet, vil automatisk fjerne dine tidligere hendelser fra kalenderen.",
  "This does not apply to repeating events!":
    "Dette gjelder ikke for gjentatte hendelser!",
  "Notify event creators about the guest": "Varsle brukere om gjesten",
  "Send event creators notification emails as soon as guests register for their events":
    "Send e-postmeldinger om arrangementskapere så snart gjestene registrerer seg for arrangementene sine",
  "List View Type": "Listevisningstype",
  Yearly: "Årlig",
  "Year view header": "År visningshode",
  "Description font": "Beschrijving lettertype",
  Connect: "koble",
  "You have no events": "Du har ingen arrangementer",
  Synchronize: "Synkroniser",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Google Calendar Sync lar deg integrere hendelsene og øktene med bomkekalenderen din.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synkronisering av Outlook-kalenderen lar deg integrere hendelser og økter med Boom-kalenderen.",
  "Your message has been sent successfully!": "Din melding har blitt sendt!",
  "There are no synchronized calendars": "Det er ingen synkroniserte kalendere",
  "to view more than 7 events": "For å se mer enn 7 hendelser",
  "Mobile app": "Mobilapp",
  "Admin Account": "Adminkonto",
  Password: "Passord",
  "Second User": "Andre bruker",
  Edit: "Redigere",
  "Guest limit": "Gjestegrense",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Alle de lokale innstillingene er (automatisk) basert på ditt språk.Hvis språket ditt er på listen, er det ikke nødvendig å tilpasse denne delen.",
  available: "tilgjengelig",
  next: "NESTE",
  Tickets: "Billetter",
  Quantity: "Mengde",
  "Promo code": "Rabattkode",
  "Select a payment method": "Velg en betalingsmetode",
  Fee: "Avgift",
  Book: "Bok",
  "All the tickets have been sold out": "Alle billettene er utsolgt",
  "Choose at least one ticket": "Velg minst en billett",
  "First choose ticket": "Velg først billett",
  "Please fill out your personal information.":
    "Vennligst fyll ut dine personlige opplysninger.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "For å gjøre et vellykket kjøp, velg ønsket betalingsmetode og skriv inn kampanjekoden for rabatterte billetter.",
  "Credit/Debit card": "Kreditt- / debetkort",
  "You can find your e-tickets attached to the email or":
    "Du kan finne dine e-billetter knyttet til e-posten eller",
  "print here.": "Skriv ut her.",
  "QR code for all tickets": "QR-kode for alle billetter",
  Duration: "Varighet",
  "Full Name": "Fullt navn",
  "Ticket id": "Billett-ID.",
  "Group id": "Gruppe ID.",
  "Choose your ticket.": "Velg din billett.",
  "Fill out your personal information.":
    "Fyll ut dine personlige opplysninger.",
  "Add the payment details.": "Legg til betalingsdetaljene.",
  "To be determined": "Å være bestemt",
  "print here": "Skriv ut her",
  "Full name": "Fullt navn",
  "Group ID": "Gruppe ID.",
  "to Book": "å bestille",
  "Unfortunately, your card has been declined":
    "Dessverre har kortet ditt blitt avslått",
  "Thank you for your purchase!": "Takk for kjøpet!",
  "Find your printable e-tickets attached to the confirmation email":
    "Finn dine utskrivbare e-billetter som er knyttet til bekreftelses-e-posten",
  Confirm: "Bekrefte",

  "Add event": "Legg til arrangement",
  Events: "arrangementer",
  "Event details": "Hendelsesdetaljer",
  Registration: "Registrering",
  "Guests list": "Gjesterliste",
  Ticket: "Billett",
  "General Info": "Generell info",
  "Customize the general settings of your event":
    "Tilpass de generelle innstillingene for arrangementet ditt",
  "Event Title": "Arrangementstittel",
  "e.g. Birthday Party": "f.eks. Bursdagsfest",
  "All Day Event": "Heldags hendelse",
  Cross: "Kryss",
  Timeline: "Tidslinje",
  "Repeating event": "Gjenta arrangementet",
  Location: "plassering",
  "Venue name": "Stednavn",
  Description: "Beskrivelse",
  Image: "Bilde",
  Color: "Farge",
  Category: "Kategori",
  "Add your events to color categories and let your users classify them easily":
    "Legg til hendelsene dine i fargekategorier og la brukerne klassifisere dem enkelt",
  "Category name": "Kategori navn",
  "e.g. Birthdays": "f.eks. Bursdager",
  Venue: "Sted",
  "Where the event takes place": "Hvor arrangementet finner sted",
  "Venue name": "Stednavn",
  "Venue phone": "Stedstelefon",
  "Venue email": "Steds -e -post",
  "Venue website": "Venestednettsted",
  Organizer: "Arrangør",
  "Person who makes the event": "Person som gjør arrangementet",
  "Organizer name": "Arrangørnavn",
  "Organizer phone": "Arrangørstelefon",
  "Organizer email": "Arrangør -e -post",
  "Organizer website": "Arrangørens nettsted",
  Save: "Lagre",
  Cancel: "Avbryt",
  Import: "Import",
  Past: "Forbi",
  All: "Alle",
  Upcoming: "Kommende",
  Uncategorised: "Ukategorisert",
  "Date Ascending": "Dato stigende",
  "Date Descending": "Dato synkende",
  "Title by A-Z": "Tittel av A-Z",
  "Title by Z-A": "Tittel av Z-A",
  "There are no events for this period":
    "Det er ingen hendelser for denne perioden",
  "Auto-Convert Date & Time": "Automatisk konvertering av dato og klokkeslett",
  TimeZone: "Tidssone",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Oppsettingsinnstillinger",
  "Yeatly view": "Yeatly visning",
  "Monthly view header": "Månedlig visningsoverskrift",
  "Weekly/Daily view header": "Ukentlig/daglig visningsoverskrift",
  Acendings: "Acendings",
  Descending: "Synkende",
  Standart: "Standart",
  Silver: "Sølv",
  Retro: "Retro",
  Dark: "Mørk",
  Night: "Natt",
  Aubergine: "Aubergine",
  "List view header": "Listevisitthode",
  "Side by Side View": "Side om side",
  "Customize Proportions": "Tilpasse proporsjoner",
  "Card Margins": "Kortmarginer",
  "Image opacity (%)": "Image Opacity (%)",
  "Side by Side Header": "Side om sidehode",
  "Text Align": "Tekst justert",
  "Timeline View": "Tidslinjevisning",
  "Title font color": "Tittelfontfarge",
  "Desciption font color": "Desciption fontfarge",
  "Line color": "Linjefarge",
  "Date Font color": "Dato fontfarge",
  "Daily events background": "Daglige hendelser bakgrunn",
  Alignment: "Justering",
  Vertical: "Vertikal",
  Horizontal: "Horisontal",
  "Vertical Alignment": "Vertikal justering",
  Right: "Ikke sant",
  Center: "Senter",
  "Horizontal Alignment": "Horisontal innretting",
  Top: "Topp",
  Center: "Senter",
  Bottom: "Bunn",
  "Dates Circle Design": "Datoer sirkeldesign",
  "Next To The Circle": "Ved siden av sirkelen",
  "In The Circle": "I sirkelen",
  "Timeline Header": "Tidslinjeoverskrift",
  Timeline: "Tidslinje",
  "Show only upcoming": "Vis bare kommende",
  "Order by": "Rekkefølge etter",
  "Timeline Event Limit": "Tidslinje hendelsesgrense",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "La besøkende legge til arrangement til lokale Calnedars: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "La besøkende dele arrangementet ditt til Facebook, LinkedIn, Twitter og etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Legg til et søkealternativ i kalenderen din for å la folk søke på hendelsene dine etter tittel, sted osv.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Tillat brukerne dine å skrive ut boom -hendelseskalenderen i et hvilket som helst datoområde.",
  "Click to apply a theme to Calendar":
    "Klikk for å bruke et tema på kalenderen",
  "Date container color": "Dato containerfarge",
  "Daily events background": "Daglige hendelser bakgrunn",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Bruk tilleggene til å installere avanserte funksjoner på kalenderne dine, og gjør dem mer funksjonelle!",
  "Open Add-ons Store": "Åpne tilleggsbutikk",
  Monday: "mandag",
  Tuesday: "tirsdag",
  Wednesday: "onsdag",
  Thursday: "Torsdag",
  Friday: "fredag",
  Saturday: "lørdag",
  Sunday: "søndag",
  "Yearly view": "Årlig utsikt",
  Ascending: "Stigende",
  "Show event time next to title": "Vis hendelsestid ved siden av tittelen",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Juster hendelsesdatoen og tid til brukerens lokale tid basert på tidssonen.",
  "Display the time zone alongside the event date.":
    "Vis tidssonen ved siden av hendelsesdatoen.",
  "Show event time next to title": "Vis hendelsestid ved siden av tittelen",
  "Time Zone": "Tidssone",
  "Upload Image": "Last opp bilde",
  "Choose a Category": "Velg en kategori",
  "Color you have chosen will not be shown as you choose category":
    "Farge du har valgt vil ikke bli vist når du velger kategori",
  Website: "Nettsted",
  Next: "Neste",
  Save: "Lagre",
  "Last Name": "Etternavn",
  "Personal Info": "Personlig informasjon",
  Back: "Tilbake",
  "This field is required": "Dette feltet er obligatorisk",
  "Your event has been submitted": "Arrangementet ditt er sendt inn",
  "Enter a location": "Skriv inn et sted",
  "Display the time zone alongside the event date.":
    "Vis tidssonen ved siden av hendelsesdatoen.",
  Home: "Hjem",
  "Side By Side Event Limit": "Side om side hendelsesgrense",
  "Mobille App": "Mobille -app",
  category: "kategori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Hold oversikt over timeplanen din enkelt ved å importere Facebook-arrangementene dine til kalenderen din.",
  "Synchronized Pages": "Synkroniserte sider",
  "There are no synchronized pages": "Det er ingen synkroniserte sider",
  "Choose page": "Velg side",
  "You have no events": "Du har ingen hendelser",
  "Add Script": "Legg til skript",
  "script bound": "Dette skriptet er allerede bundet, velg andre detaljer!",
  "Choose account": "Velg konto",
  "Choose resource": "Velg ressurs",
  "Reconnect": "Koble til igjen",
  "script disappear": "Dette skriptet eksisterer ikke, legg til skript i Google Analytics!",
};
export default no;
