let pl = {
  "Your Api Key": "Twój klucz API",
  "Fahrenheit": "Fahrenheit",
  "Celsius": "Celsjusz",
  "Select the city from the suggestions": "Wybierz miasto z sugestii",
  "Weather Forecast": "Prognoza pogody",
  "Cross Event Limit": "Limit zdarzeń krzyżowych",
  "Show events limit": "Pokaż limit wydarzeń",
  "Show tooltip/popup": "Pokaż podpowiedź/okno podręczne",
  "Bold Monthly Dividers": "Pogrubione miesięczne podziałki",
  "Scroll to see more events": "Przewiń, aby zobaczyć więcej wydarzeń",
  "Show additional date": "Pokaż dodatkową datę",
  "Custom Link": "Niestandardowy link",
  "Link to event page": "Link do strony wydarzenia",
  "No link": "Brak linku",
  "Attach File": "Dołącz plik",
  "To be announced": "Do ogłoszenia",
  "Online": "W sieci",
  "Physical": "Fizyczny",
  "Select Categories to display events related to them, or manually choose specific events under Events": "Wybierz Kategorie, aby wyświetlić powiązane z nimi zdarzenia, lub ręcznie wybierz określone zdarzenia w obszarze Zdarzenia",
  "Automatically approve events from these addresses": "Automatycznie zatwierdzaj wydarzenia z tych adresów",
  "Approve events": "Zatwierdź wydarzenia",
  "Payable with a plan": "Płatne z planem",
  "Service Details": "Szczegóły usługi",
  "participants": "uczestnicy",
  "To": "Do",
  "From": "Z",
  "Ahead": "Dalej",
  "Ago": "Temu",
  "Change the category": "Zmień kategorię",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Synchronizacja Ticket Tailor umożliwia integrację wydarzeń i sesji z kalendarzem Boom.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Pokaż czas wydarzenia obok tytułu. To ustawienie ma zastosowanie wyłącznie do widoków miesięcznych, dziennych i tygodniowych.",
  "Show Staff Member": "Pokaż członka personelu",
  "Show Price": "Pokaż cenę",
  "To Event Page": "Do strony wydarzenia",
  "Layout": "Układ",
  "Acending": "Rosnąco",
  "Yearly": "Rocznie",
  "Layout device": "Urządzenie układowe",
  "Date container font": "Czcionka kontenera daty",
  "Hide Fully Booked Slots": "Ukryj w pełni zarezerwowane automaty",
  "Enable": "Włączać",
  "Limit": "Limit",
  "Export": "Eksport",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Za chwilę zmienisz szczegóły swojego wydarzenia. Po zmianie lista gości zostanie utracona.",
  "Change Date": "Zmień datę",
  "Ends": "Kończy się",
  "On": "NA",
  "After": "Po",
  "Accept": "Zaakceptować",
  "Show less": "Pokaż mniej",
  "Venue detail": "Szczegóły miejsca",
  "Reject": "Odrzucić",
  "See guest list": "Zobacz listę gości",
  "Submit Date": "Data przesłania",
  "Total guests": "Całkowita liczba gości",
  "Do you really want to delete selected user? Once removed, cannot be undone.": "Czy na pewno chcesz usunąć wybranego użytkownika? Raz usuniętej operacji nie można cofnąć.",
  "Delete Guest": "Usuń gościa",
  "Invoice number": "Numer faktury",
  "Status": "Status",
  "Payment type": "Typ płatności",
  "Select payment method to receive fees through tickets": "Wybierz metodę płatności, aby otrzymywać opłaty za pośrednictwem biletów",
  "Add Code": "Dodaj kod",
  "Add End Time": "Dodaj godzinę zakończenia",
  "Discount": "Rabat",
  "Promo codes for the sales": "Kody promocyjne na wyprzedaże",
  "Promo codes": "Kody promocyjne",
  "Add Ticket": "Dodaj bilet",
  "Limit type": "Typ limitu",
  "Paid": "Płatny",
  "Participation tickets for your event": "Bilety na Twoje wydarzenie",
  "Show the ticket limit": "Pokaż limit biletów",
  "Show limit": "Pokaż limit",
  "Show the price on ticket": "Pokaż cenę na bilecie",
  "Enable and configure your ticketing system": "Włącz i skonfiguruj swój system sprzedaży biletów",
  "Stop repeating here": "Przestań się tu powtarzać",
  "Limited": "Ograniczony",
  "Unlimited": "Nieograniczony",
  "Thank you message title": "Dziękuję tytuł wiadomości",
  "Submit button text": "Prześlij tekst przycisku",
  "Registration button text": "Tekst przycisku rejestracji",
  "Texts": "Teksty",
  "Modify the displayed texts": "Modyfikuj wyświetlane teksty",
  "Thank you message body": "Treść wiadomości, dziękuję",
  "Notify the user when the registration is canceled": "Powiadom użytkownika w przypadku anulowania rejestracji",
  "Cancellation email": "E-mail o anulowaniu",
  "Send a reminder to the user one day prior to the event": "Wyślij przypomnienie do użytkownika na jeden dzień przed wydarzeniem",
  "Reminder email": "E-mail z przypomnieniem",
  "Send an instant email to the user once registration is completed": "Wyślij natychmiastową wiadomość e-mail do użytkownika po zakończeniu rejestracji",
  "Notification email": "E-mail z powiadomieniem",
  "Reminder email about the event": "E-mail z przypomnieniem o wydarzeniu",
  "Email notifications to users": "Powiadomienia e-mailowe dla użytkowników",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).": "Kliknij przyciski przełączające obok każdego pola, aby dodać je do formularza rejestracyjnego. Jeśli chcesz, aby pole było wymagane, kliknij gwiazdkę (*).",
  "Form Fields": "Pola formularza",
  "Enter your form description": "Wprowadź opis formularza",
  "Form Title": "Tytuł formularza",
  "Enter your form title": "Wpisz tytuł formularza",
  "Form Details": "Szczegóły formularza",
  "Configure your registration form fields": "Skonfiguruj pola formularza rejestracyjnego",
  "Show guest limit": "Pokaż limit gości",
  "Enable Registration": "Włącz rejestrację",
  "Click to activate registration on this event": "Kliknij, aby aktywować rejestrację na to wydarzenie",
  "Customize the general settings of registration": "Dostosuj ogólne ustawienia rejestracji",
  "Enter URL": "Wprowadź URL",
  "Page URL": "Strona URL",
  "Close registration when the event starts": "Zamknij rejestrację po rozpoczęciu wydarzenia",
  "Redirect to a different website": "Przekieruj do innej witryny internetowej",
  "Where users can register": "Gdzie użytkownicy mogą się zarejestrować",
  "Open event registration landing page": "Otwórz stronę docelową rejestracji na wydarzenie",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.": "Przygotowanie do wydarzenia musiało wymagać wielu przygotowań. Nadszedł czas, aby usiąść i zrelaksować się, dopóki nie zgromadzą się goście! Gdy tylko zostanie dokonana nowa rejestracja, w tym miejscu pojawią się informacje o Twoim gościu. Wróć później, aby śledzić uczestników wydarzenia.",
  "You have no guests at the moment.": "W tej chwili nie masz gości.",
  "List of people who are registered to your event": "Lista osób zarejestrowanych na Twoje wydarzenie",
  "Guest List": "Lista gości",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.": "To wydarzenie cykliczne! Wszelkie zmiany wprowadzone w tym wydarzeniu zostaną zastosowane do wszystkich powtórzeń.",
  "Repeated event": "Powtórzone wydarzenie",
  "Delete Category": "Usuń kategorię",
  "Do you really want to delete selected category? Once removed, cannot be undone.": "Czy na pewno chcesz usunąć wybraną kategorię? Raz usuniętej operacji nie można cofnąć.",
  "OK": "OK",
  "Exclude": "Wykluczać",
  "Custom recurrence": "Niestandardowe powtarzanie",
  "Duplicate": "Duplikować",
  "Delete": "Usuwać",
  "Published": "Opublikowany",
  "Drafts": "Warcaby",
  "User events": "Wydarzenia użytkownika",
  "Add new category": "Dodaj nową kategorię",
  "Manage categories": "Zarządzaj kategoriami",
  "Add category": "Dodaj kategorię",
  "Never": "Nigdy",
  "Repeat every": "Powtarzaj każde",
  "Do you really want to delete selected event? Once removed, cannot be undone": "Czy na pewno chcesz usunąć wybrane wydarzenie? Raz usuniętej operacji nie można cofnąć",
  "There are no categories yet": "Nie ma jeszcze żadnych kategorii",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.": "Wprowadzanie zmian w zsynchronizowanym kalendarzu za pomocą poniższych łączy. Prosimy o dokładne zapoznanie się ze zmianami.",
  "occurrences": "zdarzenia",
  "Save as draft": "Zapisz jako szkic",
  "More Info": "Więcej informacji",
  "Book Now": "Rezerwuj teraz",
  "Show participants": "Pokaż uczestników",
  "This service is fully booked.": "Ta usługa jest w pełni zarezerwowana.",
  "All sessions are fully booked.": "Wszystkie sesje są w pełni zarezerwowane.",
  "Registration closed": "Rejestracja zamknięta",
  "Show your Wix Bookings or Events on Calendar": "Pokaż swoje rezerwacje lub wydarzenia WIX w kalendarzu",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.": "Wybierz Auto do automatycznego wyświetlania wszystkich usług i sesji w kalendarzu lub podręczniku do wyboru ręcznego.",
  "Show cancelled events": "Pokaż anulowane wydarzenia",
  "Event Color": "Kolor zdarzenia",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.": "Wybierz Auto do automatycznego wyświetlania wszystkich zdarzeń w kalendarzu lub podręcznika do wyboru ręcznego.",
  "Auto": "Automatyczny",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.": "Wybierz Auto do automatycznego wyświetlania wszystkich organizacji i organizatorów w kalendarzu lub podręczniku do wyboru ręcznego.",
  "Manual": "podręcznik",
  "Sync method": "Metoda synchronizacji",
  "Enable synchronization": "Włącz synchronizację",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only": "Zaprezentuj filtr kategorii u góry lub na dole kalendarza. Ustawienia dotyczy tylko wyświetleń programu, krzyża, harmonogramu i kart",
  "Load Events": "Załaduj zdarzenia",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.": "Po włączeniu widżet kalendarza zostanie przetłumaczony na podstawie języka witryny. Należy pamiętać, że dopóki tytuły i opisy kalendarzowe są wprowadzane jako tekst, nie można ich przetłumaczyć.",
  "Choose plan type": "Wybierz typ planu",
  "Api key": "Klucz API",
  "Synchronized Boxes": "Zsynchronizowane pudełka",
  "Choose box": "Wybierz pudełko",
  "There are no synchronized boxes": "Nie ma zsynchronizowanych pudełek",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Synchronizacja biletów umożliwia integrację wydarzeń i sesji z kalendarzem Boom",
  Categories: "Kategorie",
  "Share this event": "Udostępnij to wydarzenie",
  Language: "Język",
  "Show Time Zone": "Pokaż strefę czasową",
  "Custom Local Settings": "Niestandardowe ustawienia lokalne",
  "Add and showcase events on your site using a beautiful calendar.":
    "Dodaj i pokaż wydarzenia w swojej witrynie za pomocą pięknego kalendarza . ",
  "Week Days": "Dni tygodnia",
  "Manage Events": "Zarządzaj wydarzeniami",
  General: "Generał",
  "Layout Picker": "Wybór układu",
  Month: "Miesiąc",
  Monthly: "Miesięczny",
  Week: "Tydzień",
  Weekly: "Co tydzień",
  Day: "Dzień",
  Daily: "Codziennie",
  Agenda: "Program",
  "Navigation Buttons": "Przyciski nawigacyjne",
  "Week numbers": "Numery tygodniowe",
  "Include Weekends": "Dołącz weekendy",
  "All-day": "Cały dzień",
  "All Day": "Cały dzień",
  Label: "Etykieta",
  "Fit to Height": "Dopasuj do wysokości",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Aby ustawić proporcje App manully wyłączyć tę opcję i rozmiaru kalendarz w edytorze. ",
  "Default Layout": "Domyślny układ",
  "Monthly view": "Widok miesięczny",
  "Weekly and Daily view": "Widok tygodniowy i dzienny",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Możesz zapewnić odwiedzającym bardziej spójne wrażenia, pokazując tę ​​samą liczbę tygodni ( 6) naraz",
  "Fixed Weekly Layout": "Naprawiono układ tygodniowy",
  back: " powrót ",
  Row: "Rząd",
  "Hours in Weekly View": "Godziny w widoku tygodniowym",
  "Hours in Daily View": "Godziny w widoku dziennym",
  Start: "Początek",
  End: "Koniec",
  "At This Hour": "O tej godzinie",
  Button: "Przycisk",
  Buttons: "Guziki",
  Sunday: "Niedziela",
  Monday: "Poniedziałek",
  Tuesday: "Wtorek",
  Wednesday: "Środa",
  Thursday: " Czwartek ",
  Friday: "Piątek",
  Saturday: "Sobota",
  "Default Date": "Data domyślna",
  year: " rok ",
  month: " miesiąc ",
  mo: " miesiąc ",
  days: " dni ",
  ago: " temu ",
  ahead: " naprzód ",
  Yesterday: "Wczoraj",
  Today: "Dzisiaj",
  Tomorrow: "Jutro",
  Custom: "Zwyczaj",
  "Set Daily Rows Limit": "Ustaw limit dzienny wierszy",
  "Set Proportions": "Ustaw proporcje",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Pozwól odwiedzającym dodawać wydarzenia do lokalnych Calnedars , Google, Yahoo, Outlook, ICalendar . ",
  Container: "Pojemnik",
  Background: "Tło",
  "Container Background": "Tło pojemnika",
  "Container Borders": "Granice kontenerów",
  Calendar: "Kalendarz",
  "Event Info Tooltip": "Etykieta informacji o wydarzeniu",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Gdy ludzie najeżdżają na zdarzenie, zobaczą wszystkie informacje o nim w podpowiedzi. ",
  "Event Info Window": "Okno informacji o wydarzeniu",
  "This is the full information window that opens when someone clicks on the event.":
    "To jest pełne okno informacyjne, które otwiera się, gdy ktoś kliknie wydarzenie. ",
  "Use Gradient": "Użyj gradientu",
  Vertical: "Pionowy",
  Horizontal: "Poziomy",
  First: "Pierwszy",
  Second: "Druga",
  diagonal: " przekątna ",
  Radial: "Promieniowy",
  "Select option": "Wybierz opcję",
  Solid: "Solidny",
  Dotted: "Kropkowany",
  Dashed: "Przerywane",
  Double: "Podwójnie",
  "Border Radius": "Promień graniczny",
  Padding: "Wyściółka",
  "Date Header": "Nagłówek daty",
  "Event Default Color": "Domyślny kolor zdarzenia",
  "Days of Week": "Dni tygodnia",
  "Days of Week Background": "Tło dni tygodnia",
  Date: "Data",
  "Event Title": "Tytuł wydarzenia",
  "Highlight today": "Podświetl dzisiaj",
  "Highlight Color": "Podświetlony kolor",
  Hide: "Ukryć",
  "Calendar Border Color": "Kolor obramowania kalendarza",
  "Calendar Border Width": "Szerokość obramowania kalendarza",
  "Calendar Border Style": "Styl obramowania kalendarza",
  "Font Color": "Kolor czcionki",
  "Event Background": "Tło wydarzenia",
  "Card Date Color": "Kolor daty karty",
  "Title Font": "Czcionka tytułu",
  "Date Font": "Czcionka daty",
  "Description Font": "Czcionka opisu",
  "Button Background": "Tło przycisku",
  "Button Text": "Przycisk tekstowy",
  "Border Color": "Kolor ramki",
  "Border Width": "Szerokość granicy",
  "Border Type": "Typ obramowania",
  Title: "Tytuł",
  Description: "Opis",
  "Background Color": "Kolor tła",
  Divider: "Rozdzielacz",
  "Event Details Font": "Czcionka szczegółów wydarzenia",
  "Website Link Color": "Kolor linku do witryny",
  "Developer Info": "Informacje dla programistów",
  "User Guide": "Podręcznik użytkownika",
  "Support e-mail": "Wsparcie e-mail",
  "Our Website": "Nasza strona internetowa",
  "App Review": "Przegląd aplikacji",
  "Enjoying App? Leave us a review in the App Market.":
    "Korzystając z aplikacji? Zostaw nam recenzję na App Market. ",
  "Review Us": "Sprawdź nas",
  "Connect With Us": "Połącz się z nami",
  "What's your email?": "Jaki jest twój e-mail? ",
  "Invalid email address!": "Nieprawidłowy adres e-mail! ",
  Comments: "Komentarze",
  "We'd love to hear from you. Send us a message.":
    "Chcielibyśmy usłyszeć od ciebie. Wyślij nam wiadomość. ",
  "Message must be at least 5 characters long":
    "Wiadomość musi mieć co najmniej 5 znaków",
  Send: "Wysłać",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Jeśli chcesz zezwolić użytkownikowi na przełączanie się między widokami kalendarza, włącz tę opcję i wybierz widoki, które chcesz pokazać. ",
  Main: "Główny",
  Localize: "Zlokalizować",
  Settings: "Ustawienia",
  Layouts: "Układy",
  Advanced: "Zaawansowane",
  Design: "Projekt",
  Support: "Wsparcie",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Wszystkie lokalne ustawienia są (automatycznie) oparte na twoim języku. Jeśli Twój język jest na liście, nie ma potrzeby dostosowywania tej sekcji.",
  "Date Format": "Format daty",
  "Time Format": "Format czasu",
  "Text Direction": "Kierunek tekstu",
  "Left to Right": "Z lewej na prawą",
  "Right to Left": "Od prawej do lewej",
  "Week Starts On": "Tydzień zaczyna się od",
  "Agenda Style": "Styl agendy",
  Classic: "Klasyczny",
  Modern: "Nowoczesny",
  "Agenda Header": "Nagłówek agendy",
  "Upcoming Events": "nadchodzące wydarzenia",
  "Agenda Event Limit": "Limit wydarzeń w programie",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Zaktualizuj teraz i uzyskaj o wiele więcej funkcji i ciesz się aplikacją w całości!",
  "Upgrade Now": "Ulepsz teraz",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Prowadzisz wydarzenia trwające cały dzień? To pozwala pokazać je w kalendarzu.",
  "24 hours": "24 godziny",
  Sat: "Sob",
  Sun: "Nie",
  Mon: "Pon",
  Default: "Domyślna",
  "Select custom design style for your calendar.":
    "Wybierz niestandardowy styl projektowania swojego kalendarza.",
  Style: "Styl",
  "Styles and Colors": "Style i kolory",
  "Calendar Name": "Nazwa kalendarza",
  "Write your Calendar name here": "Wpisz tutaj swoją nazwę kalendarza",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Nie jest to widoczne dla użytkowników. Ustaw nazwy, aby rozróżnić kalendarze podczas korzystania z funkcji synchronizacji kalendarza Boom.",
  "General Info": "Ogólne informacje",
  Venue: "Miejsce wydarzenia",
  Organizer: "Organizator",
  Search: "Szukaj",
  "Add to": "Dodać do",
  calendar: "kalendarz",
  "Copy event URL": "Skopiuj adres URL wydarzenia",
  "Copied!": "Skopiowano!",
  "Add & Share": "Dodaj i udostępnij",
  Map: "Mapa",
  "Calendar view": "Widok kalendarza",
  "Add Event": "Dodaj wydarzenie",
  Uncategorised: "Bez kategorii",
  More: "Więcej",
  Less: "Mniej",
  Register: "Zarejestrować",
  Card: "Karta",
  Guests: "Goście",
  unlimited: "Nieograniczony",
  "Show more": "Pokaż więcej",
  "Enable Search": "Włącz wyszukiwanie",
  "+ Add Event": "+ Dodaj wydarzenie",
  "Manage and Sync": "Zarządzaj i synchronizuj",
  "Show event details as...": "Pokaż szczegóły wydarzenia jako ...",
  Tooltip: "Etykietka",
  Popup: "Skrzynka informacyjna",
  None: "Żaden",
  "Show Category": "Pokaż kategorię",
  "Header Align": "Header Align",
  "Show Time": "Header Align",
  "Hours in Weekly/Daily View": "Godziny w widoku tygodniowym / dziennym",
  "Share Events": "Udostępniaj wydarzenia",
  Shadow: "Cień",
  "Inner Padding": "Wewnętrzna wyściółka",
  Text: "Tekst",
  "Active Button Border": "Ramka aktywnego przycisku",
  "Light Mode": "Tryb światła",
  "Event Text Color": "Kolor tekstu wydarzenia",
  Dates: "Daktyle",
  Skeleton: "Szkielet",
  "Skeleton Color": "Kolor szkieletu",
  Width: "Szerokość",
  "Skeleton Style": "Styl szkieletu",
  Color: "Kolor",
  "Section Titles": "Tytuły sekcji",
  "Section Content": "Treść sekcji",
  Header: "nagłówek",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Srebro",
  Night: "Noc",
  Dark: "Ciemny",
  Aubergine: "Noc",
  "Map Header": "Nagłówek mapy",
  "Show Title in mobile": "Pokaż tytuł w telefonie komórkowym",
  "Card View": "Widok karty",
  "Card background color": "Kolor tła karty",
  "Title font": "Czcionka tytułu",
  "Desciption font": "Czcionka opisu",
  "Section font": "Sekcja czcionek",
  "Section divider color": "Kolor przegrody",
  "Add event": "Dodaj wydarzenie",
  "All Day Event": "Wydarzenie całodniowe",
  Location: "Lokalizacja",
  "Choose a category": "Wybierz kategorię",
  "Venue name": "Nazwa miejsca",
  "Venue phone": "Telefon miejsca",
  "Venue email": "E-mail dotyczący miejsca",
  "Venue website": "Strona miejsca",
  "Organizer name": "Nazwa organizatora",
  "Organizer phone": "Telefon organizatora",
  "Organizer email": "E-mail organizatora",
  "Organizer website": "Witryna organizatora",
  "Personal info": "Dane osobiste",
  "First name": "Imię",
  "Last name": "Nazwisko",
  "Email Address": "Adres e-mail",
  "Additional Notes": "Dodatkowe uwagi",
  Back: "Z powrotem",
  Next: "Kolejny",
  "Your event has been submitted": "Twoje wydarzenie zostało przesłane",
  "Event submittion has been failed": "Przesłanie wydarzenia nie powiodło się",
  "e.g. Birthday Party": "na przykład. Przyjęcie urodzinowe",
  "First Name": "Imię",
  "Last Name": "Nazwisko",
  "Phone Number": "Numer telefonu",
  Address: "Adres",
  "Your comments": "Twoje komentarze",
  "How many guests?": "Ilu gości?",
  "Anything else we need to know?": "Coś jeszcze musimy wiedzieć?",
  "Guests:": "Goście:",
  Submit: "Zatwierdź",
  "Go to Calendar": "",
  "Registration completed successfully!": "Rejestracja zakończona pomyślnie!",
  "Please check your registered email address":
    "Sprawdź swój zarejestrowany adres e-mail",
  "Add to Calendar": "Dodaj do kalendarza",
  "Share this Event": "Udostępnij to wydarzenie",
  "Sorry something went wrong": "Przepraszam, coś poszło nie tak",
  "Back to registration": "Terug naar registratie",
  "Date & Location": "Data i lokalizacja",
  "Date & Time": "Data i godzina",
  home: "Dom",
  "Header align": "Wyrównaj nagłówek",
  Footer: "Stopka",
  "Categories Filter": "kategorie Filtr",
  "Show only upcoming": "Pokaż tylko nadchodzące",
  "Card(s) in a row": "Karty z rzędu",
  "Space between cards": "Przestrzeń między kartami",
  "Shown events limit": "Limit wyświetlanych wydarzeń",
  "Style 1": "Styl 1",
  "Style 2": "Styl 2",
  "Style 3": "Styl 3",
  "Style 4": "Styl 4",
  "Buttons & Links": "Przyciski i linki",
  "Button corner radius": "Promień narożnika przycisku",
  "Buttons font": "Czcionka przycisków",
  "Buttons background": "Tło przycisków",
  "Get notified by Email": "Otrzymuj powiadomienia e-mailem",
  "Review events": "Przegląd wydarzeń",
  "Click on date": "Kliknij datę",
  "Add Event button": "Przycisk Dodaj wydarzenie",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizacja kalendarza umożliwia integrację wydarzeń i sesji z kalendarzem Boom.",
  connect: "połączyć",
  "Synchronized Calendars": "Kalendarze zsynchronizowane",
  "Import events": "Importuj wydarzenia",
  Disconnect: "Rozłączyć się",
  "Choose calendar": "Wybierz kalendarz",
  "Monitor your Wix events through the sync feature":
    "Monitoruj swoje wydarzenia Wix za pomocą funkcji synchronizacji",
  "Connect all your Boom calendars available on your website":
    "Połącz wszystkie swoje kalendarze Boom dostępne w Twojej witrynie",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Planuj, dołączaj i zarządzaj spotkaniami Zoom za pomocą naszego Kalendarza Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Monitoruj wydarzenia Event Brite za pomocą funkcji synchronizacji Event Brite",
  Email: "E-mail",
  "Add-ons": "Dodatki",
  "Receive notification emails as soon as users add events to your calendar.":
    "Otrzymuj powiadomienia e-maile, gdy tylko użytkownicy dodają zdarzenia do kalendarza.",
  "Enable + button on the calendar header":
    "Enable + button on the calendar header",
  "Accept or decline events added by customers before making them public.":
    "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Switch Dodaj zdarzenie",
  "Enable your browser cookies to connect to your account.":
    "Włącz pliki cookie przeglądarki do połączenia z kontem.",
  "Learn more": "Ucz się więcej",
  "Print Button": "Wydrukuj przycisk",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Zezwalaj użytkownikom na wydrukowanie kalendarza zdarzenia wysięgnika w dowolnym zakresie dat.",
  "Show Title on mobile": "Pokaż tytuł na telefon komórkowy",
  "Show Skeleton on mobile": "Pokaż szkielet na telefonie komórkowym",
  "Start 7-day Business trial": "Uruchom 7-dniową wersję próbną",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Ciesz się wszystkimi nieograniczonymi funkcjami, takimi jak sprzedawać bilety, rejestracja, dodatki zdarzeń użytkownika.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Uwaga: Pod koniec okresu próbnego zostaniesz zwrócony do istniejącego planu subskrypcji.",
  "Not Now": "Nie teraz",
  "Start free trial": "Rozpocznij darmowy okres próbny",
  "Congrats!": "Gratulacje!",
  "Your 7-day Business trial has been successfully activated.":
    "Twój 7-dniowy proces biznesowy został pomyślnie aktywowany.",
  Done: "Zrobione",
  "Title font color": "Tytułowy kolor czcionki",
  "Desciption font color": "Opis kolor czcionki",
  "Section font color": "Kolor czcionki sekcji",
  "Card Header": "Nagłówek kart",
  Category: "Kategoria",
  "Display at the": "Wyświetlacz w The.",
  top: "szczyt",
  bottom: "na dole",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Pokaż filtr kategorii na górze lub na dole kalendarza.Ustawienia dotyczy tylko widoków programów i kart",
  "Processing your events": "Przetwarzanie wydarzeń",
  "Search for events": "Szukaj wydarzeń.",
  "There are no events added": "Nie ma żadnych zdarzeń",
  "Location: To be determined": "Lokalizacja: Do ustalenia",
  "No events for selected date": "Brak zdarzeń dla wybranej daty",
  Uncategorized: "Bez kategorii",
  "Edit event": "Edytuj wydarzenie",
  "Edit original event": "Edytuj oryginalne wydarzenie",
  "Copy event": "Wydarzenie kopiowania",
  "Copy as new event": "Kopiuj jako nowe wydarzenie",
  "Delete event": "Usuń zdarzenie",
  "Stop repeating on this date": "Przestań powtarzać w tym dniu",
  "Exclude this date": "Wyklucz tę datę",
  "Location is going to be announced": "Lokalizacja zostanie ogłoszona",
  "Fill your personal information": "Wypełnij swoje dane osobowe",
  "Check Box": "Pole wyboru",
  "Single Choice": "Pojedynczy wybór",
  Option: "Opcja",
  "Share Event": "Udostępnij wydarzenie",
  "Oops! Something went wrong": "Ups!Coś poszło nie tak",
  "We are sorry this event has already taken place":
    "Przykro nam to wydarzenie już miało miejsce",
  "Back to calendar": "Powrót do kalendarza",
  "This field is required": "To pole jest wymagane",
  Phone: "Telefon",
  "Number field": "Pole liczbowe",
  "Please provide a valid email": "Proszę podać ważny e -mail",
  "Select at least one option": "Wybierz co najmniej jedną opcję",
  "Choose tickets to see total value":
    "Wybierz bilety, aby zobaczyć całkowitą wartość",
  tickets: "bilety",
  "Choose Tickets": "Wybierz bilety",
  "Choose payment method": "Wybierz metodę płatności",
  Pay: "Zapłacić",
  Total: "Całkowity",
  Free: "Wolny",
  "Buy tickets": "Kup bilety",
  "Sold Out": "Wyprzedane",
  "Tickets are available": "Bilety są dostępne",
  "Sales End": "Koniec sprzedaży",
  "Availible from": "dostępne od",
  "Go to Orders": "Idź do zamówień",
  "Go to Details": "Przejdź do szczegółów",
  "Group ticket": "Bilet grupowy",
  Name: "Nazwa",
  Price: "Cena £",
  "Order by": "Zamów przez",
  "Order ID": "Identyfikator zamówienia",
  Applied: "Stosowany",
  Fees: "Opłaty",
  "Enter promo code": "Wpisz kod promocyjny",
  Apply: "Zastosować",
  "Promo Code": "Kod promocyjny",
  Cash: "Gotówka",
  "You can find your e-tickets attached to your email or download them":
    "Możesz znaleźć e-bilety dołączone do e-maila lub pobrać je",
  here: "tutaj",
  Time: "Czas",
  "Invalid promo code": "Nieprawidłowy kod promocyjny",
  "Credit card": "Karta kredytowa",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Wkrótce otrzymasz wiadomość potwierdzającą udaną rejestrację na swój adres e -mail.",
  "You can also check your order details below.":
    "Możesz także sprawdzić szczegóły zamówienia poniżej.",
  at: "w",
  Buy: "Kup",
  Donation: "Darowizna",
  "Enter price": "Przedsiębiorstwo",
  Choose: "Wybierać",
  Chosen: "Wybrany",
  "Choose your plan": "Wybierz swój plan",
  week: "tydzień",
  wk: "tydzień",
  "Choose plan cycle": "Wybierz cykl planu",
  months: "miesiące",
  years: "lata",
  weeks: "tygodnie",
  "Copy Event Url": "Kopiuj adres URL zdarzenia",
  "You can find your e-tickets attached to your email or print them":
    "Możesz znaleźć e-bilety dołączone do wiadomości e-mail lub wydrukować je",
  "Guest Info": "Informacje o gościa",
  "Ticket Info": "Informacje o bilecie",
  "Ticket name": "Nazwa biletu",
  "Ticket price": "Cena biletu",
  "Ticket ID": "Identyfikator biletu",
  "If you have any questions contact to organizer":
    "Jeśli masz jakieś pytania, kontaktuj się z organizatorem",
  "As soon as event ends": "Jak tylko wydarzenie się skończy",
  "1 day after event ends": "1 dzień po zakończeniu wydarzenia",
  "7 days after event ends": "7 dni po zakończeniu wydarzenia",
  "14 days after event ends": "14 dni po zakończeniu wydarzenia",
  "30 days after event ends": "30 dni po zakończeniu wydarzenia",
  Menu: "Menu",
  "No event for selected date": "Brak zdarzenia dla wybranej daty",
  view: "pogląd",
  List: "Lista",
  Year: "Rok",
  Yearly: "Rocznie",
  "Year view header": "Rok widok na nagłówek",
  "Yearly Style": "Coroczny styl",
  "There are no events": "Brak wydarzeń",
  Autotranslation: "Autotranslation.",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "Po włączeniu widget kalendarza zostanie przetłumaczony na podstawie języka witryny.* Należy pamiętać, że tak długo jak tytuł kalendarza i opisy są wprowadzane teksty, których nie można ich przetłumaczyć.",
  "Note on mobile": "Uwaga na telefonie komórkowym",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Wyłącz lub zmień tekst baru 'No Events' na mobilnej wersji kalendarza",
  Autodeletion: "Autodelecja",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Włączając opcję, automatycznie usunie twoje przeszłe zdarzenia z kalendarza.",
  "This does not apply to repeating events!":
    "Nie dotyczy to powtarzających się zdarzeń!",
  "Notify event creators about the guest": "Powiadom użytkowników o gościu",
  "Send event creators notification emails as soon as guests register for their events":
    "Wysyłaj e-maile z powiadomieniami twórców wydarzeń, gdy tylko goście zarejestrują się na swoje wydarzenia",
  "List View Type": "Typ widoku listy",
  "Description font": "Czcionka opisu",
  Connect: "połączyć",
  "You have no events": "Nie masz wydarzeń",
  Synchronize: "Synchronizować",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizacja kalendarza Google umożliwia integrację wydarzeń i sesji z kalendarzem wysięgnika.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Synchronizacja kalendarza Outlook umożliwia integrację wydarzeń i sesji z kalendarzem wysięgnika.",
  "Your message has been sent successfully!":
    "Twoja wiadomość została wysłana poprawnie!",
  "There are no synchronized calendars": "Nie ma synchronizowanych kalendarzy",
  "to view more than 7 events": "aby wyświetlić więcej niż 7 wydarzeń",
  "Mobile app": "Aplikacja mobilna",
  "Admin Account": "Konto administratora",
  Password: "Hasło",
  "Second User": "Drugi użytkownik.",
  Edit: "Edytować",
  "Guest limit": "Gość",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Wszystkie lokalne ustawienia są (automatycznie) na podstawie twojego języka.Jeśli twój język znajduje się na liście, nie ma potrzeby dostosowywania tej sekcji.",
  available: "dostępny",
  next: "Kolejny",
  Tickets: "Bilety",
  Quantity: "Ilość",
  "Promo code": "Kod promocyjny",
  "Select a payment method": "Wybierz metodę płatności",
  Fee: "Opłata",
  Book: "Książka",
  "All the tickets have been sold out": "Wszystkie bilety zostały wyprzedane",
  "Choose at least one ticket": "Wybierz co najmniej jeden bilet",
  "First choose ticket": "Najpierw wybierz bilet",
  "Please fill out your personal information.": "Wypełnij swoje dane osobowe.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Aby dokonać udanego zakupu, wybierz preferowaną metodę płatności i wprowadź kod promocyjny dla biletów zniżki.",
  "Credit/Debit card": "Karta kredytowa / debetowa",
  "print here.": "Drukuj tutaj.",
  "QR code for all tickets": "Kod QR dla wszystkich biletów",
  Duration: "Trwanie",
  "Full Name": "Pełne imię i nazwisko",
  "Ticket id": "Identyfikator biletu",
  "Group id": "Identyfikator grupy",
  "Choose your ticket.": "Wybierz bilet.",
  "Fill out your personal information.": "Wypełnij swoje dane osobowe.",
  "Add the payment details.": "Dodaj szczegóły płatności.",
  "To be determined": "Do ustalenia",
  "You can find your e-tickets attached to the email or":
    "Możesz znaleźć bilety elektroniczne dołączone do wiadomości e-mail lub",
  "print here": "Drukuj tutaj",
  "Full name": "Pełne imię i nazwisko",
  "Group ID": "Identyfikator grupy",
  "to Book": "zarezerwować",
  "Unfortunately, your card has been declined":
    "Niestety, Twoja karta została odrzucona",
  "Thank you for your purchase!": "Dziękujemy za zakupy!",
  "Find your printable e-tickets attached to the confirmation email":
    "Znajdź swoje bilety do wydruku dołączone do e-maila potwierdzenia",
  Confirm: "Potwierdzać",

  "Add event": "Dodaj wydarzenie",
  Events: "Wydarzenia",
  "Event details": "Szczegóły wydarzenia",
  Registration: "Rejestracja",
  "Guests list": "Lista gości",
  Ticket: "Bilet",
  "General Info": "Ogólne informacje",
  "Customize the general settings of your event":
    "Dostosuj ogólne ustawienia swojego wydarzenia",
  "Event Title": "Tytuł wydarzenia",
  "e.g. Birthday Party": "np. Przyjęcie urodzinowe",
  "All Day Event": "Wydarzenie przez cały dzień",
  Cross: "Przechodzić",
  Timeline: "Oś czasu",
  "Repeating event": "Powtarzające się wydarzenie",
  Location: "Lokalizacja",
  "Venue name": "Nazwa miejsca",
  Description: "Opis",
  Image: "Obraz",
  Color: "Kolor",
  Category: "Kategoria",
  "Add your events to color categories and let your users classify them easily":
    "Dodaj swoje zdarzenia do kategorii kolorów i pozwól użytkownikom łatwo je sklasyfikować",
  "Category name": "Nazwa Kategorii",
  "e.g. Birthdays": "np. Urodziny",
  Venue: "Lokal",
  "Where the event takes place": "Gdzie odbywa się wydarzenie",
  "Venue name": "Nazwa miejsca",
  "Venue phone": "Telefon do miejsca",
  "Venue email": "E -mail z miejsca",
  "Venue website": "Witryna miejsca",
  Organizer: "Organizator",
  "Person who makes the event": "Osoba, która robi wydarzenie",
  "Organizer name": "Nazwa organizatora",
  "Organizer phone": "Telefon organizatora",
  "Organizer email": "E -mail organizatora",
  "Organizer website": "Strona internetowa organizatora",
  Cancel: "Anulować",
  Import: "Import",
  Past: "Przeszłość",
  All: "Wszystko",
  Upcoming: "Nadchodzące",
  Uncategorised: "Bez kategorii",
  "Date Ascending": "Data wznoszenia",
  "Date Descending": "Data zstępująca",
  "Title by A-Z": "Tytuł A-Z",
  "Title by Z-A": "Tytuł Z-A.",
  "There are no events for this period": "Nie ma wydarzeń na ten okres",
  "Auto-Convert Date & Time": "Automatyczna data i czas",
  TimeZone: "Strefa czasowa",
  Autodeletion: "Autodelecja",
  "Layout Settings": "Ustawienia układu",
  "Yeatly view": "Yeatly View",
  "Monthly view header": "Miesięczny nagłówek widoku",
  "Weekly/Daily view header": "Cotygodniowy/codzienny nagłówek",
  Acendings: "Acendings",
  Descending: "Schodzenie",
  Standart: "Standart",
  Silver: "Srebro",
  Retro: "Retro",
  Dark: "Ciemny",
  Night: "Noc",
  Aubergine: "Bakłażan",
  "List view header": "Wyświetl nagłówek listy",
  "Side by Side View": "Widok z boku",
  "Customize Proportions": "Dostosuj proporcje",
  "Card Margins": "Margines karty",
  "Image opacity (%)": "Krycie obrazu (%)",
  "Side by Side Header": "Obok siebie nagłówek",
  "Text Align": "Wyrównaj tekst",
  "Timeline View": "Widok osi czasu",
  "Title font color": "Tytułowy kolor czcionki",
  "Desciption font color": "Kolor czcionki descypcji",
  "Line color": "Kolor linii",
  "Date Font color": "Kolor czcionki daty",
  "Daily events background": "Codzienne zdarzenia tło",
  Alignment: "Wyrównanie",
  Vertical: "Pionowy",
  Horizontal: "Poziomy",
  "Vertical Alignment": "Wyrównanie pionowe",
  Right: "Prawidłowy",
  Center: "Centrum",
  "Horizontal Alignment": "Wyrównanie poziome",
  Top: "Szczyt",
  Center: "Centrum",
  Bottom: "Spód",
  "Dates Circle Design": "Daty konstrukcji okręgu",
  "Next To The Circle": "Obok kręgu",
  "In The Circle": "W kręgu",
  "Timeline Header": "Nagłówek osi czasu",
  Timeline: "Oś czasu",
  "Show only upcoming": "Pokaż tylko nadchodzące",
  "Order by": "Zamów przez",
  "Timeline Event Limit": "Limit zdarzeń harmonogramu",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Pozwól odwiedzającemu dodać zdarzenie do lokalnych cielątek: Google, Yahoo, Outlook, icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Pozwól odwiedzającemu udostępnić swoje wydarzenie na Facebooku, LinkedIn, Twitter i itp.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Dodaj opcję wyszukiwania w swoim kalendarzu, aby ludzie wyszukiwali Twoje wydarzenia według tytułu, miejsca itp.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Pozwól użytkownikom wydrukować kalendarz zdarzeń Boom w dowolnym zakresie daty.",
  "Click to apply a theme to Calendar":
    "Kliknij, aby zastosować motyw do kalendarza",
  "Date container color": "Kolor kontenera daty",
  "Daily events background": "Codzienne zdarzenia tło",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Użyj dodatków, aby zainstalować zaawansowane funkcje w swoich kalendarzach, dzięki czemu są bardziej funkcjonalne!",
  "Open Add-ons Store": "Otwórz sklep z dodatkami",
  Monday: "Poniedziałek",
  Tuesday: "Wtorek",
  Wednesday: "Środa",
  Thursday: "Czwartek",
  Friday: "Piątek",
  Saturday: "Sobota",
  Sunday: "Niedziela",
  "Yearly view": "Widok roczny",
  Ascending: "Wznoszący się",
  "Show event time next to title": "Pokaż czas wydarzenia obok tytułu",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Dostosuj datę i godzinę zdarzenia do czasu lokalnego użytkownika w oparciu o jego strefę czasową.",
  "Display the time zone alongside the event date.":
    "Wyświetl strefę czasową wraz z datą zdarzenia.",
  "Show event time next to title": "Pokaż czas wydarzenia obok tytułu",
  "Time Zone": "Strefa czasowa",
  "Upload Image": "Załaduj obrazek",
  "Choose a Category": "Wybierz kategorię",
  "Color you have chosen will not be shown as you choose category":
    "Kolor, który wybrałeś, nie zostanie wyświetlony podczas wyboru kategorii",
  Website: "Strona internetowa",
  Next: "Następny",
  Save: "Akceptuj",
  "Last Name": "Nazwisko",
  "Personal Info": "Dane osobiste",
  Back: "Z powrotem",
  "This field is required": "To pole jest wymagane",
  "Your event has been submitted": "Twoje wydarzenie zostało złożone",
  "Enter a location": "Wprowadź lokalizację",
  "Display the time zone alongside the event date.":
    "Wyświetl strefę czasową wraz z datą zdarzenia.",
  Home: "Dom",
  "Side By Side Event Limit": "Obok siebie limit zdarzeń",
  "Mobille App": "Aplikacja M w Mobille",
  category: "Kategoria",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Łatwo śledź swój harmonogram, importując wydarzenia z Facebooka do swojego kalendarza.",
  "Synchronized Pages": "Zsynchronizowane strony",
  "There are no synchronized pages": "Brak zsynchronizowanych stron",
  "Choose page": "Wybierz stronę",
  "You have no events": "Nie masz wydarzeń",
  "Add Script": "Dodaj skrypt",
  "script bound": "Ten skrypt jest już związany, wybierz inne szczegóły!",
  "Choose account": "Wybierz konto",
  "Choose resource": "Wybierz zasób",
  "Reconnect": "Na nowo połączyć",
  "script disappear": "Ten skrypt nie istnieje, dodaj skrypt w Google Analytics!",
  "Reset Layouts Dimensions": "Resetuj układy wymiary",
  "Clear": "Jasne",
  "Undo": "Anulować",
  "Redo": "Przerobić",
  "Code Panel": "Panel kodu",
  "Code Panel Notify": "Bezpośrednia modyfikacja kodu może przełamać funkcję układu lub aplikacji. Edytuj tylko wtedy, gdy wiesz, co robisz!",
  "Clear Editor": "Wyczyść redaktor",
  "Clear Editor Notify": "Czy na pewno chcesz wyczyścić edytor? Wszystkie postępy zostaną utracone!",
  "Nothing to edit": "Nie ma nic do edycji!",
  "Shapes": "Kształty",
  "Delete The Shape": "Usuń kształt",
  "Add shapes": "Dodaj kształty między układami i dostosuj!",
  "Preview unavailable": "Podgląd komponentu niedostępny dla komponentu",
  "component removed": "Komponent usunięty z edytora.",
  "component duplicate": "Dodano komponent, Uwaga: duplikat wpisu!",
  "component added": "komponent z powodzeniem dodany do edytora.",
  "Component Preview": "Podgląd komponentów",
  "Height": "Wysokość",
  "Font Family": "Rodzina czcionek",
  "Select Font": "Wybierz czcionkę",
  "Font Weight": "Waga czcionki",
  "Font Size": "Rozmiar czcionki",
  "Text Alignment": "Wyrównanie tekstu",
  "Left Alignment": "Pozostawione wyrównanie",
  "Center Alignment": "Wyrównanie centrum",
  "Right Alignment": "Właściwe wyrównanie",
  "Text Decoration": "Dekoracja tekstu",
  "Overline": "Overline",
  "Line Through": "Przejdź",
  "Underline": "Podkreślać",
  "Underline and Overline": "Podkreślić i przewyższają",
  "Without Decoration": "Bez dekoracji",
  "Left": "Lewy",
  "Angle": "Kąt",
  "Distance": "Dystans",
  "Blur": "Plama",
  "Size": "Rozmiar",
  "Edit individually": "Edytuj indywidualnie",
  "Apply to all corners": "Zastosuj się na wszystkie rogi",
  "Date Box Visual": "Pudełko daty wizualne",
  "One Line": "Jedna linia",
  "Show Icons": "Pokaż ikony",
  "Design Settings": "Ustawienia projektowe",
  "Personalize your editor to match your style and preferences, customize every detail in this settings tab !": "Spersonalizuj edytor, aby dopasować swój styl i preferencje, dostosuj każdy szczegół w tej zakładce Ustawienia!",
  "Divider": "Rozdzielacz",
  "Ellipse": "Elipsa",
  "Rhombus": "Romb",
  "Heart": "Serce",
  "Hexagon": "Sześciokąt",
  "Circle": "Koło",
  "Rectangle": "Prostokąt",
  "Square": "Kwadrat",
  "Triangle": "Trójkąt",
  "Star": "Gwiazda",

  /* Event Page & Registration - New Keys */
  "A confirmation email has been sent to you": "Wysłano do Ciebie e-mail z potwierdzeniem",
  "Available Spots": "Dostępne miejsca",
  "Event Details": "Szczegóły wydarzenia",
  "Free admission": "Bezpłatny wstęp",
  "Get Tickets Now": "Kup bilety teraz",
  "Get Tickets": "Kup bilety",
  "Instant confirmation": "Natychmiastowe potwierdzenie",
  "No seats selected": "Nie wybrano miejsc",
  "No tickets available for this event.": "Brak biletów na to wydarzenie.",
  "No tickets selected": "Nie wybrano biletów",
  "Order Summary": "Podsumowanie zamówienia",
  "Payment": "Płatność",
  "Please enter a valid email": "Podaj prawidłowy adres e-mail",
  "Please enter your name": "Podaj swoje imię",
  "Please select at least one seat": "Wybierz co najmniej jedno miejsce",
  "Register Now": "Zarejestruj się teraz",
  "Registration Complete": "Rejestracja zakończona",
  "Secure checkout": "Bezpieczna płatność",
  "Select Tickets": "Wybierz bilety",
  "Select Your Seats": "Wybierz swoje miejsca",
  "Select seats above to continue": "Wybierz miejsca powyżej, aby kontynuować",
  "Select tickets above to continue": "Wybierz bilety powyżej, aby kontynuować",
  "Selected Seats": "Wybrane miejsca",
  "Service Fee": "Opłata serwisowa",
  "Subtotal": "Suma częściowa",
  "Total Amount": "Łączna kwota",
  "View your ticket": "Zobacz swój bilet",
  "each": "każdy",
  "per ticket": "za bilet",
  "seat": "miejsce",
  "seats": "miejsca",
  "selected": "wybrano",
  "ticket": "bilet",
  "About This Event": "O tym wydarzeniu",
  "Gallery": "Galeria",
};
export default pl;
