let ru = {
  "To": "К",
  "From": "От",
  "Ahead": "Предстоящий",
  "Ago": "Назад",
  "Change the category": "Изменить категорию",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Синхронизация Ticket Tailor позволяет интегрировать ваши события и сеансы с календарем Boom.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Показывать время события рядом с названием. Этот параметр применим только к представлениям «Ежемесячно», «Ежедневно» и «Еженедельно».",
  "Show Staff Member": "Показать сотрудника",
  "Show Price": "Показать цену",
  "To Event Page": "На страницу мероприятия",
  "Layout": "Макет",
  "Acending": "Последующий",
  "Yearly": "Ежегодно",
  "Layout device": "Устройство макета",
  "Date container font": "Шрифт контейнера даты",
  "Hide Fully Booked Slots": "Скрыть полностью забронированные слоты",
  "Enable": "Давать возможность",
  "Limit": "Лимит",
  "Export": "Экспорт",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Вы собираетесь изменить детали вашего мероприятия. После изменения ваш список гостей будет утерян.",
  "Change Date": "Изменить дату",
  "Ends": "Заканчивается",
  "On": "На",
  "After": "После",
  "Accept": "Принимать",
  "Show less": "Показывай меньше",
  "Venue detail": "Детали места проведения",
  Reject: "Отклонять",
  "See guest list": "Посмотреть список гостей",
  "Submit Date": "Дата отправки",
  "Total guests": "Всего гостей",
  "Do you really want to delete selected user? Once removed, cannot be undone.":
    "Вы действительно хотите удалить выбранного пользователя? После удаления его невозможно отменить.",
  "Delete Guest": "Удалить гостя",
  "Invoice number": "Номер счета",
  Status: "Положение дел",
  "Payment type": "Способ оплаты",
  "Select payment method to receive fees through tickets":
    "Выберите способ оплаты, чтобы получать комиссию через билеты",
  "Add Code": "Добавить код",
  "Add End Time": "Добавить время окончания",
  Discount: "Скидка",
  "Promo codes for the sales": "Промокоды на распродажи",
  "Promo codes": "Промокоды",
  "Add Ticket": "Добавить билет",
  "Limit type": "Тип лимита",
  Paid: "Оплаченный",
  "Participation tickets for your event": "Билеты на ваше мероприятие",
  "Show the ticket limit": "Показать лимит билета",
  "Show limit": "Показать лимит",
  "Show the price on ticket": "Показать цену на билете",
  "Enable and configure your ticketing system":
    "Включите и настройте вашу систему продажи билетов",
  "Stop repeating here": "Хватит повторять здесь",
  Limited: "Ограниченное",
  Unlimited: "Безлимитный",
  "Thank you message title": "Спасибо, заголовок сообщения",
  "Submit button text": "Отправить текст кнопки",
  "Registration button text": "Текст кнопки регистрации",
  Texts: "Тексты",
  "Modify the displayed texts": "Изменить отображаемые тексты",
  "Thank you message body": "Тело сообщения с благодарностью",
  "Notify the user when the registration is canceled":
    "Уведомить пользователя об отмене регистрации",
  "Cancellation email": "Письмо об отмене",
  "Send a reminder to the user one day prior to the event":
    "Отправьте напоминание пользователю за день до мероприятия",
  "Reminder email": "Напоминание по электронной почте",
  "Send an instant email to the user once registration is completed":
    "Отправьте мгновенное электронное письмо пользователю после завершения регистрации.",
  "Notification email": "Уведомление по электронной почте",
  "Reminder email about the event":
    "Напоминание по электронной почте о мероприятии",
  "Email notifications to users":
    "Уведомления по электронной почте для пользователей",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).":
    "Нажмите на кнопки переключения рядом с каждым полем, чтобы добавить его в регистрационную форму. Если вы хотите сделать поле обязательным, нажмите на звездочку (*).",
  "Form Fields": "Поля формы",
  "Enter your form description": "Введите описание формы",
  "Form Title": "Название формы",
  "Enter your form title": "Введите название формы",
  "Form Details": "Детали формы",
  "Configure your registration form fields":
    "Настройте поля регистрационной формы",
  "Show guest limit": "Показать лимит гостей",
  "Enable Registration": "Включить регистрацию",
  "Click to activate registration on this event":
    "Нажмите, чтобы активировать регистрацию на это мероприятие",
  "Customize the general settings of registration":
    "Настройте общие параметры регистрации",
  "Enter URL": "Введите URL",
  "Page URL": "URL-адрес страницы",
  "Close registration when the event starts":
    "Закрыть регистрацию после начала мероприятия",
  "Redirect to a different website": "Перенаправление на другой сайт",
  "Where users can register": "Где пользователи могут зарегистрироваться",
  "Open event registration landing page":
    "Открыть целевую страницу регистрации на мероприятие",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.":
    "Должно быть, вам потребовалась серьезная подготовка к мероприятию. Сейчас самое время расслабиться и отдохнуть, пока ваши гости не соберутся вокруг! Как только будет произведена новая регистрация, здесь появится информация о вашем госте. Вернитесь позже, чтобы отслеживать участников вашего мероприятия.",
  "You have no guests at the moment.": "У вас сейчас нет гостей.",
  "List of people who are registered to your event":
    "Список людей, зарегистрированных на ваше мероприятие",
  "Guest List": "Список гостей",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.":
    "Это повторяющееся событие! Любые изменения, внесенные в это событие, будут применены ко всем повторам.",
  "Repeated event": "Повторяющееся событие",
  "Delete Category": "Удалить категорию",
  "Do you really want to delete selected category? Once removed, cannot be undone.":
    "Вы действительно хотите удалить выбранную категорию? После удаления его невозможно отменить.",
  OK: "ХОРОШО",
  Exclude: "Исключать",
  "Custom recurrence": "Пользовательское повторение",
  Duplicate: "Дублировать",
  Delete: "Удалить",
  Published: "Опубликовано",
  Drafts: "Черновики",
  "User events": "Пользовательские события",
  "Add new category": "Добавить новую категорию",
  "Manage categories": "Управление категориями",
  "Add category": "Добавить категорию",
  Never: "Никогда",
  "Repeat every": "Повторяйте каждые",
  "Do you really want to delete selected event? Once removed, cannot be undone":
    "Вы действительно хотите удалить выбранное событие? После удаления его нельзя отменить.",
  "There are no categories yet": "Категорий пока нет",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.":
    "Внесение изменений в синхронизированный календарь с помощью следующих ссылок. Пожалуйста, внимательно просмотрите внесенные изменения.",
  occurrences: "явления",
  "Save as draft": "Сохранить как черновик",
  "More Info": "Больше информации",
  "Book Now": "Забронируйте сейчас",
  "Show participants": "Показать участников",
  "This service is fully booked.": "Эта услуга полностью забронирована.",
  "All sessions are fully booked.": "Все сессии полностью забронированы.",
  "Registration closed": "Регистрация закрыта",
  "Show your Wix Bookings or Events on Calendar":
    "Покажите свои бронирования или события Wix в календаре",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.":
    "Выберите Auto для автоматического отображения всех сервисов и сессий в календаре или руководство для ручного выбора.",
  "Show cancelled events": "Показать отмененные события",
  "Event Color": "Цвет событий",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.":
    "Выберите Auto для автоматического отображения всех событий в календаре или руководство для ручного выбора.",
  Auto: "Авто",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.":
    "Выберите Auto для автоматического отображения всех организаций и организаторов в календаре, или руководство для ручного выбора.",
  Manual: "Руководство",
  "Sync method": "Метод синхронизации",
  "Enable synchronization": "Включить синхронизацию",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only":
    "Продемонстрируйте фильтр категории вверху или в нижней части календаря. Настройки распространяются только на повестку дня, крест, график и представления карт",
  "Load Events": "Загрузить события",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.":
    "После включения ваш виджет календаря будет переведен на основе языка веб -сайта. Обратите внимание, что до тех пор, пока заголовки и описания календаря вводятся в виде текста, они не могут быть переведены.",
  "Choose plan type": "Выберите тип плана",
  "Api key": "API -ключ",
  "Synchronized Boxes": "Синхронизированные коробки",
  "Choose box": "Выберите коробку",
  "There are no synchronized boxes": "Нет синхронизированных коробок",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Синхронизация билета позволяет интегрировать ваши события и сеансы с календарем бумаги",
  Categories: "Категории",
  "Share this event": "Поделиться этим событием",
  Language: "Язык",
  "Show Time Zone": "Показать часовой пояс",
  "Custom Local Settings": "Пользовательские локальные настройки",
  "Add and showcase events on your site using a beautiful calendar.":
    "Добавляйте и демонстрируйте события на своем сайте, используя красивый календарь.",
  "Week Days": "Будние дни",
  "Manage Events": "Управление событиями",
  General: "Генеральный",
  "Layout Picker": "Выбор макета",
  Month: "Месяц",
  Monthly: "Ежемесячно",
  Week: "Неделя",
  Weekly: "Еженедельно",
  Day: "День",
  Daily: "Ежедневно",
  Agenda: "Повестка дня",
  "Navigation Buttons": "Кнопки навигации",
  "Week numbers": "Номера недели",
  "Include Weekends": "Включить выходные",
  "All-day": "Весь день",
  "All Day": "Весь день",
  Label: "Этикетка",
  "Fit to Height": "Подходит к высоте",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "Чтобы установить пропорции приложения, вручную отключите эту опцию и измените размер календаря в редакторе.",
  "Default Layout": "Макет по умолчанию",
  "Monthly view": "Ежемесячный просмотр",
  "Weekly and Daily view": "Еженедельный и ежедневный просмотр",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Вы можете дать посетителям более последовательный опыт, показывая одинаковое количество недель (6) за раз.",
  "Fixed Weekly Layout": "Фиксированный недельный макет",
  back: "назад",
  Row: "Строка",
  "Hours in Weekly View": "Часы в недельном обзоре",
  "Hours in Daily View": "Часы в ежедневном просмотре",
  Start: "Начало",
  End: "Конец",
  "At This Hour": "в этот час",
  Button: "Кнопка",
  Buttons: "Кнопки",
  Sunday: "Воскресенье",
  Monday: "Понедельник",
  Tuesday: "Вторник",
  Wednesday: "Среда",
  Thursday: "Четверг",
  Friday: "Пятница",
  Saturday: "Суббота",
  "Default Date": "Дата по умолчанию",
  year: "год",
  month: "месяц",
  mo: "месяц",
  days: "дней",
  ago: "тому назад",
  ahead: "впереди",
  Yesterday: "Вчера",
  Today: "Сегодня",
  Tomorrow: "Завтра",
  Custom: "Обычай",
  "Set Daily Rows Limit": "Установить дневной лимит строк",
  "Set Proportions": "Установите пропорции",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Разрешить посетителю добавлять события в локальные Calnedars: Google, Yahoo, Outlook, ICalendar.",
  Container: "Контейнер",
  Background: "Фон",
  "Container Background": "Фон Контейнерa",
  "Container Borders": "Контейнерные границы",
  Calendar: "Календарь",
  "Event Info Tooltip": "Информация о событии",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "Когда люди наводят курсор на событие, они видят всю информацию о нем во всплывающей подсказке.",
  "Event Info Window": "Окно информации о событии",
  "This is the full information window that opens when someone clicks on the event.":
    "Это окно полной информации, которое открывается, когда кто-то нажимает на событие.",
  "Use Gradient": "Использовать градиент",
  Vertical: "Вертикальный",
  Horizontal: "Горизонтальный",
  First: "Первый",
  Second: "Второй",
  diagonal: "Диагональ",
  Radial: "Радиальный",
  "Select option": "Выберите опцию",
  Solid: "Сплошной",
  Dotted: "Пунктирный",
  Dashed: "Пунктирная",
  Double: "Двойной",
  "Border Radius": "Пограничный радиус",
  Padding: "Ннабивка",
  "Date Header": "Заголовок даты",
  "Event Default Color": "Цвет события по умолчанию",
  "Days of Week": "Дни недели",
  "Days of Week Background": "Фон дней недель",
  Date: "Свидание",
  "Event Title": "Название события",
  "Highlight today": "Выделите сегодня",
  "Highlight Color": "Цвет подсветки",
  Hide: "Спрятать",
  "Calendar Border Color": "Цвет границы календаря",
  "Calendar Border Width": "Ширина границы календаря",
  "Calendar Border Style": "Стиль Границы Календаря",
  "Font Color": "Цвет шрифта",
  "Event Background": "Фон события",
  "Card Date Color": "Цвет даты карты",
  "Title Font": "Название шрифта",
  "Date Font": "Дата Шрифта",
  "Description Font": "Описание шрифта",
  "Button Background": "Фон кнопки",
  "Button Text": "Текст кнопки",
  "Border Color": "Цвет границы",
  "Border Width": "Ширина рамки",
  "Border Type": "Тип границы",
  Title: "Заглавие",
  Description: "Описание",
  "Background Color": "Фоновый цвет",
  Divider: "Делитель",
  "Event Details Font": "Событие Подробнее Шрифт",
  "Website Link Color": "Цвет Ссылки на Сайт",
  "Developer Info": "Информация про разработчиков",
  "User Guide": "Гид Пользователя",
  "Support e-mail": "Поддержка по e-mail",
  "Our Website": "Наш Сайт",
  "App Review": "Обзор приложения",
  "Enjoying App? Leave us a review in the App Market.":
    "Наслаждаешься приложением? Оставьте нам отзыв в App Market.",
  "Review Us": "Обзор",
  "Connect With Us": "Связаться с нами",
  "What's your email?": "Какой у тебя адрес электронной почты?",
  "Invalid email address!": "Неверный адрес электронной почты!",
  Comments: "Комментарии",
  "We'd love to hear from you. Send us a message.":
    "Мы хотели бы услышать от вас. Отправьте нам сообщение.",
  "Message must be at least 5 characters long":
    "Сообщение должно быть не менее 5 символов",
  Send: "Отправить",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Если вы хотите, чтобы пользователь мог переключаться между представлениями календаря, включите эту опцию и выберите представления, которые вы хотите показать.",
  Main: "Главный",
  Localize: "Локализировать",
  Settings: "Настройки",
  Layouts: "Макеты",
  Advanced: "Продвинутый",
  Design: "Дизайн",
  Support: "Служба поддержки",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Все локальные настройки (автоматически) основаны на вашем языке. Если ваш язык есть в списке, нет необходимости настраивать этот раздел.",
  "Date Format": "Формат даты",
  "Time Format": "Формат времени",
  "Text Direction": "Направление текста",
  "Left to Right": "Слева направо",
  "Right to Left": "Справа налево",
  "Week Starts On": "Неделя начинается",
  "Agenda Style": "Стиль Повестки дня",
  Classic: "Классический",
  Modern: "Современное",
  "Agenda Header": "Повестка дня",
  "Upcoming Events": "Предстоящие События",
  "Agenda Event Limit": "Предел Событий Повестки дня",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Обновите сейчас и получите гораздо больше возможностей и наслаждайтесь вашим приложением в полном объеме!",
  "Upgrade Now": "Обнови сейчас",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Хостинг событий, которые длятся весь день? Это позволяет вам показывать их в своем календаре",
  "24 hours": "24 часа",
  Sat: "Суб",
  Sun: "Вос",
  Mon: "Пон",
  Default: "Дефолт",
  "Select custom design style for your calendar.":
    "Выберите индивидуальный стиль дизайна для вашего календаря.",
  Style: "Стиль",
  "Styles and Colors": "Стили и Цвета",
  "Calendar Name": "Название календаря",
  "Write your Calendar name here": "Напишите здесь название вашего календаря",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Это не видно вашим пользователям. Задайте имена, чтобы дифференцировать календари при использовании функции синхронизации календаря Boom.",
  "General Info": "Главная информация",
  Venue: "Место встречи",
  Organizer: "Организатор",
  Search: "Поиск",
  "Add to": "Добавить в",
  calendar: "календарь",
  "Copy event URL": "Скопировать URL события",
  "Copied!": "Скопировано!",
  "Add & Share": "Добавить и поделиться",
  Map: "карта",
  "Calendar view": "Просмотр календаря",
  "Add Event": "Добавить событие",
  Uncategorised: "Без категории",
  More: "Больше",
  Less: "Меньше",
  Register: "регистр",
  Card: "Карта",
  Guests: "Гости",
  unlimited: "неограниченный",
  "Show more": "Показать больше",
  "Enable Search": "Включить поиск",
  "+ Add Event": "+ Добавить событие",
  "Manage and Sync": "Управление и синхронизация",
  "Show event details as...": "Показать детали события как ...",
  Tooltip: "подсказка",
  Popup: "Информационное поле",
  None: "Никто",
  "Show Category": "Показать категорию",
  "Header Align": "Выровнять заголовок",
  "Show Time": "Время для шоу",
  "Hours in Weekly/Daily View": "Часы в еженедельном / ежедневном просмотре",
  "Share Events": "Поделиться событиями",
  Shadow: "Тень",
  "Inner Padding": "Внутренняя обивка",
  Text: "Текст",
  "Active Button Border": "Граница активной кнопки",
  "Light Mode": "Легкий режим",
  "Event Text Color": "Цвет текста события",
  Dates: "Даты",
  Skeleton: "остов",
  "Skeleton Color": "Цвет скелета",
  Width: "Ширина",
  "Skeleton Style": "Ширина",
  Color: "Цвет",
  "Section Titles": "Заголовки разделов",
  "Section Content": "Содержание раздела",
  Header: "заголовок",
  Standard: "Стандарт",
  Retro: "Ретро",
  Silver: "Серебряный",
  Night: "Ночь",
  Dark: "Тьма",
  Aubergine: "Баклажан",
  "Map Header": "Заголовок карты",
  "Show Title in mobile": "Показать заголовок на мобильном устройстве",
  "Card View": "Карточка",
  "Card background color": "Цвет фона карты",
  "Title font": "Шрифт заголовка",
  "Desciption font": "Шрифт описания",
  "Section font": "Раздел шрифтов",
  "Section divider color": "Цвет разделителя секции",
  "Add event": "Добавить мероприятие",
  "All Day Event": "Событие на весь день",
  Location: "Место расположения",
  "Choose a category": "Выберите категорию",
  "Venue name": "Название объекта",
  "Venue phone": "Телефон места проведения",
  "Venue email": "Адрес места проведения",
  "Venue website": "Сайт объекта",
  "Organizer name": "Название организатора",
  "Organizer phone": "Телефон-органайзер",
  "Organizer email": "Электронная почта организатора",
  "Organizer website": "Сайт организатора",
  "Personal info": "Личная информация",
  "First name": "Имя",
  "Last name": "Фамилия",
  "Email Address": "Адрес электронной почты",
  "Additional Notes": "Дополнительные примечания",
  Back: "Назад",
  Save: "Сохранить",
  Next: "Следующий",
  "Your event has been submitted": "Ваше мероприятие отправлено",
  "Event submittion has been failed": "Отправка события не удалась",
  "e.g. Birthday Party": "например. День рождения",
  "First Name": "Имя",
  "Last Name": "Фамилия",
  "Phone Number": "Телефонный номер",
  Address: "Адрес",
  "Your comments": "Ваши комментарии",
  "How many guests?": "Сколько гостей?",
  "Anything else we need to know?": "Что-нибудь еще, что нам нужно знать?",
  "Guests:": "Гости:",
  Submit: "Разместить",
  "Go to Calendar": "Перейти в календарь",
  "Registration completed successfully!": "Регистрация прошла успешно!",
  "Please check your registered email address":
    "Пожалуйста, проверьте ваш зарегистрированный адрес электронной почты.",
  "Add to Calendar": "Добавить в календарь",
  "Share this Event": "Поделиться этим событием",
  "Sorry something went wrong": "Извините, что-то пошло не так",
  "Back to registration": "Повернутися до реєстрації",
  "Date & Location": "Дата и местоположение",
  "Date & Time": "Дата и время",
  home: "дома",
  "Header align": "Выровнять заголовок",
  Footer: "Нижний колонтитул",
  "Categories Filter": "категории Фильтр",
  "Show only upcoming": "Показать только предстоящие",
  "Card(s) in a row": "Карточка (ы) подряд",
  "Space between cards": "Расстояние между карточками",
  "Shown events limit": "Лимит показанных событий",
  "Style 1": "Стиль 1",
  "Style 2": "Стиль 2",
  "Style 3": "Стиль 3",
  "Style 4": "Стиль 4",
  "Buttons & Links": "Кнопки и ссылки",
  "Button corner radius": "Радиус угла кнопки",
  "Buttons font": "Шрифт кнопок",
  "Buttons background": "Кнопки фон",
  "Get notified by Email": "Получить уведомление по электронной почте",
  "Review events": "Обзор событий",
  "Click on date": "Нажмите на дату",
  "Add Event button": "Добавить кнопку события",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронизация календаря позволяет вам интегрировать ваши события и сеансы с вашим календарем Boom.",
  connect: "соединять",
  "Synchronized Calendars": "Синхронизированные календари",
  "Import events": "Импортировать события",
  Disconnect: "Отключить",
  "Choose calendar": "Выбрать календарь",
  "Monitor your Wix events through the sync feature":
    "Следите за своими событиями Wix с помощью функции синхронизации",
  "Connect all your Boom calendars available on your website":
    "Подключите все свои календари Boom, доступные на вашем сайте",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Планируйте, присоединяйтесь и управляйте собраниями Zoom прямо в нашем календаре Boom.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Следите за событиями Event Brite с помощью функции синхронизации Event Brite",
  Email: "Электронное письмо",
  "Add-ons": "Дополнения",
  "Receive notification emails as soon as users add events to your calendar.":
    "Получите уведомления писем, как только пользователи добавляют события в свой календарь.",
  "Enable + button on the calendar header":
    "Включить + кнопку на заголовке календаря",
  "Accept or decline events added by customers before making them public.":
    "Accept or decline events added by customers before making them public.",
  "Switch Add Event": "Переключатель Добавить событие",
  "Enable your browser cookies to connect to your account.":
    "Включите файлы файлов Browser для подключения к вашей учетной записи.",
  "Learn more": "Учить больше",
  "Print Button": "Tryckknapp",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Разрешите своим пользователям распечатать календарь событий Boom в любой диапазон даты.",
  "Show Title on mobile": "Показать название на мобильном",
  "Show Skeleton on mobile": "Показать скелет на мобильном",
  "Start 7-day Business trial": "Начните свой 7-дневный бизнес-проб",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Наслаждайтесь всеми неограниченными функциями, такими как билеты на продажу, регистрация, дополнение событий для посетителей.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Обратите внимание: в конце пробного периода вы будете возвращены в ваш существующий план подписки.",
  "Not Now": "Не сейчас",
  "Start free trial": "Начать бесплатную пробную версию",
  "Congrats!": "Поздравляю!",
  "Your 7-day Business trial has been successfully activated.":
    "Ваше 7-дневное деловое испытание было успешно активировано.",
  Done: "Готово",
  "Title font color": "Заголовок шрифта цвета",
  "Desciption font color": "Описание Цвет шрифта",
  "Section font color": "Раздел шрифта цвета",
  "Card Header": "Заголовок карты",
  Category: "Категория",
  "Display at the": "Отображать на то",
  top: "Топ",
  bottom: "Нижний",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Продемонстрируйте фильтр категории сверху или в нижней части календаря.Настройки применяются только к представлениям повестки дня и открытки",
  "Processing your events": "Обработка ваших событий",
  "Search for events": "Поиск событий",
  "There are no events added": "Нет добавленных событий",
  "Location: To be determined": "Расположение: быть определенным",
  "No events for selected date": "Нет событий для выбранной даты",
  Uncategorized: "Без рубрики",
  "Edit event": "Редактировать событие",
  "Edit original event": "Редактировать оригинальное событие",
  "Copy event": "Копировать событие",
  "Copy as new event": "Копировать как новое событие",
  "Delete event": "Удалить событие",
  "Stop repeating on this date": "Перестань повторять в эту дату",
  "Exclude this date": "Исключить эту дату",
  "Location is going to be announced": "Место будет объявлено",
  "Fill your personal information": "Заполните свою личную информацию",
  "Check Box": "Флажок",
  "Single Choice": "Один выбор",
  Option: "Вариант",
  "Share Event": "Поделиться событием",
  "Oops! Something went wrong": "Упс! Что-то пошло не так",
  "We are sorry this event has already taken place":
    "Мы сожалеем, что это событие уже произошло",
  "Back to calendar": "Вернуться к календарю",
  "This field is required": "Это поле обязательно к заполнению",
  Phone: "Телефон",
  "Number field": "Поле числа",
  "Please provide a valid email":
    "Пожалуйста, предоставьте действительный адрес электронной почты",
  "Select at least one option": "Выберите хотя бы один вариант",
  "Choose tickets to see total value":
    "Выберите билеты, чтобы увидеть общую стоимость",
  tickets: "Билеты",
  "Choose Tickets": "Выберите билеты",
  "Choose payment method": "выберите способ оплаты",
  Pay: "Платить",
  Total: "Общее",
  Free: "Бесплатно",
  "Buy tickets": "Купить билеты",
  "Sold Out": "Распроданный",
  "Tickets are available": "Билеты доступны",
  "Sales End": "Продажи конец",
  "Availible from": "Доступна с",
  "Go to Orders": "Перейти к заказу",
  "Go to Details": "Перейти к деталям",
  "Group ticket": "Групповой билет",
  Name: "Имя",
  Price: "Цена",
  "Order by": "Сортировать по",
  "Order ID": "номер заказа",
  Applied: "Применяемый",
  Fees: "Сборы",
  "Enter promo code": "Введите промо-код",
  Apply: "Применять",
  "Promo Code": "Промо код",
  Cash: "Денежные средства",
  "You can find your e-tickets attached to your email or download them":
    "Вы можете найти свои электронные билеты, прикрепленные к вашей электронной почте или загрузить их",
  here: "здесь",
  Time: "Время",
  "Invalid promo code": "Неверный промо -код",
  "Credit card": "Кредитная карта",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Вскоре вы получите подтверждающее сообщение об успешной регистрации на свой адрес электронной почты.",
  "You can also check your order details below.":
    "Вы также можете проверить данные вашего заказа ниже.",
  at: "в",
  Buy: "Купить",
  Donation: "Пожертвование",
  "Enter price": "Предприятие",
  Choose: "Выбирать",
  Chosen: "Выбранный",
  "Choose your plan": "Выберите свой план",
  week: "неделя",
  wk: "неделя",
  "Choose plan cycle": "Выберите цикл плана",
  months: "месяцы",
  years: "годы",
  weeks: "недели",
  "Copy Event Url": "Копировать URL",
  "You can find your e-tickets attached to your email or print them":
    "Вы можете найти свои электронные билеты, прикрепленные к вашей электронной почте или распечатать их",
  "Guest Info": "Информация гостя",
  "Ticket Info": "Информация о билете",
  "Ticket name": "Название билета",
  "Ticket price": "Стоимость билета",
  "Ticket ID": "Билет идентификатор",
  "If you have any questions contact to organizer":
    "Если у вас есть какие -либо вопросы, свяжитесь с организатором",
  "As soon as event ends": "Как только событие заканчивается",
  "1 day after event ends": "Через 1 день после окончания события",
  "7 days after event ends": "7 дней после окончания события",
  "14 days after event ends": "Через 14 дней после окончания события",
  "30 days after event ends": "Через 30 дней после окончания события",
  Menu: "Меню",
  "No event for selected date": "Нет события для выбранной даты",
  view: "вид",
  List: "Список",
  Year: "Год",
  Yearly: "Ежегодно",
  "Year view header": "Год просмотра заголовок",
  "Yearly Style": "Годовой стиль",
  "There are no events": "Нет событий",
  Autotranslation: "Автотрансляция",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "После включения ваш виджет календаря будет переведен на основе языка веб-сайта.* Обратите внимание, что до тех пор, пока заголовок календаря и описания введены тексты, которые они не могут быть переведены.",
  "Note on mobile": "Примечание на мобильном телефоне",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Выключите или измените текст бара «Нет событий» на мобильной версии календаря",
  Autodeletion: "Автоделеция",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Включение опции автоматически удалит ваши прошлые события из календаря.",
  "This does not apply to repeating events!":
    "Это не относится к повторяющимся событиям!",
  "Notify event creators about the guest": "Уведомлять пользователей о гостях",
  "Send event creators notification emails as soon as guests register for their events":
    "Отправляйте создателям мероприятий уведомления по электронной почте, как только гости зарегистрируются на их мероприятия",
  "List View Type": "Список просмотра списка",
  "Description font": "Шрифт описания",
  Connect: "соединять",
  "You have no events": "У вас нет событий",
  Synchronize: "Синхронизировать",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Sync Calendar Google позволяет интегрировать свои события и сеансы с вашим календарем Boom.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Синхронизация календаря Outlook позволяет интегрировать ваши события и сеансы с вашим календарем Boom.",
  "Your message has been sent successfully!":
    "Ваше сообщение было отправлено успешно!",
  "There are no synchronized calendars":
    "Там нет синхронизированных календарей",
  "to view more than 7 events": "Для просмотра более 7 событий",
  "Mobile app": "Мобильное приложение",
  "Admin Account": "Администраторная учетная запись",
  Password: "Пароль",
  "Second User": "Второй пользователь",
  Edit: "Редактировать",
  "Guest limit": "Гостевой предел",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Все локальные настройки (автоматически) основаны на вашем языке.Если ваш язык находится в списке, нет необходимости настроить этот раздел.",
  available: "имеется в наличии",
  next: "следующий",
  Tickets: "Билеты",
  Quantity: "Количество",
  "Promo code": "Промо код",
  "Select a payment method": "Выберите способ оплаты",
  Fee: "Платеж",
  Book: "Книга",
  "All the tickets have been sold out": "Все билеты были распроданы",
  "Choose at least one ticket": "Выберите хотя бы один билет",
  "First choose ticket": "Сначала выберите Билет",
  "Please fill out your personal information.":
    "Пожалуйста, заполните свою личную информацию.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "Чтобы сделать успешную покупку, пожалуйста, выберите свой предпочтительный способ оплаты и введите промо-код для дисконтированных билетов.",
  "Credit/Debit card": "Кредитная / дебетовая карта",
  "print here.": "Распечатайте здесь.",
  "QR code for all tickets": "QR-код для всех билетов",
  Duration: "Продолжительность",
  "Full Name": "ФИО",
  "Ticket id": "Идентификатор билета",
  "Group id": "Групповой идентификатор",
  "Choose your ticket.": "Выберите свой билет.",
  "Fill out your personal information.": "Заполните свою личную информацию.",
  "Add the payment details.": "Добавьте детали платежей.",
  "To be determined": "Быть определенным",
  "You can find your e-tickets attached to the email or":
    "Вы можете найти свои электронные билеты, привязанные к электронной почте или",
  "print here": "Распечатайте здесь",
  "Full name": "ФИО",
  "Group ID": "Групповой идентификатор",
  "to Book": "бронировать",
  "Unfortunately, your card has been declined":
    "К сожалению, ваша карта была отклонена",
  "Thank you for your purchase!": "Спасибо за покупку!",
  "Find your printable e-tickets attached to the confirmation email":
    "Найдите свои печатные электронные билеты, прикрепленные к электронной почте с подтверждением",
  Confirm: "Подтверждать",

  "Add event": "Добавить событие",
  Events: "События",
  "Event details": "Детали события",
  Registration: "Постановка на учет",
  "Guests list": "Список гостей",
  Ticket: "Билет",
  "General Info": "Главная информация",
  "Customize the general settings of your event":
    "Настройте общие настройки вашего мероприятия",
  "Event Title": "Название мероприятия",
  "e.g. Birthday Party": "например Вечеринка в честь дня рождения",
  "All Day Event": "Событие на весь день",
  Cross: "Крест",
  Timeline: "График",
  "Repeating event": "Повторяющее событие",
  Location: "Расположение",
  "Venue name": "Название места",
  Description: "Описание",
  Image: "Изображение",
  Color: "Цвет",
  Category: "Категория",
  "Add your events to color categories and let your users classify them easily":
    "Добавьте свои события в цветные категории и позвольте вашим пользователям легко их классифицировать",
  "Category name": "Название категории",
  "e.g. Birthdays": "например Дни рождения",
  Venue: "Место проведения",
  "Where the event takes place": "Где происходит мероприятие",
  "Venue name": "Название места",
  "Venue phone": "Проникновение телефона",
  "Venue email": "Электронная почта места",
  "Venue website": "Сайт места проведения",
  Organizer: "Организатор",
  "Person who makes the event": "Человек, который совершает мероприятие",
  "Organizer name": "Название организатора",
  "Organizer phone": "Организатор телефон",
  "Organizer email": "Организатор Электронная почта",
  "Organizer website": "Сайт организатора",
  Save: "Сохранять",
  Cancel: "Отмена",
  Import: "Импортировать",
  Past: "Прошлое",
  All: "Все",
  Upcoming: "Предстоящий",
  Uncategorised: "Без категории",
  "Date Ascending": "Дата восхождения",
  "Date Descending": "Дата спуска",
  "Title by A-Z": "Название A-Z",
  "Title by Z-A": "Название Z-A",
  "There are no events for this period": "В этот период нет событий",

  "Auto-Convert Date & Time": "Auto-Convert Date & Time",
  TimeZone: "Часовой пояс",
  Autodeletion: "Автоделеция",
  "Layout Settings": "Настройки макета",
  "Yeatly view": "Yeatly смотрит",
  "Monthly view header": "Ежемесячный заголовок",
  "Weekly/Daily view header": "Heverly/Daily View Header",
  Acendings: "Акцент",
  Descending: "Нисходящий",
  Standart: "Standart",
  Silver: "Серебро",
  Retro: "Ретро",
  Dark: "Темный",
  Night: "Ночь",
  Aubergine: "Aubergine",
  "List view header": "Список заголовок просмотра",
  "Side by Side View": "Бок о бок вид",
  "Customize Proportions": "Настройте пропорции",
  "Card Margins": "Карточная маржа",
  "Image opacity (%)": "Опрошение изображения (%)",
  "Side by Side Header": "Бок рядом",
  "Text Align": "Текст выравнивается",
  "Timeline View": "Временный вид",
  "Title font color": "Заголовок шрифт цвет",
  "Desciption font color": "Цвет шрифта",
  "Line color": "Линейный цвет",
  "Date Font color": "Дата цвет шрифта",
  "Daily events background": "Ежедневные события",
  Alignment: "Выравнивание",
  Vertical: "Вертикальный",
  Horizontal: "Горизонтальный",
  "Vertical Alignment": "Вертикальное выравнивание",
  Right: "Верно",
  Center: "Центр",
  "Horizontal Alignment": "Горизонтальное выравнивание",
  Top: "Вершина",
  Center: "Центр",
  Bottom: "Нижний",
  "Dates Circle Design": "Даты круга дизайна",
  "Next To The Circle": "Рядом с кругом",
  "In The Circle": "В кругу",
  "Timeline Header": "Временная шкала",
  Timeline: "График",
  "Show only upcoming": "Показать только грядущий",
  "Order by": "Сортировать по",
  "Timeline Event Limit": "Ограничение события временной шкалы",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Позвольте посетителю добавить мероприятие в местных кальнаров: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Разрешить посетителю поделиться вашим мероприятием в Facebook, LinkedIn, Twitter и т. Д.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Добавьте опцию поиска в свой календарь, чтобы позволить людям искать ваши события по заголовке, месту встречи и т. Д.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Позвольте вашим пользователям распечатать календарь событий Boom в любом диапазоне дат.",
  "Click to apply a theme to Calendar":
    "Нажмите, чтобы применить тему в календарь",
  "Date container color": "Дата контейнер цвет",
  "Daily events background": "Ежедневные события",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Используйте надстройки, чтобы установить расширенные функции в календарях, что делает их более функциональными!",
  "Open Add-ons Store": "Открыть магазин Addons",
  Monday: "Понедельник",
  Tuesday: "Вторник",
  Wednesday: "Среда",
  Thursday: "Четверг",
  Friday: "Пятница",
  Saturday: "Суббота",
  Sunday: "Воскресенье",
  "Yearly view": "Ежегодный вид",
  Ascending: "Восходящий",
  "Show event time next to title": "Показать время события рядом с заголовком",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Отрегулируйте дату и время события в локальное время пользователя в зависимости от их часового пояса.",
  "Display the time zone alongside the event date.":
    "Отобразить часовой пояс вместе с датой события.",
  "Show event time next to title": "Показать время события рядом с заголовком",
  "Time Zone": "Часовой пояс",
  "Upload Image": "Загрузить изображение",
  "Choose a Category": "Выберите категорию",
  "Color you have chosen will not be shown as you choose category":
    "Цвет, который вы выбрали",
  Website: "Веб-сайт",
  Next: "Следующий",
  Save: "Сохранять",
  "Last Name": "Фамилия",
  "Personal Info": "Личная информация",
  Back: "Назад",
  "This field is required": "Это поле обязательно к заполнению",
  "Your event has been submitted": "Ваше мероприятие было представлено",
  "Enter a location": "Введите место",
  "Display the time zone alongside the event date.":
    "Отобразить часовой пояс вместе с датой события.",
  Home: "Дом",
  "Side By Side Event Limit": "Бок рядом с ограничением события",
  "Mobille App": "Мобильное приложение",
  category: "категория",
  Add: "Добавлять",
  username: "имя пользователя",
  password: "пароль",
  "Connect all your Boom calendars available on your website.":
    "Подключите все ваши календари бума, доступные на вашем сайте.",
  "Monitor your Wix events through the sync feature.":
    "Следите за своими событиями WIX через функцию синхронизации.",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Легко отслеживайте свое расписание, импортируя события из Facebook в свой календарь.",
  "Synchronized Pages": "Синхронизированные страницы",
  "There are no synchronized pages": "Нет синхронизированных страниц",
  "Choose page": "Выберите страницу",
  "You have no events": "У тебя нет событий",
  "Add Script": "Добавить скрипт",
  "script bound": "Этот скрипт уже связан, выберите другие данные!",
  "Choose account": "Выберите аккаунт",
  "Choose resource": "Выберите ресурс",
  "Reconnect": "Восстановить связь",
  "script disappear": "Этого сценария не существует, пожалуйста, добавьте скрипт в свою Google Analytics!",
};
export default ru;
