let sv = {
  "Automatically approve events from these addresses": "Godkänn automatiskt händelser från dessa adresser",
  "Approve events": "Godkänn evenemang",
  "Payable with a plan": "Betalas med plan",
  "Service Details": "Servicedetaljer",
  "participants": "deltagare",
  "To": "Till",
  "From": "Från",
  "Ahead": "Framåt",
  "Ago": "Sedan",
  "Change the category": "Ändra kategori",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar.": "Ticket Tailor sync låter dig integrera dina evenemang och sessioner med din Boom-kalender.",
  "Show event time next to title. This setting is only applicable to the Monthly, Daily, and Weekly views.": "Visa händelsetid bredvid titeln. Den här inställningen är endast tillämplig på vyerna Månatlig, Daglig och Veckovis.",
  "Show Staff Member": "Visa personalmedlem",
  "Show Price": "Visa pris",
  "To Event Page": "Till evenemangssidan",
  "Layout": "Layout",
  "Acending": "Acending",
  "Yearly": "Årlig",
  "Layout device": "Layoutenhet",
  "Date container font": "Teckensnitt för datumbehållare",
  "Hide Fully Booked Slots": "Göm fullbokade spelautomater",
  "Enable": "Gör det möjligt",
  "Limit": "Begränsa",
  "Export": "Exportera",
  "You are about to change the details of your event. Once changed, your guest list will be lost.": "Du är på väg att ändra detaljerna för ditt evenemang. När den har ändrats kommer din gästlista att gå förlorad.",
  "Change Date": "Byt datum",
  "Ends": "Slutar",
  "On": "På",
  "After": "Efter",
  "Accept": "Acceptera",
  "Show less": "Visa mindre",
  "Venue detail": "Lokal detalj",
  "Reject": "Avvisa",
  "See guest list": "Se gästlista",
  "Submit Date": "Inlämningsdatum",
  "Total guests": "Totalt gäster",
  "Do you really want to delete selected user? Once removed, cannot be undone.": "Vill du verkligen ta bort den valda användaren? När den har tagits bort kan den inte ångras.",
  "Delete Guest": "Ta bort gäst",
  "Invoice number": "Fakturanummer",
  "Status": "Status",
  "Payment type": "Betalnings typ",
  "Select payment method to receive fees through tickets": "Välj betalningsmetod för att få avgifter via biljetter",
  "Add Code": "Lägg till kod",
  "Add End Time": "Lägg till sluttid",
  "Discount": "Rabatt",
  "Promo codes for the sales": "Kampanjkoder för försäljningen",
  "Promo codes": "Kampanjkoder",
  "Add Ticket": "Lägg till biljett",
  "Limit type": "Begränsningstyp",
  "Paid": "Betalt",
  "Participation tickets for your event": "Deltagarbiljetter till ditt event",
  "Show the ticket limit": "Visa biljettgränsen",
  "Show limit": "Visa gräns",
  "Show the price on ticket": "Visa priset på biljetten",
  "Enable and configure your ticketing system": "Aktivera och konfigurera ditt biljettsystem",
  "Stop repeating here": "Sluta upprepa här",
  "Limited": "Begränsad",
  "Unlimited": "Obegränsat",
  "Thank you message title": "Tack meddelande rubrik",
  "Submit button text": "Skicka knapptext",
  "Registration button text": "Text för registreringsknapp",
  "Texts": "Texter",
  "Modify the displayed texts": "Ändra de visade texterna",
  "Thank you message body": "Tack meddelandetexten",
  "Notify the user when the registration is canceled": "Meddela användaren när registreringen avbryts",
  "Cancellation email": "Avbokning e-post",
  "Send a reminder to the user one day prior to the event": "Skicka en påminnelse till användaren en dag innan evenemanget",
  "Reminder email": "Påminnelsemail",
  "Send an instant email to the user once registration is completed": "Skicka ett omedelbart e-postmeddelande till användaren när registreringen är klar",
  "Notification email": "E-postmeddelande",
  "Reminder email about the event": "Påminnelsemail om evenemanget",
  "Email notifications to users": "E-postmeddelanden till användare",
  "Click on the toggle buttons next to each field to add it to your registration form. If you want to make the field required, click on the asterisk (*).": "Klicka på växlingsknapparna bredvid varje fält för att lägga till det i ditt registreringsformulär. Om du vill göra fältet obligatoriskt, klicka på asterisken (*).",
  "Form Fields": "Formulärfält",
  "Enter your form description": "Ange din formulärbeskrivning",
  "Form Title": "Formulärtitel",
  "Enter your form title": "Ange din formulärrubrik",
  "Form Details": "Formdetaljer",
  "Configure your registration form fields": "Konfigurera dina registreringsformulärfält",
  "Show guest limit": "Visa gästgräns",
  "Enable Registration": "Aktivera registrering",
  "Click to activate registration on this event": "Klicka för att aktivera registrering på detta evenemang",
  "Customize the general settings of registration": "Anpassa de allmänna inställningarna för registrering",
  "Enter URL": "Skriv in URL",
  "Page URL": "Sidans URL",
  "Close registration when the event starts": "Stäng anmälan när eventet startar",
  "Redirect to a different website": "Omdirigera till en annan webbplats",
  "Where users can register": "Där användare kan registrera sig",
  "Open event registration landing page": "Öppna målsidan för eventregistrering",
  "It must have taken you plenty of preparation to get ready for your event. Now is the time to sit back and relax till your guests gather around! As soon as a new registration is made, the information about your guest will appear here. Come back later to keep track of your event attendees.": "Det måste ha tagit dig massor av förberedelser för att göra dig redo för ditt evenemang. Nu är det dags att luta sig tillbaka och koppla av tills dina gäster samlas runt! Så fort en ny registrering är gjord kommer informationen om din gäst att dyka upp här. Kom tillbaka senare för att hålla reda på dina eventdeltagare.",
  "You have no guests at the moment.": "Du har inga gäster för tillfället.",
  "List of people who are registered to your event": "Lista över personer som är registrerade på ditt evenemang",
  "Guest List": "Gästlista",
  "This is a recurring event! Any changes made to this event, will be applied to all repetitions.": "Detta är en återkommande händelse! Alla ändringar som görs i detta evenemang kommer att tillämpas på alla repetitioner.",
  "Repeated event": "Upprepad händelse",
  "Delete Category": "Ta bort kategori",
  "Do you really want to delete selected category? Once removed, cannot be undone.": "Vill du verkligen ta bort den valda kategorin? När den har tagits bort kan den inte ångras.",
  "OK": "OK",
  "Exclude": "Utesluta",
  "Custom recurrence": "Anpassad upprepning",
  "Duplicate": "Duplicera",
  "Delete": "Radera",
  "Published": "Publicerad",
  "Drafts": "Utkast",
  "User events": "Användarhändelser",
  "Add new category": "Lägg till ny kategori",
  "Manage categories": "Hantera kategorier",
  "Add category": "Lägg till Kategori",
  "Never": "Aldrig",
  "Repeat every": "Upprepa varje",
  "Do you really want to delete selected event? Once removed, cannot be undone": "Vill du verkligen ta bort vald händelse? När den har tagits bort kan den inte ångras",
  "There are no categories yet": "Det finns inga kategorier än",
  "Making Changes to your synced calendar with the following links. Please review your changes carefully.": "Göra ändringar i din synkroniserade kalender med följande länkar. Vänligen granska dina ändringar noggrant.",
  "occurrences": "händelser",
  "Save as draft": "Spara som utkast",
  "More Info": "Mer information",
  "Book Now": "Boka nu",
  "Show participants": "Visa deltagare",
  "This service is fully booked.": "Den här tjänsten är fullbokad.",
  "All sessions are fully booked.": "Alla sessioner är fullbokade.",
  "Registration closed": "Registrering stängd",
  "Show your Wix Bookings or Events on Calendar": "Visa dina WIX -bokningar eller evenemang på kalendern",
  "Choose Auto for automatic display of all services and sessions on the calendar, or Manual for manual selection.": "Välj Auto för automatisk visning av alla tjänster och sessioner i kalendern eller manualen för manuell val.",
  "Show cancelled events": "Visa avbrutna händelser",
  "Event Color": "Evenemangsfärg",
  "Choose Auto for automatic display of all events on the calendar, or Manual for manual selection.": "Välj Auto för automatisk visning av alla händelser i kalendern eller manualen för manuell val.",
  "Auto": "Bil",
  "Choose Auto for automatic display of all organizations and organizers on the calendar, or Manual for manual selection.": "Välj Auto för automatisk visning av alla organisationer och arrangörer i kalendern eller manualen för manuell val.",
  "Manual": "Manuell",
  "Sync method": "Synkroniseringsmetod",
  "Enable synchronization": "Aktivera synkronisering",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda, Cross, Timeline and Card views only": "Visa upp kategorifiltret längst upp eller längst ner i kalendern. Inställningarna gäller endast för agenda, kors, tidslinje och kortvyer",
  "Load Events": "Belastningshändelser",
  "Once enabled, your calendar widget will be translated based on the website’s language. Please note that as long as calendar titles and descriptions are entered as text, they cannot be translated.":
    "När du är aktiverad kommer din kalenderwidget att översättas baserat på webbplatsens språk. Observera att så länge kalendertitlar och beskrivningar matas in som text kan de inte översättas.",
  "Choose plan type": "Välj Plan Type",
  "Api key": "API -nyckel",
  "Synchronized Boxes": "Synkroniserade lådor",
  "Choose box": "Välj låda",
  "There are no synchronized boxes": "Det finns inga synkroniserade rutor",
  "Ticket Tailor sync allows you to integrate your events and sessions with your Boom Calendar":
    "Ticket Faror Sync låter dig integrera dina evenemang och sessioner med din bomkalender",
  Language: "Språk",
  "Show Time Zone": "Visa tidszon",
  "Custom Local Settings": "Anpassa lokala inställningar",
  "Add and showcase events on your site using a beautiful calendar.":
    "Lägg till och visa evenemang på din hemsida med den här vackra kalendern.",
  "Week Days": "Veckodagar",
  "Manage Events": "Hantera evenemang",
  General: "Allmänt",
  "Layout Picker": "Välj layout",
  Month: "Månad",
  Monthly: "Månadsvis",
  Week: "Vecka",
  Weekly: "Veckovis",
  Day: "Dag",
  Daily: "Dagsvis",
  Agenda: "Agenda",
  "Navigation Buttons": "Navigeringsknappar",
  "Week numbers": "Veckonummer",
  "Include Weekends": "Inkludera helgdagar",
  "All-day": "Hela dagen",
  "All Day": "Hela dagen",
  Label: "Märka",
  "Fit to Height": "Anpassa höjd",
  "To set App proportions manully disable this option and resize Calendar in Editor.":
    "För att manuellt ställa in proportioner i Appen inaktivera detta alternativ. Ändra istället i kalenderns Editor.",
  "Default Layout": "Förinställd layout",
  Monthlyview: "Visa månadsvis",
  "Weekly and Daily view": "Visa vecka och dag",
  "You can give visitors a more consistent experience by showing the same number of weeks(6) at a time.":
    "Du kan ge besökarna en mer koncis överblick genom att varje gång visa samma antal veckor (6).",
  "Fixed Weekly Layout": "Fast visning av veckor",
  back: "Tillbaka",
  Row: "Rad",
  "Hours in Weekly View": "Tider visas per vecka",
  "Hours in Daily View": "Tider visas per dag",
  Start: "Start",
  End: "Slut",
  "At This Hour": "På denna timme",
  "Card(s) in a row ": "Antal kort bredvid varandra",
  "Space between cards ": "Avstånd mellan kort",
  "Shown events’ limit ": "Maxantal evenemang som visas",
  "Show only upcoming ": "Visa bara planerade",
  "Add to": "Lägg till",
  Button: "Knapp",
  Buttons: "Knappar",
  Sunday: "Söndag",
  Monday: "Måndag",
  Tuesday: "Tisdag",
  Wednesday: "Onsdag",
  Thursday: " Torsdag ",
  Friday: "Fredag",
  Saturday: "Lördag",
  "Default Date": "Förinställt datum",
  year: " år ",
  month: " månad ",
  mo: " månad ",
  days: " Dagar ",
  ago: " sedan ",
  ahead: " framöver",
  Yesterday: "Igår",
  Today: "Idag",
  Tomorrow: "Imorgon",
  Custom: "Anpassa",
  "Set Daily Rows Limit": "Ställ in radantal per dag",
  SetProportions: "Ställ in proportioner",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Tillåt besökare lägga till evenemang i sin kalender: Google, Yahoo, Outlook, ICalendar.",
  Container: "Kalenderyta",
  "Add to…Button ": "Knapp – Dela i egen kalender",
  Background: "Bakgrund",
  "Container Background": "Kalenderytans bakgrund ",
  "Container Borders": "Kalenderytans kantlinjer",
  Calendar: "Kalender",
  "Event Info Tooltip": "Information om evenemanget ",
  "When people hover over an event they’ll see all the info about it in a tooltip.":
    "När någon håller muspekaren över ett evenemang presenteras informationen i ett informationsfönster.",
  "Event Info Window": "Evenemangets informationsfönster",
  "This is the full information window that opens when someone clicks on the event.":
    "Detta är det fullständiga informationsfönstret som öppnas när någon klickar på evenemanget.",
  "Use Gradient": "Använd lutning",
  Vertical: "Vertikal",
  Horizontal: "Horisontell",
  First: "Först",
  Second: "Andra",
  diagonal: " diagonal ",
  Radial: "Avstånd mellan hörn ",
  "Select option": "Välj alternativ",
  Solid: "Heldragen",
  Dotted: "Prickad",
  Dashed: "Streckad",
  Double: "Dubbel",
  "Border Radius": "Border Radius",
  Padding: "Stoppning",
  "Date Header": "Rubrikdatum",
  "Event Default Color": "Förinställd färg – Evenemang",
  "Days of Week": "Veckodagar",
  "Days of Week Background": "Bakgrund – Veckodagar",
  Date: "Datum",
  "Event Title": "Evenemangstitel ",
  "Highlight today": "Markera idag",
  "Highlight Color": "Markera färg",
  Hide: "Dölj",
  "Calendar Border Color": "Färg - Kalenderns kantlinjer",
  "Calendar Border Width": "Bredd - Kalenderns kantlinjer",
  "Calendar Border Style": "Stil - Kalenderns kantlinjer",
  "Font Color": "Färg - Teckensnitt ",
  "Event Background": "Bakgrund - Evenemang",
  "Card Date Color": "Färg - Kortdatum",
  "Title Font": "Teckensnitt - Titel",
  "Date Font": "Teckensnitt - Datum",
  "Description Font": "Teckensnitt - Beskrivning",
  "Button Background": "Bakgrund - Knapp",
  "Button Text": "Text - Knapp",
  "Border Color": "Färg - Kantlinjer",
  "Border Width": "Bredd - Kantlinjer",
  "Border Type": "Typ - Kantlinjer",
  Title: "Titel",
  Description: "Beskrivning",
  "Background Color": "Bakgrundsfärg",
  Divider: "Avskiljare",
  "Event Details Font": "Teckensnitt - Detaljbeskrivning evenemang",
  "Website Link Color": "Färg - Länk hemsida",
  "Developer Info": "Information för utvecklare",
  "User Guide": "Bruksanvisning",
  "Support e-mail": "Support e-post",
  "Our Website": "Vår hemsida",
  "App Review": "Applikationsrecension",
  "Enjoying App? Leave us a review in the App Market.":
    "Gillar du Appen? Skriv en recension i App Market.",
  "Review Us": "Skriv en recension om oss",
  "Connect With Us": "Ta kontakt med oss",
  "What's your email?": "Din e-postadress?",
  "Invalid email address!": "Ogiltig e-postadress! ",
  Comments: "Kommentarer",
  "We'd love to hear from you. Send us a message.":
    "Du får gärnakontakta oss. Skicka oss ett meddelande.",
  "Message must be at least 5 characters long":
    "Meddelandet måste innehålla minst 5 tecken",
  Send: "Skicka",
  "If you want to allow user to switch between calendar views, enable this option and choose the views you want to show.":
    "Låt användaren växla mellan olika kalenderutseenden genom att aktivera detta alternativ. Välj önskat utseende.",
  Main: "Huvudmeny",
  Localize: "Lokalisera",
  Settings: "Inställningar",
  Layouts: "Olika layout",
  Advanced: "Avancerat",
  Design: "Design",
  Support: "Support",
  "All the local settings are (automatically) based on your language. If your language is on the list, there's no need to customize this section.":
    "Alla lokala inställningar anpassas automatiskt efter språkval. Om språket finns i språklistan behövs inga ytterligare inställningar i det här avsnittet.",
  "Date Format": "Datumformat",
  "Time Format": "Tidsformat",
  "Text Direction": "Textriktning",
  "Left to Right": "Vänster tillhöger",
  "Right to Left": "Höger till vänster",
  "Week Starts On": "Veckan börjar på",
  "Agenda Style": "Stil - Agenda",
  Classic: "Klassisk",
  Modern: "Modern",
  "Agenda Header": "Rubrik - agenda ",
  "Upcoming Events": "Planerade evenemang",
  "Agenda Event Limit": "Evenemangsbegränsningar",
  "Upgrade now and get a lot more features and enjoy your APP in full!":
    "Uppgradera nu och få tillgång till fler funktioner och nyttja vår App fullt ut!",
  "Upgrade Now": "Uppgradera nu",
  "Hosting events that last allday? This lets you show them on your calendar.":
    "Varar bokat evenemang en hel dag? Då kan du visa evenemanget i din kalender.",
  "24 hours": "24 timmar",
  Sun: "Sön",
  Mon: "Mån",
  Sat: "Lör",
  Default: "Standard",
  "Select custom design style for your calendar.":
    "Välj och anpassa kalenders design.",
  Style: "Stil",
  "Styles and Colors": "Stilar och färger",
  "Calendar Name": "Kalendernamn",
  "Write your Calendar name here": "Skriv ditt kalendernamn här",
  "Enable Search": "Aktiverasökning",
  "This is not visible to your users. Set names to differentiate your calendars when using the Boom Calendar Sync function.":
    "Detta är inte synligt för dina användare. Välj olika namn för att särskilja kalendrar när ’Boom Calendar Sync’ används.",
  "+ Add Event": "+ Lägg till händelse",
  "Manage and Sync": "Hantera och Sync",
  "Show event details as...": "Visa evenemangsdetaljer som...",
  Tooltip: "Användartips",
  Popup: "Informationsruta",
  None: "Ingen",
  "Show Category": "Visa kategori",
  "Header Align": "Justera rubrik",
  "Show Time": "Visa tid",
  "Hours in Weekly/Daily View": "Visa öppettider vecka/dag ",
  "Share Events": "Delaevenemang",
  Shadow: "Skugga",
  "Inner Padding": "Inre utfyllnad",
  Text: "Text",
  "Active Button Border": "Kantlinje - Aktiv knapp",
  "Light Mode": "Ljus inställning",
  "Event Text Color": "Färg - Evenemangstext",
  Dates: "datum",
  Skeleton: "Rutmönster",
  "Skeleton Color": "Färg - Rutmönster ",
  Width: "Bredd",
  "Skeleton Style": "Stil - Rutmönster",
  Color: "Färg",
  "Section Titles": "Avsnittstitlar",
  "Section Content": "Avsnittsinnehåll",
  Header: "Rubrik",
  "Map Header": "Karthuvud",
  Map: "Karta",
  Standard: "Standard",
  Retro: "Retro",
  Silver: "Silver",
  Night: "Natt",
  Dark: "Mörk",
  Aubergine: "Aubergine",
  "Show Title in mobile": "Visa titel i mobilen",
  Card: "Kort",
  "Card View": "Visning - Kort",
  "Card background color": "Bakgrundsfärg - Kort",
  "Title font": "Teckensnitt - Titel ",
  "Desciption font": "Teckensnitt - Beskrivning ",
  "Section font": "Teckensnitt - Avsnitt",
  "Section divider color": "Färg - Avsnittsavskiljare",
  "General Info": "Generell information",
  Venue: "Mötesplats",
  Organizer: "Arrangör",
  Search: "Sök",
  calendar: "kalender",
  "Copy event URL": "Kopier URL-adresse",
  "Copied!": "Kopiert!",
  "Add & Share": "Lägg till och dela",
  "Calendar view": "Kalendervy",
  "Add Event": "Lägg till händelse",
  Uncategorised: "Okategoriserad",
  More: "Mer",
  Less: "Mindre",
  Register: "Registrera",
  Guests: "Gäster",
  unlimited: "obegränsat",
  "Show more": "Visa mer",
  Categories: "Kategorier",
  "Share this event": "Поделиться этим событием",
  "Add event": "Lägg till händelse",
  "All Day Event": "Heldagsevent",
  Location: "Plats",
  "Choose a category": "Välj en kategori",
  "Venue name": "Platsnamn",
  "Venue phone": "Lokaltelefon",
  "Venue email": "E-postadress",
  "Venue website": "Platswebbplats",
  "Organizer name": "Arrangörens namn",
  "Organizer phone": "Arrangörstelefon",
  "Organizer email": "Arrangörens e-post",
  "Organizer website": "Arrangörens webbplats",
  "Personal info": "Personlig information",
  "First name": "Förnamn",
  "Last name": "Efternamn",
  "Email Address": "E-postadress",
  "Additional Notes": "Ytterligare anmärkningar",
  Back: "Tillbaka",
  Save: "Spara",
  Next: "Nästa",
  "Your event has been submitted": "Ditt evenemang har skickats in",
  "Event submittion has been failed": "Inlämning av händelse misslyckades",
  "e.g. Birthday Party": "t.ex. Födelsedagskalas",
  "First Name": "Förnamn",
  "Last Name": "Efternamn",
  "Phone Number": "Telefonnummer",
  Address: "Adress",
  "Your comments": "Era kommentarer",
  "How many guests?": "Hur många gäster?",
  "Anything else we need to know?": "Något annat vi behöver veta?",
  "Guests:": "Gäster:",
  Submit: "Skicka in",
  "Go to Calendar": "Gå til Kalender",
  "Registration completed successfully!": "Registreringen är klar!",
  "Please check your registered email address":
    "Kontrollera din registrerade e-postadress",
  "Add to Calendar": "Lägg till i din kalender",
  "Share this Event": "Dela denna händelse",
  "Sorry something went wrong": "Förlåt, något gick fel",
  "Back to registration": "Tillbaka till registrering",
  "Date & Location": "Datum och plats",
  "Date & Time": "Datum tid",
  home: "Hem",
  "Header align": "Header justera",
  Footer: "Sidfot",
  "Categories Filter": "kategorier Filter",
  "Show only upcoming": "Visa bara kommande",
  "Card(s) in a row": "Kort i rad",
  "Space between cards": "Mellanslag mellan kort",
  "Shown events limit": "Visade händelsegränser",
  "Style 1": "Stil 1",
  "Style 2": "Stil 2",
  "Style 3": "Stil 3",
  "Style 4": "Stil 4",
  "Buttons & Links": "Knappar och länkar",
  "Button corner radius": "Knapp hörnradie",
  "Buttons font": "Knappar teckensnitt",
  "Buttons background": "Knappar bakgrund",
  "Get notified by Email": "Få avisering via e-post",
  "Review events": "Granska händelser",
  "Click on date": "Klicka på datum",
  "Add Event button": "Knappen Lägg till händelse",
  "Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Med kalendersynkronisering kan du integrera dina händelser och sessioner med din Boom-kalender.",
  connect: "ansluta",
  "Synchronized Calendars": "Synkroniserade kalendrar",
  "Import events": "Importera händelser",
  Disconnect: "Koppla ifrån",
  "Choose calendar": "Välj kalender",
  "Monitor your Wix events through the sync feature":
    "Övervaka dina Wix-händelser genom synkroniseringsfunktionen",
  "Connect all your Boom calendars available on your website":
    "Anslut alla dina boomkalendrar tillgängliga på din webbplats",
  "Schedule, join, and manage Zoom meetings right through our Boom Calendar.":
    "Schemalägg, gå med och hantera Zoom-möten direkt via vår Boom Calendar.",
  "Monitor your Event Brite events through the Event Brite sync feature..":
    "Övervaka dina Event Brite-händelser via Sync-funktionen för Event Brite",
  Email: "E-post",
  "Add-ons": "Lägg till",
  "Receive notification emails as soon as users add events to your calendar.":
    "Ta emot meddelandemail så snart användarna lägger till evenemang i din kalender.",
  "Enable + button on the calendar header":
    "Aktivera + knappen på kalenderhuvudet",
  "Accept or decline events added by customers before making them public.":
    "Acceptera eller avvisa händelser som läggs till av kunder innan de gör dem offentliga.",
  "Switch Add Event": "Byt tilläggshändelse",
  "Enable your browser cookies to connect to your account.":
    "Aktivera dina webbläsarkakor för att ansluta till ditt konto.",
  "Learn more": "Läs mer",
  "Print Button": "Tryckknapp",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "อนุญาตให้ผู้ใช้ของคุณพิมพ์ปฏิทินกิจกรรมบูมของคุณในช่วงวันที่ใดก็ได้",
  "Show Title on mobile": "Visa titel på mobilen",
  "Show Skeleton on mobile": "Visa skelett på mobilen",
  "Start 7-day Business trial": "Starta din 7-dagars affärsförsök",
  "Enjoy all the Unlimiited features, such as Sell tickets, Registration, Visitor event add-ons.":
    "Njut av alla obegränsade funktioner, till exempel att sälja biljetter, registrering, besökarevenemang.",
  "Please note: At the end of the trial period, you will be returned to your existing subscription plan.":
    "Observera: I slutet av försöksperioden kommer du att returneras till din befintliga prenumerationsplan.",
  "Not Now": "Inte nu",
  "Start free trial": "Påbörja gratis provperiod",
  "Congrats!": "grattis!",
  "Your 7-day Business trial has been successfully activated.":
    "Din 7-dagars affärsförsök har framgångsrikt aktiverats.",
  Done: "Gjort",
  "Title font color": "Titel typsnitt",
  "Desciption font color": "Beskrivning Font Färg",
  "Section font color": "Sektion teckensnittsfärg",
  "Card Header": "Kortrubrik",
  Category: "Kategori",
  "Display at the": "Visa på",
  top: "topp",
  bottom: "botten",
  "Showcase the category filter at the top or at the bottom of the calendar. The settings applies to Agenda and Card views only":
    "Visa kategorifiltret längst upp eller längst ner i kalendern.Inställningarna gäller endast för agenda och kortvisningar",
  "Processing your events": "Bearbetar dina händelser",
  "Search for events": "Sök efter händelser",
  "There are no events added": "Det finns inga händelser som läggs till",
  "Location: To be determined": "Plats: att bestämmas",
  "No events for selected date": "Inga händelser för valda datum",
  Uncategorized: "Okategoriserad",
  "Edit event": "Redigera händelse",
  "Edit original event": "Redigera originalhändelse",
  "Copy event": "Kopieringshändelse",
  "Copy as new event": "Kopiera som nytt evenemang",
  "Delete event": "Radera händelse",
  "Stop repeating on this date": "Sluta upprepa på detta datum",
  "Exclude this date": "Uteslut detta datum",
  "Location is going to be announced": "Plats kommer att meddelas",
  "Fill your personal information": "Fyll din personliga information",
  "Check Box": "Kryssruta",
  "Single Choice": "Enskilda val",
  Option: "Alternativ",
  "Share Event": "Delaevenemang",
  "Oops! Something went wrong": "hoppsan!Något gick fel",
  "We are sorry this event has already taken place":
    "Vi är ledsna att den här händelsen redan har ägt rum",
  "Back to calendar": "Tillbaka till kalendern",
  "This field is required": "Detta fält krävs",
  Phone: "Telefon",
  "Number field": "Nummerfält",
  "Please provide a valid email": "Var god ange en giltig e-postadress",
  "Select at least one option": "Välj minst ett alternativ",
  "Choose tickets to see total value":
    "Välj biljetter för att se det totala värdet",
  tickets: "biljetter",
  "Choose Tickets": "Välj biljetter",
  "Choose payment method": "Välj betalsätt",
  Pay: "Betala",
  Total: "Total",
  Free: "Gratis",
  "Buy tickets": "Köpa biljetter",
  "Sold Out": "Utsåld",
  "Tickets are available": "Biljetter finns tillgängliga",
  "Sales End": "Försäljningsslut",
  "Availible from": "Tillgänglig från",
  "Go to Orders": "Gå till order",
  "Go to Details": "Gå till detaljer",
  "Group ticket": "Gruppbiljett",
  Name: "Namn",
  Price: "Pris",
  "Order by": "Sortera efter",
  "Order ID": "Beställnings -ID",
  Applied: "Applicerad",
  Fees: "Avgifter",
  "Enter promo code": "Ange kampanjkod",
  Apply: "Tillämpa",
  "Promo Code": "Rabattkod",
  Cash: "Kontanter",
  "You can find your e-tickets attached to your email or download them":
    "Du kan hitta dina e-biljetter kopplade till din e-post eller ladda ner dem",
  here: "här",
  Time: "Tid",
  "Invalid promo code": "Ogiltig kampanjkod",
  "Credit card": "Kreditkort",
  "You will soon receive a confirmation message of successful registration to your email address.":
    "Du kommer snart att få ett bekräftelsemeddelande om framgångsrik registrering till din e -postadress.",
  "You can also check your order details below.":
    "Du kan också kontrollera dina beställningsuppgifter nedan.",
  at: "på",
  Buy: "köpa",
  Donation: "Donation",
  "Enter price": "Företag",
  Choose: "Välja",
  Chosen: "Vald",
  "Choose your plan": "Välj din plan",
  week: "vecka",
  wk: "vecka",
  "Choose plan cycle": "Välj plancykel",
  months: "månad",
  years: "år",
  weeks: "Veckor",
  "Copy Event Url": "Kopiera Event -URL",
  "You can find your e-tickets attached to your email or print them":
    "Du kan hitta dina e-biljetter kopplade till din e-post eller skriva ut dem",
  "Guest Info": "Gästinformation",
  "Ticket Info": "Biljettinformation",
  "Ticket name": "Biljettnamn",
  "Ticket price": "Biljettpris",
  "Ticket ID": "Biljett -ID",
  "If you have any questions contact to organizer":
    "Om du har några frågor Kontakt till arrangören",
  "As soon as event ends": "Så snart händelsen slutar",
  "1 day after event ends": "1 dag efter evenemanget slutar",
  "7 days after event ends": "7 dagar efter evenemangets slut",
  "14 days after event ends": "14 dagar efter evenemangets slut",
  "30 days after event ends": "30 dagar efter evenemangets slut",
  Menu: "Meny",
  "No event for selected date": "Inget evenemang för valt datum",
  view: "se",
  List: "Lista",
  Year: "År",
  "Yearly Style": "Årstil",
  "There are no events": "Det finns inga händelser",
  Autotranslation: "Autotranslation",
  "Once enabled, your calendar widget will be translated based on the website’s language. *note that as long as calendar title, and descriptions are inputted texts they can not be translated.":
    "När den är aktiverad kommer din kalender widget att översättas baserat på webbplatsens språk.* Observera att så länge kalendertitel och beskrivningar är inmatade texter kan de inte översättas.",
  "Note on mobile": "Obs på mobilen",
  "Turn off or change the text of the “No events” bar on mobile version of calendar":
    "Stäng av eller ändra texten på 'No Events' -fältet på mobilversion av kalendern",
  Autodeletion: "Autodeletion",
  "Enabling the option, will automatically remove your past events from the calendar.":
    "Aktivera alternativet tar automatiskt bort dina tidigare händelser från kalendern.",
  "This does not apply to repeating events!":
    "Detta gäller inte för upprepande händelser!",
  "Notify event creators about the guest": "Meddela användare om gästen",
  "Send event creators notification emails as soon as guests register for their events":
    "Skicka e-postmeddelanden om evenemangsskapare så snart gästerna registrerar sig för sina evenemang",
  "List View Type": "Listvy typ",
  Yearly: "Årlig",
  "Year view header": "Årsvyrubrik",
  "Description font": "Teckensnitt - Beskrivning ",
  Connect: "ansluta",
  "You have no events": "Du har inga händelser",
  Synchronize: "Synkronisera",
  "Google Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Med Google Kalender-synkronisering kan du integrera dina händelser och sessioner med din Boom-kalender.",
  "Outlook Calendar sync allows you to integrate your events and sessions with your Boom Calendar.":
    "Outlook Calendar Sync tillåter dig att integrera dina evenemang och sessioner med din bomkalender.",
  "Your message has been sent successfully!":
    "Ditt meddelande har skickats framgångsrikt!",
  "There are no synchronized calendars":
    "Det finns inga synkroniserade kalendrar",
  "to view more than 7 events": "För att se mer än 7 händelser",
  "Mobile app": "Mobil app",
  "Admin Account": "Adminkonto",
  Password: "Lösenord",
  "Second User": "Andra användare",
  Edit: "Redigera",
  "Guest limit": "Gästgräns",
  "Monthly view": "Månadsvisning",
  "Set Proportions": "Ställ in proportioner",
  "All the local settings are (automatically) based on your language. If your language is on the list, there 's no need to customize this section.":
    "Alla lokala inställningar är (automatiskt) baserat på ditt språk.Om ditt språk är på listan, är det inte nödvändigt att anpassa det här avsnittet.",
  "Hosting events that last all day? This lets you show them on your calendar.":
    "Hosting händelser som varar hela dagen?Detta låter dig visa dem på din kalender.",
  available: "tillgängligt",
  next: "Nästa",
  Tickets: "Biljetter",
  Quantity: "Kvantitet",
  "Promo code": "Rabattkod",
  "Select a payment method": "Välj en betalningsmetod",
  Fee: "Avgift",
  Book: "bok",
  "All the tickets have been sold out": "Alla biljetter har sålts ut",
  "Choose at least one ticket": "Välj minst en biljett",
  "First choose ticket": "Välj först biljett",
  "Please fill out your personal information.":
    "Vänligen fyll i din personliga information.",
  "To make a successful purchase, please select your preferred payment method and enter the promo code for discounted tickets.":
    "För att göra ett framgångsrikt köp, välj önskad betalningsmetod och ange promo-koden för rabatterade biljetter.",
  "Credit/Debit card": "Kredit / Betalkort",
  "print here.": "Skriv ut här.",
  "QR code for all tickets": "QR-kod för alla biljetter",
  Duration: "Varaktighet",
  "Full Name": "Fullständiga namn",
  "Ticket id": "Biljett ID",
  "Group id": "Grupp id",
  "Choose your ticket.": "Välj din biljett.",
  "Fill out your personal information.": "Fyll i din personliga information.",
  "Add the payment details.": "Lägg till betalningsuppgifterna.",
  "To be determined": "Att vara bestämd",
  "You can find your e-tickets attached to the email or":
    "Du kan hitta dina e-biljetter bifogade e-postmeddelandet eller",
  "print here": "Skriv ut här",
  "Full name": "Fullständiga namn",
  "Group ID": "Grupp id",
  "to Book": "att boka",
  "Unfortunately, your card has been declined":
    "Tyvärr har ditt kort blivit avvisat",
  "Thank you for your purchase!": "Tack för ditt köp!",
  "Find your printable e-tickets attached to the confirmation email":
    "Hitta dina utskrivbara e-biljetter kopplade till bekräftelsemailen",
  Confirm: "Bekräfta",

  "Add event": "Lägg till händelse",
  Events: "evenemang",
  "Event details": "Evenemangsdetaljer",
  Registration: "Registrering",
  "Guests list": "Gästlistan",
  Ticket: "Biljett",
  "General Info": "Generell information",
  "Customize the general settings of your event":
    "Anpassa de allmänna inställningarna för ditt evenemang",
  "Event Title": "Evenemangstitel",
  "e.g. Birthday Party": "t.ex. Födelsedagskalas",
  "All Day Event": "Heldagsevent",
  Cross: "Korsa",
  Timeline: "Tidslinje",
  "Repeating event": "Upprepande händelse",
  Location: "Plats",
  "Venue name": "Platsnamn",
  Description: "Beskrivning",
  Image: "Bild",
  Color: "Färg",
  Category: "Kategori",
  "Add your events to color categories and let your users classify them easily":
    "Lägg till dina evenemang i färgkategorier och låt dina användare klassificera dem enkelt",
  "Category name": "Kategori namn",
  "e.g. Birthdays": "t.ex. Födelsedag",
  Venue: "Mötesplats",
  "Where the event takes place": "Där evenemanget äger rum",
  "Venue name": "Platsnamn",
  "Venue phone": "Telefontelefon",
  "Venue email": "E -postmeddelande",
  "Venue website": "Platsplats",
  Organizer: "Arrangör",
  "Person who makes the event": "Person som gör evenemanget",
  "Organizer name": "Arrangörnamn",
  "Organizer phone": "Arrangörstelefon",
  "Organizer email": "E -postmeddelande",
  "Organizer website": "Arrangörwebbplats",
  Save: "Spara",
  Cancel: "Annullera",
  Import: "Importera",
  Past: "Dåtid",
  All: "Allt",
  Upcoming: "Kommande",
  Uncategorised: "Okategoriserad",
  "Date Ascending": "Datum stigande",
  "Date Descending": "Datum fallande",
  "Title by A-Z": "Titel av A-Z",
  "Title by Z-A": "Titel av z-a",
  "There are no events for this period":
    "Det finns inga händelser för denna period",

  "Auto-Convert Date & Time": "Auto-konverterat datum och tid",
  TimeZone: "Tidszon",
  Autodeletion: "Autodeletion",
  "Layout Settings": "Layout inställningar",
  "Yeatly view": "Ja",
  "Monthly view header": "Månadsvisningshuvud",
  "Weekly/Daily view header": "Veckovis/Daily View -rubrik",
  Acendings: "Acendings",
  Descending: "Nedåtgående",
  Standart: "Standart",
  Silver: "Silver",
  Retro: "Retro",
  Dark: "Mörk",
  Night: "Natt",
  Aubergine: "Aubergine",
  "List view header": "List Visa rubrik",
  "Side by Side View": "Sidan vid sidovy",
  "Customize Proportions": "Anpassa proportioner",
  "Card Margins": "Kortmarginaler",
  "Image opacity (%)": "Image Opacity (%)",
  "Side by Side Header": "Sida vid sidhuvud",
  "Text Align": "Textinriktning",
  "Timeline View": "Tidslinjevy",
  "Title font color": "Teckensnittsfärg",
  "Desciption font color": "Fontfärg",
  "Line color": "Linjefärg",
  "Date Font color": "Datumteckensnittsfärg",
  "Daily events background": "Daglig händelsesbakgrund",
  Alignment: "Inriktning",
  Vertical: "Vertikal",
  Horizontal: "Horisontell",
  "Vertical Alignment": "Vertikal inriktning",
  Right: "Höger",
  Center: "Centrum",
  "Horizontal Alignment": "Horisontell linjering",
  Top: "Topp",
  Center: "Centrum",
  Bottom: "Botten",
  "Dates Circle Design": "Datum Circle Design",
  "Next To The Circle": "Bredvid cirkeln",
  "In The Circle": "I cirkeln",
  "Timeline Header": "Tidslinjehuvud",
  Timeline: "Tidslinje",
  "Show only upcoming": "Visa endast kommande",
  "Order by": "Sortera efter",
  "Timeline Event Limit": "Tidslinjehändelsesgräns",
  "Allow visitor to add event to local Calnedars: Google, Yahoo, Outlook, ICalendar.":
    "Tillåt besökare att lägga till evenemang till lokala Caledars: Google, Yahoo, Outlook, Icalendar.",
  "Allow visitor to share your event to Facebook, Linkedin, Twitter and etc.":
    "Låt besökaren dela ditt evenemang till Facebook, LinkedIn, Twitter och etc.",
  "Add a search option on your calendar to let people search your events by title, venue, etc.":
    "Lägg till ett sökalternativ i din kalender för att låta människor söka efter dina evenemang efter titel, plats, etc.",
  "Permit your users to print your Boom Event Calendar in any date range.":
    "Tillåt dina användare att skriva ut din Boom Event -kalender inom valfritt datumintervall.",
  "Click to apply a theme to Calendar":
    "Klicka för att tillämpa ett tema på kalendern",
  "Date container color": "Datum behållarfärg",
  "Daily events background": "Daglig händelsesbakgrund",
  "Use the Add-ons to install advanced features on your calendars, making them more functional!":
    "Använd tilläggen för att installera avancerade funktioner i dina kalendrar, vilket gör dem mer funktionella!",
  "Open Add-ons Store": "Öppna tillägg",
  Monday: "Måndag",
  Tuesday: "Tisdag",
  Wednesday: "Onsdag",
  Thursday: "Torsdag",
  Friday: "fredag",
  Saturday: "Lördag",
  Sunday: "Söndag",
  Ascending: "Stigande",
  "Yearly view": "Torsdag",
  "Show event time next to title": "Visa händelsetid bredvid titeln",
  "Adjust the event date and time to the user's local time based on their time zone.":
    "Justera händelsedatum och tid till användarens lokala tid baserat på deras tidszon.",
  "Display the time zone alongside the event date.":
    "Visa tidszonen tillsammans med händelsedatumet.",
  "Show event time next to title": "Visa händelsetid bredvid titeln",
  "Time Zone": "Tidszon",
  "Upload Image": "Ladda upp bild",
  "Choose a Category": "Välj en kategori",
  "Color you have chosen will not be shown as you choose category":
    "Färg som du har valt kommer inte att visas när du väljer kategori",
  Website: "Hemsida",
  Next: "Nästa",
  Save: "Spara",
  "Last Name": "Efternamn",
  "Personal Info": "Personlig information",
  Back: "Tillbaka",
  "This field is required": "Detta fält krävs",
  "Your event has been submitted": "Ditt evenemang har lämnats in",
  "Enter a location": "Ange en plats",
  "Display the time zone alongside the event date.":
    "Visa tidszonen tillsammans med händelsedatumet.",
  Home: "Hem",
  "Side By Side Event Limit": "Sidan vid sidoevenemangsgränsen",
  "Mobille App": "Mobila app",
  category: "kategori",
  "Keep track of your schedule easily by importing your Facebook events to your calendar.":
    "Håll koll på ditt schema enkelt genom att importera dina Facebook-evenemang till din kalender.",
  "Synchronized Pages": "Synkroniserade sidor",
  "There are no synchronized pages": "Det finns inga synkroniserade sidor",
  "Choose page": "Välj sida",
  "You have no events": "Du har inga händelser",
  "Add Script": "Lägg till skript",
  "script bound": "Det här skriptet är redan bundet, välj andra detaljer!",
  "Choose account": "Välj konto",
  "Choose resource": "Välj resurs",
  "Reconnect": "Återansluta",
  "script disappear": "Det här skriptet finns inte, lägg till skript i din Google Analytics!",
  "Reset Layouts Dimensions": "Återställ layouter dimensioner",
  "Clear": "Rensa",
  "Undo": "Ångra",
  "Redo": "Göra om",
  "Code Panel": "Kodpanel",
  "Code Panel Notify": "Modifierande kod direkt kan bryta layouten eller appfunktionaliteten. Redigera bara om du vet vad du gör!",
  "Clear Editor": "Clear Redaktör",
  "Clear Editor Notify": "Är du säker på att du vill rensa redaktören? Alla framsteg kommer att gå förlorade!",
  "Nothing to edit": "Det finns inget att redigera!",
  "Shapes": "Former",
  "Delete The Shape": "Ta bort formen",
  "Add shapes": "Lägg till former mellan layouter och anpassa!",
  "Preview unavailable": "Förhandsvisning av komponenten är inte tillgänglig för komponent",
  "component removed": "Komponent tas bort från redaktören.",
  "component duplicate": "Komponent Tillagd, Obs: Duplicate Entry!",
  "component added": "Komponent läggs framgångsrikt till redaktören.",
};
export default sv;
